ycm-core/YouCompleteMe

- README.md
Fixes #1317. Also adds an h2 level "Installation" section header and demotes the platform-specific installation headers to h3.
If we want to keep the top-level table of contents as small as possible, we could move the sub-tables down to below the header for their respective section. Eg. move the "User Guide" table of contents down to below the "User Guide" header from its current placement as a sub-list in the main table.
Also, the Commands section could get its own table of contents listing the individual command names, but there are enough commands that I wouldn't recommend doing this unless the table was placed below the Commands section header. It would be useful for those who generally know what command they are looking for but have simply forgotten the exact name.
> Table of contents in README

- run_tests.sh
Allow user to skip build when running tests.
This is required if you have to pass custom parameters to the build.
> Test suite: allow skipping of build step

- README.md
It would be faster to look up the Options section with a link, without scrolling way down to the bottom of the page.
> Add link to Options section

- README.md
- python/ycm/client/command_request.py
This is required to allow the ycmd GetType and GetParent subcommands to echo
their reults in vim. The apporach is to display any text returned from a
subcommand in the 'message' property assuming that the command is not a known
'GoTo' command.
> Support completer commands that return text

- python/ycm/vimsupport.py
C requires a newline at the end of any file, Vim always includes one. With -Weverything, YCM warns that it's missing, because joining the lines of the buffer doesn't reflect the implicit newline. Adding a newline makes the buffer text match what will be saved, and makes the warning go away. This impacts any C source file compiled with sufficient warnings (e.g. -Weverything).
I've signed the Google CLA.
> Fix spurious warning about missing newline at EOF

- README.md
Gocode is now supported using the Completer API.
Related: Valloric/ycmd/pull/106
> Update README for Gocode support in ycmd.

- .travis.yml
Pip no longer supports --use-mirrors since version 1.5. See https://github.com/pypa/pip/pull/1098.
CLA signed.
> Remove deprecated --use-mirrors argument from pip

- README.md
The docs say:
> YCM is designed to work with libclang version 3.6 or higher, but can in theory work with any 3.2+ version as well.
So I don't think the link should link to 3.3.
> Don't link to specific clang version

- autoload/youcompleteme.vim
Previously: https://github.com/neovim/neovim/issues/2782
> Remap <Nul> to <C-Space> regardless of gui_running since it is an unreliable way of detecting terminals in neovim

- python/ycm/client/completer_available_request.py
- python/ycm/youcompleteme.py
Previously we were checking if the `hook.py` file existed for the given
filetype. ycmd has an endpoint for checking if given a filetype a
semantic completer is available. Should fix #1284.
I've signed the CLA
> Check the server end point for available completer

- python/ycm/youcompleteme.py
#1531 seems sensible: if one disable `javascript` I guess that `javascript.jasmine` should be disable as well.
Fixes #1531
> Disable completion if any of current filetypes is disable

- autoload/youcompleteme.vim
I had the check for the omnifunc set backwards. I will start to see if we can start testing the vimscript layer as well. I have signed the CLA.
> Fix check condition for setting omnifunction

- python/ycm/vimsupport.py
There has been several complaints about the message "ValueError: File is less than 5 lines long; not compiling". See issues #814, #1364, #1544. In fact, I believe the issue is not the message itself but the infamous "Press ENTER or type command to continue" prompt when editing a new C-family file.
For example, if I create the file `foo.c`, Vim will display the line `"foo.c" [New file]` and then YouCompleteMe will display `ValueError: File is less than 5 lines long; not compiling`. Since there are now two lines, the hit-enter message is prompted. By redrawing the screen just before displaying the message from YouCompleteMe, only one line appears and we avoid this behavior.
Tested on Linux and Windows.
CLA signed.
> Redraw the screen before displaying a message

- python/ycm/youcompleteme.py
Commit 98d687a5e02548fafc05397aaab38e8735078ff4 causes a Python crash in Vim on Windows. This is due to the `SafePopen` call in `s:SetUpPython` function which sets `stdin` to `PIPE` on Windows. 
Since the `stdin` option is only necessary when starting the `ycmd` server (in `python/ycm/youcompleteme.py`), this PR and PR Valloric/ycmd#173 introduce a new option `stdin_windows` to `SafePopen` that sets `stdin` to `PIPE` on Windows. This option is only used when starting the `ycmd` server. 
CLA signed.
> Set stdin to PIPE on Windows only when necessary

- README.md
New MacVim site is located at GitHub. The repository is at
https://github.com/macvim-dev/macvim and releases page
at https://github.com/macvim-dev/macvim/releases
> Update MacVim location

- README.md
- python/ycm/client/command_request.py
- python/ycm/diagnostic_interface.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
This change provides the client-side support in YouCompleteMe for vim providing a new :YcmFixIt command which applies changes to the vim buffer to implement trivial fixes to common coding errors where the completer provides instructions on how to fix a diagnostic. A note is added "(FixIt)" to the diagnostic text echo'd in vim when a FixIt is available.
While this may seem out of the scope of ycmd/YouCompleteMe (as a completion engine), I think it is a really useful feature, and provided straight out of libclang. so I'm sending this slightly incomplete PR (along with the associated ycmd change) to see what the appetite is within the user and maintainer community, and to get feedback on the approach.
I know that I need to write some tests, and perhaps tidy up some TODOs, but I would really …
> [RFC] YCM Client support for FixIt commands

- python/ycm/client/base_request.py
- python/ycm/client/completion_request.py
Needed for https://github.com/Valloric/ycmd/pull/198
This maintains the previous client behaviour when the semantic completer throws an exception.
> If errors are returned in addition to completion suggestions, print them

- install.sh
People like me use YCM on machines that don't have bash, and it's nice to not have to add it unnecessarily. This removes the bash dependency for installation.
> Removed the bash dependency that install.sh had

- README.md
- doc/youcompleteme.txt
Because badges need consideration (and it [still](https://github.com/Valloric/ycmd/pull/207) looks better).
> Use SVG Travis badge instead of PNG

- python/ycm/client/completion_request.py
- python/ycm/client/tests/completion_request_test.py
Fixes https://github.com/Valloric/YouCompleteMe/issues/106
We add the detailed_info (which is the function definiton) followed by the brief comment if supplied.
I added a test for the method, which is now reasonably complex.
> Show docs from clang completer in preview window

- python/ycm/client/command_request.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
While playing with FixIts in C++, I found the following issue. When fixing the third line in the code:
```cpp
template<int Value> struct CT { template<typename> struct Inner; };
CT<10 >> 2> ct; // expected-warning{{require parentheses}}
```
the following result is obtained:
```cpp
CT<1(0 >> 2)> ct; // expected-warning{{require parentheses}}
```
which is obviously wrong.
The issue is YouCompleteMe does not replace the chunks in the right order. It starts by adding the closing parenthesis, add one to the delta and inserts the opening parenthesis in the wrong place cause of the delta.
We actually use the expression `str(line) + ',' + str(column)` to sort the chunks by line then column whereas it should simply be `(line, column)`.
This PR fixes this issue, adds two tests which are failing in …
> Correct FixIt chunks sorting

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
- python/ycm/client/completion_request.py
- python/ycm/client/tests/completion_request_test.py
- python/ycm/tests/postcomplete_tests.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
When forcing semantic completion with the keybind, C# completions can return a list of importable types. These types are from namespaces which havn't been imported, and thus are not valid to use without also adding their namespace's import statement. This change makes YCM automatically insert the necessary using statement to import that namespace on completion completion. In the case there are multiple possible namespaces, it prompts you to choose one.
Demo:
By default, the using statement is inserted after the last using statement. If there aren't any, it's inserted before the first line. This behavior is customization by setting a function to the vim global ``g:ycm_cs_insert_namespace_function``. I implemented this in pure vimscript largely so I could provide such customization... …
> Add required namespace in C# after completing

- README.md
- doc/youcompleteme.txt
Noticed that the subcommands supported by typescript are not listed. Updated the docs and ran
```
vim-tools/html2vimdoc.py -f youcompleteme README.md > doc/youcompleteme.txt
```
> Update subcommmands supported for typescript

- README.md
- doc/youcompleteme.txt
I never got time to do the larger revamp of the README.md, but I thought a super-quick summary would be useful, as I'm about to add yet-another subcommand to a bunch of completers.
> Add super-quick feature summary by completer

- README.md
- doc/youcompleteme.txt
Fixes https://github.com/Valloric/YouCompleteMe/issues/1653
This change:
* updates the `README.md` and vim help
* updates the `ycmd` submodule to latest master, which includes `GetDoc` subcommand
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1701)
> Declare support for GetDoc subcommand

- python/ycm/vimsupport.py
One of my coworkers found this crash today. Usually he opens a lot of gvim-s and forgets about them, and eventually one of GoToDefinition commands backfired :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1732)
> Fix rare crash when trying to jump to file which has .swp

- autoload/youcompleteme.vim
Vim commands (`YcmDebugInfo`, `YcmCompleter`, etc.) should not be defined if an error is encountered when processing the `s:SetUpPython` function. Why? Because those commands will return errors like `name 'ycm_state' is not defined`.
Note: due to an unexpected behavior, those commands work fine when libraries are found outdated. See issue #1726.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1727)
> Define Vim commands only if setup is successful

- CONTRIBUTING.md
- README.md
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
- python/ycm/youcompleteme.py
The `g:ycm_server_use_vim_stdout` option is not working like expected. ycmd logs are not written to the console when using the gui client with this option enabled. This is the case on Windows and I think @puremourning can confirm this on other platforms. Worse, it also makes the ycmd server unresponsive on Windows.
It's a big issue because we recommend to use this option in [CONTRIBUTING.md](https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md).
This PR removes the option and updates the contribution guidelines by asking the user to put the `let g:ycm_server_keep_logfiles = 1` option instead.
To further improve the debugging process, I would like to add a new command `:YcmToggleLogs` (thanks to @puremourning for the idea) that automatically open or close the ycmd stdout …
> Remove g:ycm_server_use_vim_stdout option

- appveyor.yml
AppVeyor certainly made some changes to their infrastructures because the `run_tests.py` script is not properly executed anymore. We now need to specifically call it with python.
This is already done in the `ycmd` repository so no changes needed there.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1761)
> Fix AppVeyor configuration

- .travis.yml
- python/test_requirements.txt
- run_tests.py
- travis/travis_install.linux.sh
- travis/travis_install.osx.sh
- travis/travis_install.sh
There should be no difference between the behaviour on OS X and the behaviour on other platforms as all of the tests are python. However, running them is cheap and proves that there are no differences.
The approach is to import the scripts from `ycmd` with a couple of modifications:
- don't set `YCM_CORES=1` as we didn't before, and this makes the build a lot faster
- don't install `gcc-4.8` as we didn't before
- install `argparse` for the tests as it is not available in python2.6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1762)
> Run tests on OS X

- CONTRIBUTING.md
- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
Two approaches were proposed in PR #1753:
- open the stdout and stderr logfiles in Vim windows or close them if already opened: `:YcmToggleLogs`;
- open one of the logfiles in the preview window by specifying it as an argument in the command: `:YcmShowLog <stdout|stderr>`.
This PR merges both approaches by adding an optional argument (`Stdout` or `Stderr`) to the first approach. When no argument is given, both logfiles are opened (or closed if already opened).
With this approach, we cannot use the preview window because only one such window is allowed by Vim. So, we simulate it by adding properties specific to the preview window (horizontal split, height, etc.)
Since they are multiple ways to open a file in Vim, I added a generic function `OpenFilename` for this. It makes easy to …
> Introducing :YcmToggleLogs command

- python/ycm/client/command_request.py
`ServerReady`, `ServerRunning`, and `ServerTerminated` C♯ subcommands could return a traceback or nothing in Vim because ycmd returns a boolean as the response of these commands.
Fix this by echoing `Yes` when the response is `True`, `No` otherwise.
Refactor the `RunPostCommandActionsIfNeeded` function to improve readability.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1805)
> Handle boolean responses from ycmd subcommands

- python/ycm/client/command_request.py
In continuation to PR #1805, when the ycmd server returns a canonical type (boolean, number, string, etc.), we should print it to the user.
For example, this applies to the `SolutionFile` C♯ subcommand which only returns a string (actually, this could be improved in the completer).
This also fixes a thrown exception when the response is not iterable (a number for example).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1807)
> Handle canonical response from subcommands

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/diagnostic_interface.py
- python/ycm/youcompleteme.py
@Valloric I've implemented two functions which resolve #1011 
The interface exposed to Vim is:
```viml
youcompleteme#GetErrorCount()
youcompleteme#GetWarningCount()
```
Below is a rough example of how these methods can be used to integrate with other plugins. In this case Lightline has been extended to show the error and warning count as red and yellow sections on the end of the status line, respectively.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1814)
> Expose functions to get error and warning counts

- python/ycm/youcompleteme.py
Currently, only `all` snippets are displayed by YCM because UltiSnips is called without setting the buffer filetypes. See issue #1818.
This is fixed by using UltiSnips methods `reset_buffer_filetypes` and `add_buffer_filetypes`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1821)
> Set buffer filetypes for UltiSnips

- autoload/youcompleteme.vim
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/postcomplete_tests.py
- python/ycm/youcompleteme.py
- run_tests.py
Fixes #1829 
Detailed analysis is available on [the issue](https://github.com/Valloric/YouCompleteMe/issues/1829). But principally: if the filetype being edited is not a filetype suporting YCM native diagnostics, then warnings, errors, etc. (including the "unknown extra conf" warning/prompt) are not displayed after the "FileReadyToParse" `event_notification`
The approach is: for filetypes which do not support diagnostics, rather than ignoring all `FileReadyToParse` event responses, simply call the `Response` method, which raises the appropriate error or handles the "confirm extra-conf" behaviour. Any other data returned by the completer (such as diagnostics!), are simply ignored.
Tested with tern completer which raises an error if the `.tern-project` file is not found.
Tested with a …
> [READY] Raise warnings on FileReadyToParse for completers not supporting diagnostics

- README.md
- doc/youcompleteme.txt
Adds support for native JavaScript completion using ycmd's Tern completer.
WIP because relies on #1848 to be merged first.
This PR:
- Adds functional documentation to the README.md
- Adds configuration documentation to the README.md
- Updates the vim doc inline with the above
- And, most importantly, updates `ycmd` submodule to include the Tern completer and the additional fixes.
There are quite a lot of commits going in to ycmd. Here's a summary of the PRs:
```
8ec8386 Auto merge of #283 - micbou:appveyor-python-issue, r=puremourning
d079a92 Auto merge of #280 - puremourning:tern-global-config, r=Valloric
dee9afe Auto merge of #281 - puremourning:tern-timeout-exit, r=Valloric
24f5d51 Auto merge of #279 - micbou:coverage, r=Valloric
115a51d Auto merge of #275 - d0k:reparse, r=Valloric …
```
> [READY] Add JavaScript completion using Tern completer

- install.py
Without this install.py always exits 0 and no way to tell vim-plug its installation actually failed.
Before:
```
$ ./install.py
...
-- Configuring incomplete, errors occurred!
See also "/tmp/ycm_build.Vu_ej5/CMakeFiles/CMakeOutput.log".
See also "/tmp/ycm_build.Vu_ej5/CMakeFiles/CMakeError.log".
File "/root/.vim/plugged/YouCompleteMe/third_party/ycmd/build.py", line 312, in <module>
Main()
File "/root/.vim/plugged/YouCompleteMe/third_party/ycmd/build.py", line 303, in Main
BuildYcmdLibs( args )
File "/root/.vim/plugged/YouCompleteMe/third_party/ycmd/build.py", line 248, in BuildYcmdLibs
subprocess.check_call( [ 'cmake' ] + full_cmake_args )
File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
raise CalledProcessError(retcode, cmd) …
```
> Use check_call to capture error from build process

- python/ycm/youcompleteme.py
A traceback is raised in Vim when completing in a C♯ file while the ycmd server crashed:
```
Error detected while processing function <SNR>27_OnCompleteDone:
line    1:
Error detected while processing function <SNR>27_OnCompleteDone:
line    1:
File "<string>", line 1, in <module>
Error detected while processing function <SNR>27_OnCompleteDone:
line    1:
File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\../python\ycm\youcompleteme.py", line 305, in OnCompleteDone
Error detected while processing function <SNR>27_OnCompleteDone:
line    1:
action(self)
Error detected while processing function <SNR>27_OnCompleteDone:
line    1:
File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\../python\ycm\youcompleteme.py", line 102, in <lambda> …
```
> [READY] Fix traceback when v:completed_item is empty

- autoload/youcompleteme.vim
This basically is a return to the older approach where everything is done on OnBufferVisit. This way we just defer the first time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1770)
> Defer setting the omnifunc only the first time

- python/ycm/client/command_request.py
- python/ycm/client/tests/command_request_test.py
- python/ycm/vimsupport.py
When a `GoTo` command returns a list of destinations, such as declarations and definitions in Python and references in JavaScript, we pop the Vim quick fix list with a list of destinations. however, we always jump to the character before the actual declaration/definition.
## Resolution
Vim's QuickFix lists require 1-based columns, which is what is returned from ycmd's commands, so don't subtract 1 from the column number.
As noted in the comments, the Vim documentation for `setqflist` is somewhat vague about this "byte offset", but it is confirmed to mean "1-based column number" both in testing and in `:help getqflist`.
Tested this with the Tern completer (`:YcmCompleter GoToReferences`) and Jedi completer (`:YcmCompleter GoToDeclaration`). For the Jedi completer, use something like: …
> [READY] Fix GoTo lists arriving at the wrong column.

- README.md
- doc/youcompleteme.txt
Support for the Rust programming language is added using ycmd's racerd completer. This PR contains documentation for using the Rust completer and an update to the ycmd submodule.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1888)
> Add support for the Rust programming language

- python/ycm/youcompleteme.py
Instead of printing the last 30 lines of the `stderr` logfile if the server crashed, we tell the user to run the `:YcmToggleLogs stderr` command to check the logs.
Remove `SERVER_CRASH_MESSAGE_SAME_STDERR` message because we are always using the `stderr` logfile since PR #1753. Also, console ouput cannot be used to see the logs.
Simplify `_NotifyUserIfServerCrashed` method by using `CheckFilename` function from `vimsupport` module.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1875)
> [READY] Update notifications when ycmd server crashed

- README.md
- doc/youcompleteme.txt
Following PR Valloric/ycmd#285, older versions of CMake (< 3.0) don't support the MSVC generator names with the year component but newer versions accept both formats. So, replace the generator names in README.md by the old ones.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1893)
> [READY] Update CMake generators for MSVC in README

- python/ycm/youcompleteme.py
[Lets try this again](https://github.com/Valloric/YouCompleteMe/pull/1897#issuecomment-170978003)
If the check for available completers isn't run because the server isn't
alive, or the check request erred or times out, don't cache the result. Only
cache valid returns.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1898)
> Don't cache invalid completer check results

- python/ycm/client/omni_completion_request.py
- python/ycm/tests/omni_completion_request_tests.py
OmniCompletionRequest is missing the RawResponse method, so any attempt to call
it calls the base class method instead. However, since the data structures of
this class and base class are different, this causes an error.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1916)
> Add missing implementation on OmniCompletionRequest

- appveyor.yml
This fixes the following error on AppVeyor:
```
You're using an outdated location for the get-pip.py script, please use the one available from https://bootstrap.pypa.io/get-pip.py
```
I also changed the way `get-pip.py` is downloaded. This is now done like in the `ycmd` repository.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1929)
> [READY] Update get-pip.py script URL on AppVeyor

- python/ycm/paths.py
- python/ycm/tests/paths_test.py
See discussion in issue #1891 for details.
Implement a new strategy to find the Python interpreter path:
- if specified, use `g:ycm_path_to_python_interpreter` option.
- on UNIX platforms, use `sys.executable` as the path to Python interpreter;
- on Windows, deduce it from `os.__file__` path (it should always be in the parent folder).
In all cases, check the version (2.6 or 2.7) of the Python interpreter path by running it.
This PR may break things. It needs thorough testing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1896)
> [READY] Implement new strategy to find the Python interpreter path

- python/ycm/test_utils.py
- python/ycm/tests/event_notification_test.py
While I was reviewing PR #1905, I found an issue with the `EventNotification` tests. It's easy to reproduce. You just need to comment [this line in `python/ycm/youcompleteme.py`](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/youcompleteme.py#L508) and run the tests. With this change, the `EventNotification` tests should fail since the second call of `ValidateParseRequest` re-raises the warning. However, tests are still passing because `assert_has_calls` does not check if a call was not made. For example, if `functionA` is called twice, both `assert_has_calls( [ functionA ] )` and `assert_has_calls( [ functionA, functionA ] )` are successful.
To fix this, we just need to check the number of calls using `call_count`. This is done by creating a subclass of `MagicMock` …
> [READY] Fix issue in EventNotification tests

- README.md
- doc/youcompleteme.txt
This sentence may be interpreted as executing the `make` command to move the libaries. See issue #1951. We *make* it clear by using `cmake` instead.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1954)
> [READY] Avoid confusion with make command

- README.md
- doc/youcompleteme.txt
This also updates to latest ycmd. Changes that affect the client:
- update racerd;
- add GoTo support for Go completer;
- add concurrent requests for Typescript completer;
- fix issue #1953;
- add GoToReferences support for Typescript completer.
I changed the filetypes lists to be in alphabetical order, except the C-family languages.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1965)
> [READY] Update Go documentation with GoTo subcommands

- README.md
- doc/youcompleteme.txt
This hasn't been true since [ycmd pull request #44](https://github.com/Valloric/ycmd/pull/44).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1988)
> Remove C# Diagnostic Support documentation note

- README.md
- doc/youcompleteme.txt
Found this while reading the documentation. There is no `ycmd` reference so it is displayed as `[ycmd][]`.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1990)
> [READY] Add links to ycmd repository in README

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Using GitHub's new issue and PR templates. Should in theory help cut down on issues that
- don't include enough info to even ascertain what the problem is,
- are user error,
- ask questions that are already answered in the docs, usually in several places.
The above types of issues are ~95% of all issues we get.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2003)
> [READY] Templates for new issues and PRs

- README.md
- doc/youcompleteme.txt
- python/ycm/client/command_request.py
- python/ycm/client/tests/command_request_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Previously, FixIts could only apply to the current buffer. Now we can apply FixIts across files, even if they are not currently open in the user's Vim. We obey existing configuration about how/where to open new files and apply changes in such a way as to not scribble the user's filesystem, and allow full undo history, like existing FixIt commands. Vim's python API actually makes this really quite easy.
To achieve this, we sort the chunks by filename, apply the existing logic unchanged. The only difference is that `ReplaceChunk` no longer implicitly assumes it applies to `vim.current.buffer`.
Previously, we used the subcommand name to determine the type of response to expect. This coupled the client and the server and didn't allow us to apply FixIts for a "Refactor" command, or "GoTo" for …
> [READY] Support FixIt and Refactor commands across multiple files

- autoload/youcompleteme.vim
- python/ycm/paths.py
- python/ycm/setup.py
This PR fixes issue #1726 by moving most of SetUpPython logic to its own module and using a try-catch-else block at the end of the function. It also prevents Python backtraces in Vim (which are really annoying) for common exceptions (`RuntimeError` and `ImportError`).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1994)
> [READY] Rewrite SetUpPython function

- README.md
- doc/youcompleteme.txt
Rename entries of `YcmCompleter subcommands` section in table of contents so that they correspond to their sections title. Add `Miscellaneous commands` missing entry.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2011)
> [READY] Fix entries in table of contents

- README.md
- doc/youcompleteme.txt
I use the `--all` flag for every build. I know this is probably a flag that's more useful for YCM contributors than most users, but it makes sense to document it.
It's only an update to the README, so I just tested it by eyeballing the output.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2027)
> [READY] Add --all option to README

- python/ycm/client/command_request.py
- python/ycm/client/completer_available_request.py
- python/ycm/client/completion_request.py
- python/ycm/client/event_notification.py
In PR #2016, we have changed the way we are catching exceptions on requests by only catching the `ServerError` instead of all exceptions, which is great for debugging purposes. However, due to this change, we don't catch the exception from a timed out request, leading to a ugly traceback in Vim. This PR fixes that.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2029)
> [READY] Catch ReadTimeout exception on requests

- python/ycm/youcompleteme.py
Even if `ycmd` process is terminated, YCM will try to send the `event_notification` request in `OnFileReadyToParse` function, blocking Vim for one second if the server crashed at the start (because of [this request](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/client/base_request.py#L222)) or resulting in a traceback with  `ConnectionError` exception otherwise. This will happen for the `InsertLeave`, `CursorMoved`, `CursorHold`, `BufferVisit` events, making Vim almost unusable.
This is fixed by returning early if the process is terminated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2041)
> [READY] Do not send request in OnFileReadyToParse function if server is down

- python/ycm/syntax_parse.py
- python/ycm/vimsupport.py
Fixes https://github.com/Valloric/YouCompleteMe/issues/2036
I'm submitting this without tests for now because it's probably quite important, and adding tests is going to be quite time consuming because we somehow need to mock out the output of `:syntax list` with unicode chars, etc.
I have tested manually and got people experiencing the issue to also confirm that it fixes it.
I've also surveyed other uses of `vim.eval` that return string and wrapped them in a `ToUnicode` where there is a possibility of it not working. This is much more speculative, so feel free to say …
> [READY] Fix traceback when syntax files contain unicode characters

- README.md
- doc/youcompleteme.txt
This PR updates the Windows documentation by mentioning both Python versions but recommending Python 3. It also changes the link to the 64-bit Vim by a link to [my own builds](https://bintray.com/micbou/generic/vim/view): they are updated more frequently, are available in both architectures, provide almost all Vim features, and are automatically tested before being released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2074)
> [READY] Update Windows installation in README

- README.md
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
- python/ycm/paths.py
- python/ycm/test_utils.py
As requested in https://github.com/Valloric/YouCompleteMe/issues/2052#issuecomment-195631106 I'm sending this PR. I've marked it as WIP because I've renamed only the `ycmd` option and that is because keeping the backward compatibility here was straight forward since is a client only option. For the jedihttp option instead I would like some opinion …
> [READY] Rename ycmd python option

- README.md
- doc/youcompleteme.txt
Since PR Valloric/ycmd#353, Clang version must be at least 3.8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2099)
> [READY] Update Clang version in documentation

- python/ycm/tests/postcomplete_tests.py
A refactoring of PostComplete tests made the `GetCompletionsUserMayHaveCompleted_ReturnEmptyIfPendingMatches_OldVim` test identical to 
`GetCompletionsUserMayHaveCompleted_ReturnEmptyIfPendingMatches_NewVim`. Revert to original test.
This PR also updates the tests with small changes. See the commit message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2097)
> [READY] Fix PostComplete test

- autoload/youcompleteme.vim
Since we don't really know why YCM is disabled when Vim is started in diff mode (the [relevant commit](https://github.com/Valloric/YouCompleteMe/commit/a6d5979b0847a8629861c8252d1e93c2b9a00297) is 4 years old) and I couldn't find any issues with YCM enabled in this mode, I propose to revert this commit.
See issue #2104 and [relevant thread on ycm-users list](https://groups.google.com/forum/?hl=en#!topic/ycm-users/cdqPJH5QrBs).
Fixes issue #2104.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2106)
> [READY] Do not disable YCM when Vim is started in diff mode

- plugin/youcompleteme.vim
- python/ycm/paths.py
- python/ycm/setup.py
- python/ycm/youcompleteme.py
See PR Valloric/ycmd#467.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2142)
> [READY] Add error messages when ycmd crashed

- python/ycm/base.py
- python/ycm/vimsupport.py
See the commit message and issue #2127.
Make Vim to use Python 3 for YCM by either using Vim with only Python 3 support or by editing the `s:UsingPython2` function in `autoload/youcompleteme.vim` to always return 0.
Create the following `vimrc`:
```
set nocompatible
set runtimepath+=~/.vim/bundle/YouCompleteMe
set encoding=utf8
filetype plugin indent on
let g:dummy_variable = '€'[0]
```
and start Vim with it. The following error will occur:
```
YouCompleteMe unavailable: 'utf-8' codec can't decode byte 0xe2 in position 0: unexpected end of data
```
with the traceback in `:messages`:
```python
File "<string>", line 24, in <module>
File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\setup.py", line 49, in SetUpYCM …
```
> [READY] Avoid evaluating Vim globals in Python

- python/ycm/tests/syntax_parse_test.py
- python/ycm/vimsupport.py
Fixes #2159.
I think the issue is caused by `locale.getpreferredencoding()` returning an empty string on some configurations (especially on OS X with Python 2). This is [the value used by default when no encoding is specified](https://docs.python.org/2/library/io.html?highlight=open#io.open). The same error is raised if we do:
```python
open( 'some_file', encoding = '' )
```
For references, similar issues: https://github.com/Valloric/ycmd/issues/395, https://github.com/Valloric/ycmd/issues/419
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2160)
> [READY] Fix LookupError exception when opening a file

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/client/command_request.py
- python/ycm/client/tests/command_request_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
From discussion in PR #2101, we reuse the `SetQuickFixList` function for the `GoTo*` subcommands. This automatically makes the quickfix window height equal to the number of locations.
Unfortunately, there is no Vim option to change the default height (10) of the quickfix window so we can't really use the heuristic `min(number of Locations, default height)` because users would not be able to change the default height (and we don't want to add another option). However, there are still solutions to set a default height. For instance, a user could add the following line in its vimrc:
```viml
autocmd FileType qf exe "20wincmd _"
```
to set the default height to 20. This will override YCM behavior.
I didn't reproduce the `lazyredraw` boilerplate from `youcompleteme#OpenGoToList`. I guess it was …
> [READY] Use SetQuickFixList function for GoTo* subcommands

- plugin/youcompleteme.vim
Vim recently has introduced a new feature called 'packages', which
permits, among the rest, to disable automatic loading a plugin at
startup. Plugins that are disabled at startup may be manually loaded
during a session using `:packadd` (see `:h packages`, `:h :packadd`).
Of course, a plugin that is loaded after startup cannot rely on VimEnter
events.
In order to support lazy loading YCM, check whether YCM is sourced
during startup or at a later time. In the former case, define an
autocommand as before; in the latter case, enable YCM immediately.
Why would one want to load YCM lazily? I use YCM only for certain file
types (Python), and I prefer not to have pop up menus appearing
all the time for other file types. In my …
> Support lazy loading with :packadd.

- README.md
- doc/youcompleteme.txt
- python/ycm/client/command_request.py
- python/ycm/client/tests/command_request_test.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
See PR https://github.com/Valloric/ycmd/pull/532
This PR presents the user with a list to choose from supplied FixIt suggestions when there are multiple suggestions on the same line. This not only helps with the child diagnostics mentioned in the ycmd PR, but also for cases where there are simply 2 diagnostics on the current line; the user can now select which of them to apply. Previously the one closest to the cursor was applied (which was always the first one supplied from the server).
I created a new `SelectFromList` method which uses `inputlist()` as the user interface …
> [READY] Support selecting from the list of FixIts when multiple are supplied

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
This PR updates the `ReplaceChunk` tests by using plain strings instead of byte objects to mimic Vim buffers returning byte objects on Python 2 and unicode objects on Python 3.
We are only updating the tests for now to show that these changes make the tests fail on Python 3 with the same error as issue #2240.
Fixes #2240.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2242)
> [READY] Fix Python 3 bytes issue in ReplaceChunk function

- python/ycm/client/shutdown_request.py
- python/ycm/test_utils.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/omni_completer_test.py
- python/ycm/tests/postcomplete_tests.py
- python/ycm/tests/server_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
This PR depends on https://github.com/Valloric/ycmd/pull/282.
We don't want to block Vim exit if the server takes too much time to answer the shutdown request so we use a timeout of 100ms for this request. In my experience, it takes ~5ms.
The `YcmStopServer` command only exists for testing purpose. It will be removed in the final version of this PR.
Fixes #876.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2245)
> [READY] Implement shutdown handler

- python/ycm/tests/syntax_parse_test.py
While trying to fix a bug when extracting identifiers from Vim syntax files, I found out that errors from syntax tests are not really helpful because `eq_` assertions don't tell which items are missing when comparing lists (or sets). So, we use matchers from hamcrest instead to get useful assertion errors.
Note that with these changes, we don't test anymore if the value returned by `_KeywordsFromSyntaxListOutput` is a set. I don't think it's an issue but if you feel that's important, we can probably check for it too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2273)
> [READY] Rewrite syntax tests

- python/ycm/syntax_parse.py
- python/ycm/tests/syntax_parse_test.py
This PR is an attempt at improving the extraction of keywords from Vim syntax files. Current approach is to go through the `syntax list` output and:
- ignore lines where the first word is a reserved keyword for syntax highlighting except for `contained`;
- ignore all words used by Vim as arguments in the syntax commands;
- add remaining words to the list of identifiers.
The main issue with this approach is that syntax arguments that could be valid language keywords are always ignored. There is also a bug where the `match` keyword is extracted while not being a language keyword (see the Python, C++, and Java tests).
With the new approach, we try to ignore Vim keywords only when necessary, that is:
- ignore `syntax match` (fix the `match` keyword bug) and `syntax region` commands: they …
> [READY] Improve extraction of keywords from syntax list

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
When highlighting a range of characters for a diagnostic, we make sure that the start and end positions do not go paste the line contents or the range will not be highlighted at all (don't ask, this is a Vim feature). However, we don't account for the end position not being included in the diagnostic range. So, when this position ends at line ending or after it, we move it just before the `EOL` character. Since the end position is not part of the range, this character will not be highlighted, which is not what we want. We fix this behavior by decrementing the end column before clamping it and incrementing it after.
Fixes https://github.com/Valloric/YouCompleteMe/issues/846.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [READY] Fix diagnostic highlighting at line ending

- python/ycm/client/base_request.py
- python/ycm/client/command_request.py
- python/ycm/client/completion_request.py
- python/ycm/client/tests/command_request_test.py
- python/ycm/diagnostic_interface.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
Being interrupted by the `Press ENTER or type command to continue` prompt while writing code is annoying. This happens when an error occurs during completion and the error message displayed on the status line is longer than the window width. We prevent that by truncating the message.
Note that the message logged to the command-line history will also be truncated.
4 functions to display messages on the status line (`PostVimMessage`, `PostMultiLineNotice`, `EchoText`, and `EchoTextVimWidth`) is a little too much. Merge them into one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2302)
> [READY] Avoid hit-enter prompts during completions

- README.md
- doc/youcompleteme.txt
Newer version of clang and llvm is required now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2319)
> Update instructions for FreeBSD

- README.md
- doc/youcompleteme.txt
- python/ycm/youcompleteme.py
Use the `UltiSnips#SnippetsInCurrentScope` public function instead of the `UltiSnips_Manager` internal object to fetch snippets. Fixes #2320.
Give a workaround in the FAQ for snippets not suggested as candidates if added with the `:UltiSnipsAddFiletypes` command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2321)
> [READY] Do not depend on UltiSnips internals to fetch snippets

- autoload/youcompleteme.vim
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
When evaluating a Vim expression in Python that involves code expecting user input (e.g. `input()`, `inputlist()`, `complete_check()`, etc.), if this evaluation is interrupted by the user (with `CTRL-C` for instance), Vim will pass the interruption to the Python interpreter which in turn will raise a `KeyboardInterrupt` exception. We don't want these exceptions to be displayed to the user (because the way Vim handles Python exceptions is really annoying) so we catch them where appropriate.
Fixes #2289.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2329)
> [READY] Handle keyboard interruption when evaluating Vim expression with user input

- README.md
- doc/youcompleteme.txt
We mention all supported languages except C-family languages and JavaScript in the `Semantic Completion for Other Languages` section of the documentation. Add them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2344)
> [READY] Mention all natively supported languages in documentation

- README.md
- doc/youcompleteme.txt
With PR https://github.com/Valloric/ycmd/pull/506, we removed the `StartServer` subcommand in favor of the `RestartServer` one and we hid the `StopServer` subcommand from the user. Update the documentation to reflect this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2346)
> [READY] Update miscellaneous commands in documentation

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
Long and personal experience, when TextChangedI gets used, YCM seems
to perform better, diagnostics will trigger much less frequently at
inappropriate occasions, even less with whitespace agnostic triggers,
if I recall correctly...
There's a previous discussion at #1337. At the time this change was bundled in
a single pull request with other changes.
It has gone through the test of the time, sole issue I've stumbled upon was reported
by @puremourning at https://github.com/oblitum/YouCompleteMe/issues/10. This
is what me and other users of my fork use daily.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1901)
> [READY] Bumps required Vim to 7.4.143 and adopts TextChangedI.

- .travis.yml
- README.md
- ci/travis/travis_install.linux.sh
- doc/youcompleteme.txt
Updates ycmd submodule to latest (see below), and updates the subcommand documentation to cover `GetDocImprecise` and the new `GetTypeImprecise`.
Other user-visible changes being included (Release notes):
- PR 590: Enable KeepGoing option when creating translation units in Clang completer
- PR 595: Fix default include paths for macOS Sierra
- PR 596: Fix javascript subcommand errors for relative paths.
- Fix for #607
- PR 609: Support GetTypeQuick completer subcommand in clang completer
- PR 615: Rename GetDocQuick subcommand to GetDocImprecise
Text in the subcommand …
> [READY] Update ycmd. Update docs for GetTypeImprecise and GetDocImprecise

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- [ x ] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [ x ] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [ x ] I have included tests for the changes in my PR. If not, I have included a
Rationale: Tests are in https://github.com/Valloric/ycmd/pull/617.  This does not change any behavior in YCM itself, only makes things go faster.
- [ x ] **I understand my PR may be closed if it becomes obvious I didn't
GetUnsavedAndCurrentBufferData() is invoked on every kepress.  On a large file (15+k loc), using this new function takes kepress …
> Use JoinLinesAsUnicode in GetUnsavedAndCurrentBufferData().

- autoload/youcompleteme.vim
- python/ycm/client/base_request.py
- python/ycm/client/event_notification.py
- python/ycm/test_utils.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
When deleting a buffer, we use the current buffer to send the `BufferUnload` event notification request to ycmd instead of the buffer being deleted. This is an issue when the current buffer is not of the same filetype as the deleted one. In this case, three different scenarios may occur:
- the current buffer filetype is not allowed: no request is sent to the ycmd server. The `OnBufferUnload` method from the completer corresponding to the filetype of the deleted buffer is not called. If the filetype is a C-family language, the translation unit is not destroyed. If it is TypeScript, we don't tell TSServer to close the file (not really an issue unless the file is modified elsewhere);
- the current buffer filetype has no semantic support in ycmd: the request is sent to the ycmd server but no …
> [READY] Use deleted buffer instead of current buffer when sending BufferUnload event notification

- .coveragerc
- .gitignore
- .travis.yml
- README.md
- appveyor.yml
- codecov.yml
- doc/youcompleteme.txt
- python/test_requirements.txt
- run_tests.py
There should not have anything to configure on codecov website.
I updated the `run_tests` script to behave exactly like the one in ycmd repository: when passing tests as arguments, you need to specify the path from the root project, not the `python` folder. For instance:
```
./run_tests.py --skip-build -- python/ycm/tests/event_notification_test.py
```
instead of
```
./run_tests.py --skip-build -- ycm/tests/event_notification_test.py
```
This way, you can now complete the path to the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2385)
> [READY] Add coverage support

- python/ycm/client/tests/command_request_test.py
- python/ycm/client/tests/completion_request_test.py
- python/ycm/tests/__init__.py
- python/ycm/tests/base_test.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/omni_completer_test.py
- python/ycm/tests/paths_test.py
- python/ycm/tests/postcomplete_test.py
- python/ycm/tests/syntax_parse_test.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/tests/youcompleteme_test.py
We don't want `test_utils.py` to appear in the coverage reports. Instead of blacklisting it in `.coveragerc`, we move it to the tests folder.
This will decrease coverage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2389)
> [READY] Move test_utils.py file to tests folder

- install.py
See PR https://github.com/Valloric/ycmd/pull/630.
Closes https://github.com/Valloric/YouCompleteMe/pull/2351.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2405)
> [READY] Catch CalledProcessError exception in install script

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Auto-inserting namespace imports in C# is broken because the `ReplaceChunk()` call is missing an argument
ReplaceChunk must have changed to require the buffer at some point
No test is included because it's a one-line change; the method is theoretically covered, so I'm not sure why the missing argument error was not caught (not familiar with these tests). Happy to add one if needed (and I can get pointed in the right …
> Fix InsertNamespace

- autoload/youcompleteme.vim
See pull request: [#2072](https://github.com/Valloric/YouCompleteMe/pull/2072)
Unfortunately I was not able to reproduce the original author's results. I tried using a clean .vim and .vimrc. The only plugins I used were YCM and ctrlfs.vim, just as the original author mentioned. The .vimrc looks like this:
```VimL
syntax on
set history=500
set nocp
filetype plugin indent on
set encoding=GBK
```
Whatever I tried to do with configuration, I couldn't get a start without an error, but it is already known that …
> Don't set omnifunc when not allowed

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
* Additionally set the preview buffer to be unlisted so it does not interfere with commands like :bnext
* See [my comment](https://github.com/Valloric/YouCompleteMe/issues/1366#issuecomment-259878581) for more details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2436)
> Address #1366 by reusing a single preview buffer

- python/ycm/youcompleteme.py
This fixes a new error detected by the last version of `pycodestyle` (2.2.0), which is a dependency of `flake8`:
```
C:\projects\youcompleteme\python\ycm\youcompleteme.py:69:1: E305 expected 2 blank lines after class or function definition, found 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2441)
> [READY] Fix flake8 error

- README.md
- doc/youcompleteme.txt
Since PR https://github.com/Valloric/ycmd/pull/590, Clang 3.9 is required because of the `KeepGoing` option. In fact, it is still possible to successfully compile against a 3.8 system libclang or with the `-DEXTERNAL_LIBCLANG_PATH` flag pointing to a 3.8 libclang since [the headers included in ycmd](https://github.com/Valloric/ycmd/tree/master/cpp/llvm/include/clang-c) are used in these two cases. However, the `KeepGoing` option will have no effect. So, we still recommend Clang 3.9 in all cases.
Closes https://github.com/Valloric/ycmd/issues/654.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2445)
> [READY] Bump Clang version in documentation

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
- python/ycm/tests/__init__.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
We have a lot of issue reports with Python exceptions that interrupt user workflow or even worse make the editor unusable and force users to restart it (e.g. issue https://github.com/Valloric/YouCompleteMe/issues/2192). We really want to avoid that but at the same time we can't just silence these exceptions because they are useful to debug the issue. Logging them to Vim `:messages` is not practical because we can't write to it without displaying messages in the status line which, in addition to distract users, may lead to various issues like the infamous `Press ENTER or type command to continue` message. This is why a logfile is needed.
For now, only server crashes are logged but more logging will be added: connection issues with the server (`ConnectTimeout`, `ReadTimeout`, etc. …
> [READY] Add client logfile

- plugin/youcompleteme.vim
The `ycm_register_as_syntastic_checker` option was introduced a long time ago in commit https://github.com/Valloric/YouCompleteMe/commit/16b6f877c62510840e4547e11f4b31a89e68f491 and became obsolete when [Syntastic support was replaced](https://github.com/Valloric/YouCompleteMe/commit/6c01881e1a615b1b87fc5ef20855d11f9fde32a7). Since then, it doesn't serve any purpose except being an alias to the `ycm_show_diagnostics_ui` option which can be an issue (see #2455) so we remove it.
Fixes #2455.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2456)
> [READY] Remove outdated Syntastic option

- autoload/youcompleteme.vim
This autocommand has a bug that makes the cursor goes to the first line of the current buffer when opening the preview window with `:pedit`. Since the `BufRead` autocommand is always called after, we can drop it by moving the `s:OnBufferReadPre` logic into the `s:OnBufferRead` function.
Fixes #2466.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2469)
> [READY] Do not use BufReadPre autocommand

- python/ycm/client/completion_request.py
- python/ycm/client/event_notification.py
An `AttributeError` exception is raised when `Done` is called before `Start` in the `CompletionRequest` and `EventNotification` classes because the `_response_future` attribute is not yet defined.
Fixes #2461.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2465)
> [READY] Fix exception when response future is not set

- autoload/youcompleteme.vim
In PR #2469, we moved the large file logic inside `s:OnBufferRead` but forgot this function was not only called on the `BufRead` event but also on the `FileType` one. This makes the large file message appears twice when opening such file. We fix that by not displaying the message when the `b:ycm_largefile` variable is already set.
Also, the message is now displayed with `PostVimMessage` to avoid the `Press ENTER or type command to continue` prompt.
Fixes #2485.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2487)
> [READY] Fix large file message appearing twice

- python/ycm/client/base_request.py
Since PR #2453, we don't catch anymore exceptions raised from loading or ignoring a `.ycm_extra_conf.py` file. For instance, loading this extra conf:
```python
raise Exception
```
will result in a Python traceback inside Vim. This is fixed by catching the `UnknownExtraConf` exception in its own block (as [it was before](https://github.com/Valloric/YouCompleteMe/blob/48b7ccef76c9f15b8fc0227b5e661eb55e483459/python/ycm/client/event_notification.py#L64-L73)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2488)
> [READY] Handle server exceptions from loading/ignoring extra conf

- .github/ISSUE_TEMPLATE.md
> project administration-only change
The issue template has worked very well and a larger number of reported issues include useful diagnostics. However, this is still far from ubiquitous.
I've noticed two recurring problems, that I've tried to solve with an update to the template:
- when reporting a build failure, not including the _entire_ `install.py` log or the command used to run it
- when reporting issues, stating that something doesn't work, but not stating what the expected behaviour was (this is a common human mistake).
Meanwhile, I've encouraged the reporter to …
> [READY] Improve issue template - guide the user in completing it

- README.md
- doc/youcompleteme.txt
> only changes docs
This change:
- updates the c-family completer documentation to describe the built in support for compilation databases added in https://github.com/Valloric/ycmd/pull/680
- explains more about why ycmd needs compiler flags, and how to go about providing them
- recommends using a compilation database (as that seems to be the fashion)
- standardises formatting for `NOTE` (it was inconsistent before)
- states that the preferred installation method is `install.py` (rather than the full installation instructions)
- update the vim doc
- update the ycmd …
> [READY] Update readme for compilation database support

- python/ycm/paths.py
rationale for why I haven't:
- This seems quite difficult to test in a cross-platform, cross-version fashion, but
- I might have missed something, I am not a python expert. :)
Sitecustomize files can be slow or broken and might hang editor
startup.  Since they aren't necessary for checking the python version,
disable them to get a small speed boost for everyone, and an editor
that doesn't hang indefinitely on startup if the sitecustomize gets
into an infinite loop (due to a bad NFS mount or similar).
[cont]: …
> Disable sitecustomize when checking python version

- python/ycm/client/debug_info_request.py
- python/ycm/tests/client/debug_info_request_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
Thanks to PR #2342, we can easily update the `:YcmToggleLogs` command to also list the subservers logfiles and open them directly in Vim. For instance, when editing a Python file:
```
:YcmToggleLogs
Available logfiles are:
jedihttp_55438_stderr_g9rk18nc.log
jedihttp_55438_stdout_duc8kfqm.log
ycm_ttssiu.log
ycmd_55432_stderr_b9lnwf.log
ycmd_55432_stdout_jyakxs.log
```
Then
```
:YcmToggleLogs jedihttp_55438_stderr_g9rk18nc.log
```
to open the JediHTTP stderr logfile in Vim.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2506)
> [READY] Include subservers logfiles in YcmToggleLogs command

- autoload/youcompleteme.vim
- python/ycm/client/base_request.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
Currently, we always check that the ycmd process is up (with the `IsServerAlive` method) before sending a request. Without this check, each request could block Vim until a `NewConnectionError` exception is raised if the server crashed. This is the case on Windows where it takes ~1s before the exception is raised which makes Vim unusable. However, even with this check, Vim may still be blocked in the following cases:
- the server crashes just after the check but before sending the request;
- the server is up but unresponsive (e.g. its port is closed).
To avoid both cases, we instead use [the connect timeout parameter from Requests](http://docs.python-requests.org/en/master/user/advanced/?highlight=connect%20timeout#timeouts) and set it to a duration sufficiently short (10 ms) that the …
> [READY] Rely on connect timeout instead of checking that the server is alive

- python/ycm/client/base_request.py
On non-Windows platforms (tested on Linux and OS X), a `ConnectionError` exception is raised instead of a `ConnectTimeout` one when the connection cannot be established (e.g. the server crashed). Since [the latter is a subclass of the former](http://docs.python-requests.org/en/master/_modules/requests/exceptions/#ConnectTimeout), we only need to catch `ConnectionError`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2516)
> [READY] Catch ConnectionError instead of ConnectTimeout

- README.md
- plugin/youcompleteme.vim
This is another attempt at:
https://github.com/Valloric/YouCompleteMe/pull/2473
Which removed the apparently flawed attempt at "lazy" loading of YCM. While it fails to get the load out of the critical startup path, it *does* serve the useful purpose when starting up gvim of avoiding a deadlock situation in gvim.
So, this time, we keep VimEnter, but only for the gui-starting case. We update the comment to explain what is actually happening. And we can keep the docs about how to defer loading.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> Don't use VimEnter initialization except when stating gui

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/client/command_request.py
- python/ycm/tests/client/command_request_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
This PR moves the logic of the `YcmDiags` and `YcmForceCompileAndDiagnostics` commands to the Python layer. It replaces the `echo` calls by `PostVimMessage` ones to display message on the status line and it always prints `Diagnostics refreshed` once compilation is done. This has the benefit of clearing the message `Forcing compilation, this will block Vim until done.` and avoiding the `Press Enter or type command to continue` prompt.
This also adds the `YcmLocationOpened` autocommand which is the same as `YcmQuickFixOpened` but for the location list window.
Fixes #2543.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2548)
> [READY] Refactor diagnostic commands

- plugin/youcompleteme.vim
`has('gui')` returns `1` even in console Vim if it is compiled with `+gui`. We should use `gui_running` instead. See https://github.com/Valloric/YouCompleteMe/commit/1d1a4f4cff04ed32ab924dda20666e67eabdefb4#commitcomment-20876179.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2554)
> [READY] Use gui_running instead of gui to defer YCM loading at VimEnter

- plugin/youcompleteme.vim
YCM should start the same whether Vim is running in GUI or not. Otherwise, this makes it difficult for other plugins to interact with YCM at startup because they can't predict how YCM will start unless they also check if Vim is running in GUI which is unreasonable. Since we can't load it at Vim startup because of [a deadlock issue](https://github.com/Valloric/YouCompleteMe/pull/2473#issuecomment-267716136), we should always defer it at the VimEnter event.
See discussion in https://github.com/Valloric/YouCompleteMe/commit/39659caf34c664c7419cadb41cb813158e0749fa for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2561)
> [READY] Always defer loading at VimEnter

- autoload/youcompleteme.vim
When both versions are available, we should use Python 3 over Python 2 for the following reasons:
- faster startup:
<table>
<tr>
<th rowspan="2">Platform</th>
<th colspan="2">First run (ms)</th>
<th colspan="2">Subsequent runs (ms)</th>
</tr>
<tr>
<td>Python 2</td>
<td>Python 3</td>
<td>Python 2</td>
<td>Python 3</td>
</tr>
<tr>    
<td>Ubuntu 16.04 64-bit</td>
<td>197</td>
<td>110</td>
<td>117</td>
<td>84</td>
</tr>
<tr>
<td>macOS 10.12</td>
<td>322</td>
<td>186</td>
<td>210</td>
<td>124</td>
</tr>
<tr> 
<td>Windows 10 64-bit</td>
<td>601</td>
<td>295</td>
<td>251</td>
<td>144</td>
</tr>  
</table>
*Results obtained by running the `prof.py` script from [this branch](https://github.com/micbou/YouCompleteMe/tree/profiling-startup). The difference between first run and subsequent runs is …
> [READY] Prefer Python 3 over Python 2

- python/ycm/youcompleteme.py
On Python 3, reading stderr from server returns bytes. We need to convert it to unicode for `splitlines()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2569)
> [READY] Convert stderr from server to unicode

- python/ycm/client/base_request.py
See https://github.com/Valloric/ycmd/pull/724. This also fixes a regression in startup time on Python 3 because importing `futures.moves` was calling [the `import_top_level_modules` function](https://github.com/PythonCharmers/python-future/blob/master/src/future/moves/__init__.py#L7-L8) which is slow.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2577.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2578)
> [READY] Import urljoin and urlparse from ycmd.utils

- README.md
- python/ycm/youcompleteme.py
This just makes use of [these changes](https://github.com/Valloric/ycmd/pull/718) to ycmd.
It adds TypeScript to the list of filetypes that diagnostics are supported for and reflects that in the README. (And updates ycmd.)
No tests are included, since the only code that changed is the hard-coded list of filetypes. The new ycmd functionality is tested in that project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2584)
> Typescript diagnostics

- python/ycm/paths.py
- python/ycm/tests/paths_test.py
Even with the `-S` option (see PR https://github.com/Valloric/YouCompleteMe/pull/2502), starting the Python interpreter to check its version can be slow. For instance, on my machine (in PowerShell):
```ps
> Measure-Command -Expression {python -S -c "pass"}
...
TotalMilliseconds : 25,4387
```
It's also not particularly useful because, in the typical case, the Python used to start ycmd will be the one from `PYTHON_USED_DURING_BUILDING` which is necessarily a supported version. In the cases where the `g:ycm_server_python_interpreter` option is specified or a Python is found in the PATH, it's up to the user to provide a supported version. If they don't, the ycmd server will probably fail to start and the following error will be displayed to them:
```
The ycmd server SHUT DOWN (restart with …
```
> [READY] Remove Python version check

- python/ycm/paths.py
- python/ycm/tests/paths_test.py
I was looking at `PathToPythonInterpreter` coverage and was surprised to see [that line](
https://github.com/Valloric/YouCompleteMe/blob/01570aac03f609d30d7c94871161c1e2128ce9e7/python/ycm/paths.py#L84) covered. This shouldn't be the case since we are supposed to use the Python from `PYTHON_USED_DURING_BUILDING`. This happens because the Python executable used in our Travis builds on macOS is named `Python` (with a capital letter) and so we don't accept it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2590)
> [READY] Accept capitalized name for Python executable

- python/ycm/diagnostic_interface.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
When multiple diagnostics are on the same line, warnings may have higher priority than errors. See #2141 for an example. This happens for several reasons:
- we sort diagnostics by column and then by kind. We should do the opposite;
- we place all signs; each sign overriding the previous one. Since only one sign is visible by line, we should just insert the first one (which has the highest priority);
- we draw highlighting matches (squiggles) in the same order as diagnostics; each match being drawn over the previous ones. We should draw them in reverse order (from lowest to highest priority).
Fixes #2141.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2592)
> [READY] Prioritize errors over warnings on the same line

- README.md
- doc/youcompleteme.txt
YCM requires Vim 7.4.147 or later while this FAQ entry mentions 7.4.72.
Update Vim documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2593)
> [READY] Remove outdated FAQ entry

- python/ycm/client/command_request.py
- python/ycm/client/debug_info_request.py
- python/ycm/tests/command_test.py
- python/ycm/tests/testdata/.ycm_extra_conf.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
Send extra_conf_vim_data in requests from :YcmCompleter and :YcmDebugInfo commands. It's needed for passing compile_commands.json directory to every call of FlagsForFile in client_data argument.
- [ x] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [ x] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [ x] I have included tests for the changes in my PR. If not, I have included a
- [x ] **I understand my PR may be closed if it becomes obvious I didn't
Directory of compile_commands.json may be different for different configurations. And …
> Send extra_conf_vim_data in requests from :YcmCompleter and :YcmDebugInfo commands

- README.md
- doc/youcompleteme.txt
Two links are not properly displayed because of wrong markdown syntax. Also, the link for the Python 2.7.11 workaround doesn't point to the right section of [`appveyor.bat`](https://github.com/vim/vim-win32-installer/blob/master/appveyor.bat) because the file changed since then. Use a specific commit instead of master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2597)
> [READY] Fix links in documentation

- python/ycm/paths.py
Once YCM is installed through a plugin manager in Vim (e.g. using the `:PluginInstall` command with Vundle), it picks a Python interpreter (most likely the one used to run YCM inside Vim), caches it, and starts the server with it. This fails since the `ycm_core` library is not yet compiled and the following message is displayed on the status line:
```
The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). YCM core library not detected; you need to compile YCM before using it. Follow the instructions in the documentation.
```
After reading the documentation, the user may then build the library directly from Vim:
```
:!/path/to/YCM/install.py
```
or by opening a new terminal and calling the `install.py` script without leaving Vim. Once the compilation is done, he will restart the …
> [READY] Do not cache Python interpreter path

- python/ycm/diagnostic_interface.py
- python/ycm/tests/youcompleteme_test.py
ycmd may return a location extent with a starting column of zero (see the test for an example) which is not a valid column (columns are 1-indexed). We should use the location in this case. Also, when the location extent is not valid, we should call `AddDiagnosticSyntaxMatch` with the `is_error` parameter to highlight warnings as such and not as errors (`is_error` is `True` by default).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2602)
> [READY] Fix diagnostic highlighting with invalid location extent

- CONTRIBUTING.md
[`git-new-workdir` is deprecated in favor of `git-worktree`](http://nuclearsquid.com/writings/git-new-workdir/).
@homu shouldn't be triggered to merge this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2606)
> [READY] Replace git-new-workdir by git-worktree

- requirements.txt
- update_from_readme.py
This makes the `update_from_readme.py` script compatible with Python 3.
`six` is a dependency of `html5lib` and `wsgiref` is available since Python 2.5 so we can remove them from `requirements.txt`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2608)
> [READY] Add Python 3 support to update_from_readme script

- README.md
- doc/youcompleteme.txt
Forgot to update the list of supported CMake generators on Windows in PR #2572.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2609)
> [READY] Update Visual Studio generators in documentation

- README.md
- doc/youcompleteme.txt
I am not aware of a Vim option to not switch to the location list (or quickfix) window when calling `lopen` (respectively `copen`) so I think it's a good idea to give an example in the docs on how to achieve this using the `YcmLocationOpened` and `YcmQuickFixOpened` autocommands.
Also, the `execute` calls are not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2635)
> [READY] Update autocommands examples in documentation

- .travis.yml
Our homu instance gets travis events through GitHub status events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2643)
> [READY] Removing unnecessary travis webhook

- autoload/youcompleteme.vim
When opening a file, Vim triggers the `BufRead` event then the `BufEnter` one. By setting the `s:previous_allowed_buffer_number` variable in `s:AllowedToCompleteInBuffer`, we avoid a reparse on `BufEnter` after parsing the buffer on `BufRead`. This reduces the number of `BufferVisit` and `FileReadyToParse` requests sent to the server by one when opening a file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2644)
> [READY] Improve reparse requirement on BufEnter event

- README.md
- doc/youcompleteme.txt
- python/ycm/youcompleteme.py
This issue has already been reported twice (https://github.com/Valloric/YouCompleteMe/issues/2403 and https://github.com/Valloric/YouCompleteMe/issues/2611) and is not something that we can fix on our side so we should mention it in the FAQ.
Closes https://github.com/Valloric/YouCompleteMe/issues/2611.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2639)
> [READY] Add FAQ entry about YCM not shutting down when quitting Vim

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
- python/ycm/tests/__init__.py
- python/ycm/tests/event_notification_test.py
- python/ycm/youcompleteme.py
Currently, we wait for an autocommand to trigger to display diagnostics. This is not ideal as users have to do some actions like moving the cursor or editing the buffer to see them. We can improve that by using [the timers feature introduced in Vim 7.4.1578](https://github.com/vim/vim/commit/975b5271eed4fa0500c24a8f37be0b1797cb9db7) to display diagnostics asynchronously. Here's a demo:
By displaying diagnostics asynchronously, we can drop the `CursorHold` and `CursorHoldI` autocommands as well as [the `g:ycm_allow_changing_updatetime` option](https://github.com/Valloric/YouCompleteMe/blob/5a806dcb301beeeac4df9bb84a4f7e4069d40c43/README.md#the-gycm_allow_changing_updatetime-option). In addition, we can now parse the current buffer and display diagnostics on the `TextChanged` event instead …
> [READY] Display diagnostics and parse initial buffer asynchronously using timers

- plugin/youcompleteme.vim
Forgot to remove the `g:ycm_allow_changing_updatetime` option from `plugin/youcompleteme.vim` in PR #2636.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2656)
> [READY] Completely remove g:ycm_allow_changing_updatetime option

- python/ycm/tests/postcomplete_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
Now that we require at least Vim 7.4.1578, we can remove the code that automatically insert namespaces in C# for Vim versions prior to 7.4.774.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2650)
> [READY] Clean C# inserting namespace code

- python/test_requirements.txt
See PR https://github.com/Valloric/ycmd/pull/770.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2672)
> [READY] Require coverage.py package older than version 4.4 

- autoload/youcompleteme.vim
- python/ycm/buffer.py
- python/ycm/diagnostic_interface.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
Adds an emulation of Vim buffer object and moves change tracking into python.
Now diagnostics are stored per buffer, which effectively solves #2165 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2631)
> [READY] Moved change tracking to python. Per buffer diagnostics

- .travis.yml
- README.md
- ci/travis/travis_install.linux.sh
- doc/youcompleteme.txt
This include the following changes:
- PR Valloric/ycmd#710: allow compilation for iOS projects;
- PR Valloric/ycmd#728: handle unicode pathname when loading source on Python 2;
- PR Valloric/ycmd#735: update JediHTTP;
- PR Valloric/ycmd#741: update Boost to 1.64.0;
- PR Valloric/ycmd#744: create a symlink instead of renaming libclang;
- PR Valloric/ycmd#745: ignore identifiers from comments and strings on certain events;
- PR Valloric/ycmd#746: ignore identifiers from comments and strings by filetype;
- PR Valloric/ycmd#749: improve CSS identifier regex;
- PR Valloric/ycmd#753: fix Godef build error;
- PR Valloric/ycmd#754: search Python library in lib64 folder in addition to lib;
- PR Valloric/ycmd#767: specify .NET Framework 4.5.
This also updates the C# instructions in the full …
> [READY] Update ycmd

- python/ycm/base.py
- python/ycm/tests/base_test.py
- python/ycm/vimsupport.py
`CurrentIdentifierFinished` and `LastEnteredCharIsIdentifierChar` incorrectly use byte offsets with unicode lines (`CurrentColumn` returns a byte offset and `CurrentLineContents` a unicode string). This leads to weird bugs when there is a non-ASCII character on the current line:
This is fixed by converting byte offsets to codepoint ones through the `ByteOffsetToCodepointOffset` function.
This changes the behavior of these two functions when the current column position is invalid. Both functions returned false in that case. They now return as if the current column were at the end of the line. In practice, this doesn't really matter since the position of the current column should always be valid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [READY] Use codepoint offsets in identifier functions

- README.md
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
YCM expects the character encoding used by Vim to be UTF-8. If another encoding is used, inserting a non-ASCII character raises a `UnicodeDecodeError` exception resulting in a Python traceback inside Vim. However, supporting other encodings would make the code more complex for no good reason. A file in a different encoding than UTF-8 can be edited in Vim without any issue when the `encoding` option is set to `utf-8`. For instance, editing a file encoded in `latin-1` is as simple as:
```viml
:e ++enc=latin1
```
There is no need to change the `encoding` option for that.
We don't force `encoding` to be `utf-8` because changing this option is not safe after Vim start. From [the `encoding` documentation](http://vimdoc.sourceforge.net/htmldoc/options.html#'encoding'):
```
NOTE: Changing this …
```
> [READY] Require UTF-8 encoding

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
- python/ycm/base.py
- python/ycm/client/completion_request.py
- python/ycm/client/omni_completion_request.py
- python/ycm/omni_completer.py
- python/ycm/tests/client/omni_completion_request_tests.py
- python/ycm/tests/completion_test.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/test_utils.py
- python/ycm/youcompleteme.py
There is a number of issues with the current completion system:
- UI is blocked until the completions are returned by the server, the request timed out, or a key is pressed by the user. This leads to a rough experience when completions take too much time: cursor disappearing and timeout errors (see https://github.com/Valloric/YouCompleteMe/issues/2192 and https://github.com/Valloric/YouCompleteMe/issues/2574). Users even [increase the timeout by manually editing the `completion_request.py` file](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/client/completion_request.py#L30) to avoid these errors, which exacerbate the issue and, in some cases, make the plugin unusable (see https://github.com/Valloric/YouCompleteMe/issues/2574).
- no fuzzy matching from omnifunc when …
> [READY] Rewrite completion system

- README.md
- doc/youcompleteme.txt
With Valloric/YouCompleteMe#2636 we bumped minimum required vim version to 7.4.1578, but in one place we didn't change the value.
Yes, this PR is just one number change, but inconsitency bothers me.
--- …
> Correct vim 7.4 patch requirement

- python/ycm/omni_completer.py
- python/ycm/tests/omni_completer_test.py
A number of issues have been raised over the years where YCM doesn't interact great with the user's omnifunc. This is commonly because we ignore the omnifunc's `findstart` response, and use our own implementation (`base.CompletionStartColumn`).
In combination with valloric/ycmd#681 this change uses the omnifunc's start column for completions and fixes valloric/ycmd#671 and others, such as:
- https://github.com/Valloric/YouCompleteMe/issues/1322 probably (not yet tested)
- https://github.com/Valloric/YouCompleteMe/issues/1957
- …
> [READY] Reset the start column in omnifunc completer

- autoload/youcompleteme.vim
- python/ycm/youcompleteme.py
There is no need to continue polling the server if its process has terminated (i.e. the server crashed). This fixes issue https://github.com/Valloric/YouCompleteMe/issues/2683 when the server is not working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2704)
> [READY] Stop polling for readiness if the server crashed

- python/ycm/tests/__init__.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
On Python 2, jumping in a file whose path contains non-ASCII characters raises the following warnings:
```
Error detected while processing function <SNR>26_CompleterCommand:
line   18:
python\ycm\vimsupport.py:400: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
if filename != GetCurrentBufferFilepath():
python\ycm\vimsupport.py:375: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
if win.buffer.name == filepath:
```
This happens because, in the `JumpToLocation` function, we are comparing a unicode object (`filename` and `filepath`) with a Vim buffer name (`vim.current.buffer.name` returned by `GetCurrentBufferFilepath` and `win.buffer.name` …
> [READY] Fix unicode warning when jumping on Python 2

- python/ycm/tests/event_notification_test.py
- python/ycm/tests/omni_completer_test.py
- python/ycm/tests/test_utils.py
Change the `VimBuffer` object to accept a Python function as its omnifunc, e.g.
```python
def Omnifunc( findstart, base ):
if findstart:
return 5
return [ 'a', 'b', 'c' ]
```
and rewrite the omnifunc tests accordingly. This reduces the amount of mocking done directly in these tests.
Also, extend the `ToBytesOnPY2` function to lists and dictionaries so that, instead of having to write
```python
[ ToBytesOnPY2( 'a' ), ToBytesOnPY2( 'b' ), ToBytesOnPY2( 'c' ) ]
```
in tests, one can write:
```python
ToBytesOnPY2( [ 'a', 'b', 'c' ] )
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2701)
> [READY] Rewrite omnifunc tests

- python/ycm/omni_completer.py
- python/ycm/tests/omni_completer_test.py
- python/ycm/vimsupport.py
When compiled without C-family support, YCM will use the default omnifunc from Vim (`ccomplete#Complete`) to provide semantic completion. This omnifunc calls [`searchdecl`](http://vimdoc.sourceforge.net/htmldoc/eval.html#searchdecl()) to find a declaration, which is supposed to move the cursor to that declaration. However, the cursor is not moved when called through the omni completion mapping (`CTRL-X CTRL-O`). Since PR https://github.com/Valloric/YouCompleteMe/pull/2657, YCM calls the omnifunc outside completion mode and thus the cursor is moved to the found declaration after typing `.` or `->`.
Considering this `searchdecl` trick may be used by other omnifuncs, we fix the issue by always restoring the cursor position after calling the omnifunc.
Fixes #2698.
--- …
> [READY] Restore cursor position after omnifunc call

- python/ycm/omni_completer.py
- python/ycm/tests/omni_completer_test.py
- python/ycm/youcompleteme.py
We currently cache the omnifunc when the file is ready to be parsed i.e. on the `FileType`, `BufEnter` events and possibly on `InsertLeave` and `TextChanged`. That's problematic if the omnifunc is modified after these events and the user is requesting completions from it. This was the cause of issue https://github.com/Valloric/YouCompleteMe/issues/1027 but is not relevant anymore because we now always parse the file on the `BufEnter` event and thus the omnifunc is properly updated after switching buffers. Still, it's more correct to cache the omnifunc inside the `ShouldUseNow` method since `ComputeCandidatesInner` is called immediately after. Performance is not a concern: it takes less than 10 μs to get the omnifunc.
Fixes https://github.com/Valloric/YouCompleteMe/issues/1027.
---
This …
> [READY] Do not cache omnifunc on FileReadyToParse event

- python/ycm/tests/event_notification_test.py
- python/ycm/youcompleteme.py
When a buffer is unloaded, [we compare its name to the current buffer one in the `BuildRequestData` function](https://github.com/Valloric/YouCompleteMe/blob/5b89d4183232758f0ea02acee93d08b74e188dc7/python/ycm/client/base_request.py#L160). This raises a unicode warning on Python 2 when the deleted buffer name contains non-ASCII characters because the deleted buffer name is a byte object while the current buffer name is a unicode one.
I updated the `BufferUnload` test to show the issue. I'll send the fix once the builds failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2710)
> [READY] Fix unicode warning when unloading buffer on Python 2

- autoload/youcompleteme.vim
When `completefunc` is not set (because YCM is not allowed to complete in the current buffer or the server failed to start) and semantic completion is forced with `<C-Space>`, Vim returns the following error:
```
E764: Option 'completefunc' is not set
```
This happens because we don't check if `completefunc` is set to `youcompleteme#CompleteFunc` in that case.
To completely avoid this issue, we always set the `completefunc` before invoking it. This may look inefficient but, in practice, the performance cost is almost nil.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2722)
> [READY] Check completefunc when forcing semantic completion

- plugin/youcompleteme.vim
No tests because we don't have Vimscript tests. But I tested:
* System Vim on macOS:
```
BeniMac:YouCompleteMe-Clean ben$ /usr/bin/vi
YouCompleteMe unavailable: requires Vim 7.4.1578+.
Info: You appear to be running the default system Vim on macOS. It reports as patch 8056, but it is really older than 1578. Please consider MacVim, homebrew Vim or a self-built Vim that satisfies the minimum requirement.
Press ENTER or type command to continue
```
* Manually built too-old Vim on macOS (regression test)
```
BeniMac:vim ben$ ./src/vim
YouCompleteMe unavailable: requires Vim …
```
> [RFC] Add a more obvious explanation for users of the default system Vim on macOS

- autoload/youcompleteme.vim
When sending keys to Vim through `feedkeys`, these keys are by default added to the end of the typeahead buffer. If there are already keys in the buffer, they will be processed first and may change the state that our keys combination was sent for. For instance, `<C-X><C-U><C-P>` may be sent in normal mode instead of insert mode (issue #2731) or `<C-e>` outside of completion mode (issue #2732). We avoid that by inserting the keys at the start of the typeahead buffer with the `i` option.
Fixes #2731.
Fixes #2732.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2733)
> [READY] Insert keys at the start of the typeahead buffer

- README.md
- doc/youcompleteme.txt
By linking to a specific version of [ycmd `.ycm_extra_conf.py` file](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/.ycm_extra_conf.py) in the docs, users following the link won't copy a version of this file that's incompatible with the current version of YCM when that file is modified because of a change in our `.ycm_extra_conf.py` specs (like in PR https://github.com/Valloric/ycmd/pull/795), and ycmd submodule is not yet updated.
Also, link to the raw file instead of the github page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2737)
> [READY] Pin YCM extra conf version in documentation

- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
When the ycmd server crashes, we read its standard error and log the result. Unfortunately, this blocks Vim if a sub-server is still running after the crash (e.g. JediHTTP). In that case, the only way to unblock Vim is to manually kill the sub-server.
We could fix the issue by writing some (non-trivial) code that reads ycmd `stderr` without blocking but instead we simply don't read it at all. The drawback is small: [ycmd immediately redirects its `stdout` and `stderr` to logfiles at startup](https://github.com/Valloric/ycmd/blob/ff255aed4aac0b923313254f73d1f3d40f87d707/ycmd/__main__.py#L150-L153). In other words, reading its `stderr` is only useful if ycmd crashed before the redirection. This is something that should never happen.
--- …
> [READY] Do not read server standard error

- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
This PR improves the error message displayed to the user when the server unexpectedly crashes by giving the exact command to type to open the server logfile.
We could go further by automatically opening the server logfile but this is too disruptive in my opinion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2752)
> [READY] Improve error message when server crashes

- README.md
- doc/youcompleteme.txt
Update the documentation for the `ClearCompilationFlagCache` subcommand by taking into account that:
- the `do_cache` parameter is set to `True` by default;
- the flags from the compilation database are also cached;
- restarting the server clears the cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2763)
> [READY] Update ClearCompilationFlagCache docs

- README.md
- doc/youcompleteme.txt
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
The location list is specific to the current window so it should be opened inside the current window (default behavior), not to full width at the bottom of the screen (with `:botright`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2781)
> [READY] Do not open location list at the bottom of screen

- README.md
- doc/youcompleteme.txt
Both notes are obsolete: [libclang correctly returns the type for `auto` since version 3.8](https://github.com/Valloric/ycmd/pull/353) and diagnostics are automatically refreshed after applying a fix-it since PR https://github.com/Valloric/YouCompleteMe/pull/2636.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2782)
> [READY] Remove obsolete notes in documentation

- python/ycm/paths.py
- python/ycm/tests/__init__.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
YCM returns the cryptic error `YouCompleteMe unavailable: [Errno 2] No such file or directory` when the Python interpreter path used to start the server doesn't exist. See issues https://github.com/Valloric/YouCompleteMe/issues/2773 and https://github.com/Valloric/YouCompleteMe/issues/2775.
This PR improves that by using the `FindExecutable` and `GetExecutable` functions from ycmd to check if the Python interpreter path exists (and is an executable) and by returning a much more helpful message if it doesn't. We use `FindExecutable` instead of `GetExecutable` on the `g:ycm_server_python_interpreter` option so that the user can specify a Python path with just the executable name (e.g. `python`, `python2`, `python3`).
This also fixes a Python traceback in Vim that occurs when, after …
> [READY] Improve path to python interpreter error handling

- README.md
- Updated Linux64 instructions for older systems where cmake(2.8) might be causing compilation issues.
- Using cmake3 may likely address issues (in certain scenarios)
This is a non-code PR adding instructions to the README.md file for situations where `cmake` may be the issue. The instructions simply specify that under certain scenarios, using `cmake3` instead of `cmake` may address the compilation-issues of YCM (eg. on older systems like Ubuntu 14.04). A reference to this issue can be found under the discussion here: …
> Added instructions for cmake3

- python/ycm/diagnostic_interface.py
- python/ycm/tests/__init__.py
- python/ycm/tests/youcompleteme_test.py
If there is a diagnostic on the current line while updating diagnostics, echo it on the command line. Here's a demo:
Without this change, users have to move the cursor up and down to see the message on the command line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2797)
> [READY] Echo diagnostic asynchronously

- autoload/youcompleteme.vim
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
Instead of notifying the user if the server crashed immediately after starting it (which is unlikely to work because the server process is necessarily up at this point), do it during polling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2798)
> [READY] Improve server crash notification at startup

- README.md
- doc/youcompleteme.txt
Prior to version 8.0.0127, Vim would insert the first suggestion when leaving completion while auto-wrapping text. See issue https://github.com/vim/vim/issues/1312 and [the corresponding patch](https://github.com/vim/vim/commit/73fd4988866c3adc15b5d093efdf5e8cf70d093d). This would cause issues #771 and #2789 when using YCM.
We mention this bug in the FAQ and suggest to update to Vim 8.0.0127 or later.
Closes https://github.com/Valloric/YouCompleteMe/issues/771.
Closes https://github.com/Valloric/YouCompleteMe/issues/2789.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2802)
> [READY] Mention auto-insert wrapping bug in the FAQ

- README.md
- doc/youcompleteme.txt
There are some issues with [7-Zip 9.20](http://www.7-zip.org/download.html) when extracting files from the Clang installer. See https://github.com/Valloric/YouCompleteMe/issues/2756 and https://github.com/Valloric/YouCompleteMe/issues/2811.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2816)
> [READY] Update 7-Zip requirement to 16.04 or later

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
While I was looking at PR https://github.com/Valloric/YouCompleteMe/pull/2827, I noticed that the default behavior of `GetBufferNumberForFilename` is to create a buffer for the given filename if no buffer already exists for that filename. This behavior is rather unexpected given the name of that function. In fact, `GetBufferNumberForFilename` is almost always called with the `open_file_if_needed` parameter (renamed `create_buffer_if_needed` for clarity) sets to `False`. This really suggests that the default value should be `False` instead of `True`.
In addition, that default behavior may lead to performance issues when the server returns diagnostics for a lot of files with no corresponding buffers since this will create a buffer for each one of these files.
--- …
> [READY] Change GetBufferNumberForFilename default behavior

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
Currently, YCM calls the `completefunc` at each key press even if there are no candidates. This has the side effect of always keeping the user in completion mode while typing in insert mode, which causes the following issues:
- the `<C-U>`, `<C-N>`, `<C-P>`, and `<C-E>` keys are not working as expected in insert mode when the completion menu is not visible;
- automatic comment formatting is broken in some situations. See issue https://github.com/Valloric/YouCompleteMe/issues/2552.
This is solved by only calling the `completefunc` if suggestions are available (or if the start column is not after the current column) and by closing the completion menu otherwise.
Updates the `<C-U>` entry in the FAQ.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2552.
--- …
> [READY] Only call completion function if needed

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
When the filetype is set to a number (e.g. `set filetype=42`), YCM raises the following error:
```python
File "<string>", line 1, in <module>
File "C:\\Users\\micbou\\projects\\YouCompleteMe\\autoload\..\python\ycm\youcompleteme.py", line 571, in HandleFileParseRequest
self.NativeFiletypeCompletionUsable() ):
File "C:\\Users\\micbou\\projects\\YouCompleteMe\\autoload\..\python\ycm\youcompleteme.py", line 362, in NativeFiletypeCompletionUsable
return ( self.CurrentFiletypeCompletionEnabled() and
File "C:\\Users\\micbou\\projects\\YouCompleteMe\\autoload\..\python\ycm\youcompleteme.py", line 674, in CurrentFiletypeCompletionEnabled
filetypes = vimsupport.CurrentFiletypes()
File "C:\\Users\\micbou\\projects\\YouCompleteMe\\autoload\..\python\ycm\vimsupport.p …
```
> [READY] Fix error when filetype is a number

- ci/travis/travis_install.sh
Fix the `shell_session_update: command not found` error in macOS builds on Travis by removing [the `cd`, `popd`, `pushd` functions defined by RVM](https://github.com/rvm/rvm/blob/ff63fa117bd05e581ecbf2b0378d9ddbb263deb1/scripts/cd#L14-L16). See https://github.com/travis-ci/travis-ci/issues/8703#issuecomment-347881274.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2840)
> [READY] Fix macOS builds on Travis

- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Spaces are not the only characters that need to be escaped when passing a filepath to a Vim command: `*`, `?`, `[`, `{`, etc. should be escaped too. Instead of escaping each one of these characters in Python, we use [the Vim function `fnameescape`](http://vimdoc.sourceforge.net/htmldoc/eval.html#fnameescape()).
Closes #2623.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2834)
> [READY] Use fnameescape to escape filepath

- python/ycm/vimsupport.py
On Windows, Vim returns buffer filepaths with forward slashes instead of backward ones if [the `shellslash` option](http://vimdoc.sourceforge.net/htmldoc/options.html#'shellslash') is set. Since the server always return paths with backslashes on that platform, [the paths comparison in `JumpToLocation`](https://github.com/Valloric/YouCompleteMe/blob/e8e144d446603fbaebf23c54491f43ccd79b65f4/python/ycm/vimsupport.py#L409) will incorrectly return `True` for two equivalent paths. We need to normalize the paths from Vim.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2838)
> [READY] Normalize buffer filepath

- README.md
- doc/youcompleteme.txt
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
Instead of displaying the list of available logfiles, prompt the user to open (or close if already
open) one of them when running the `:YcmToggleLogs` command with no arguments. Keep the current behavior when one or more arguments are given.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2860)
> [READY] Prompt the user to select a logfile with the YcmToggleLogs command

- python/ycm/client/base_request.py
- python/ycm/tests/client/base_request_test.py
- python/ycm/youcompleteme.py
This allows completer servers to detect the correct directory to launch
no matter what request initialises the completer server.
This change ensures that the client supplies the working directory to the server on each request, in particular, event notifications; the java and javascript completers use this to start the server in the `FileReadyToParse` event, rather than on construction of the completer. The subtle difference allows them to use the client's working directory, rather than the _server's_ working directory to do things like project detection.
See also:
* This …
> [READY] Always supply working directory

- python/ycm/tests/omni_completer_test.py
Now that the server supports Java natively (or will soon), we need to use a
filetype that does not have native support to ensure that we call the
mocked omnifunc, but also one for which YCM has a semantic trigger.
Rather than picking another random languagse, which might break in the
future, we invent a language (ycmtest) and supply a manual trigger
mapping to the YouCompleteMe object.
References:
* Part 2 of the java completer client changes
* You probably previously saw this using ruby, but this was always a hack. This solution is permanent.
[cont]: …
> [READY] Use fake filetype for omni completion test

- README.md
- doc/youcompleteme.txt
See PR https://github.com/Valloric/ycmd/pull/884. Also, remove the part where we suggest to replace `msbuild` with `xbuild` since [`xbuild` is deprecated](http://www.mono-project.com/docs/about-mono/releases/5.0.0/#xbuild).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2848)
> [READY] Update MSBuild command in documentation

- README.md
At the request of the nice folk over at `#vim` on free node, this PR signposts the contact details and installation instructions at the top of the readme so that users seeking help use our contact details, rather than asking over there.
Overall it is better for users to seek support from us because:
* we have better knowledge and can solve issues more quickly
* we get better visibility of in-the-wild issues and sticking points
* certain #vim users feel that they are unduly burdened with supporting setup issues for YCM
cc @romainl 
[cont]: …
> [READY] Signpost the contact details earlier in the README

- autoload/youcompleteme.vim
- python/ycm/client/base_request.py
- python/ycm/client/event_notification.py
- python/ycm/tests/client/base_request_test.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
This PR significantly reduces the time spent to build the request when there are a lot of buffers. This is done by:
- using the `options` property on the buffer object to get the `mod` variable instead of evaluating `getbufvar`;
- not computing the buffer filepath if the buffer is not modified;
- passing the number of the unloaded buffer instead of its filepath on the `BufferUnload` event. Getting the Python buffer object from its number is easier than from its filepath.
Here are the times spent to edit a new empty buffer (i.e. two event notifications `BufferVisit` and `FileReadyToParse`) for different numbers of buffers already open in the editor before and after the changes:
<table>
<tr>
<th>Number of buffers open</th>
<th>Before (ms)</th>
<th>After (ms)</th>
</tr>  
<tr>    
<td>1</td> …
> [READY] Optimize request building

- python/ycm/vimsupport.py
When the message is exactly as wide as the vim window, vim still
displays "press enter..." message.
The bug can be demonstrated if we hardcode the `message` to `&columns * 'a'` and forcing `truncate` to `True`.
No tests because I didn't think it was necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [READY] Fix truncation of messages when len(message) == vim_width

- python/ycm/tests/command_test.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/youcompleteme.py
Evaluating the values of [the `g:ycm_extra_conf_vim_data` option](https://github.com/Valloric/YouCompleteMe#the-gycm_extra_conf_vim_data-option) may raise a Python exception (e.g. one of the values is not defined). Since that option is evaluated each time a request is sent, such exception can render the editor almost unusable as each key press will print a Python traceback to the user. 
A simple way to reproduce the issue is to add the following line in vimrc:
```viml
let g:ycm_extra_conf_vim_data = [ 'undefined_value' ]
```
We fix that by catching and logging the exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2899)
> [READY] Avoid traceback when computing extra conf data

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Without the proposed fix, the test included in that PR fails as follows
```
FAIL: ycm.tests.vimsupport_test.ReplaceChunksInBuffer_LineOverlappingChunks_test
----------------------------------------------------------------------
File "C:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
self.test(*self.arg)
File "C:\Users\micbou\projects\YouCompleteMe\python\ycm\tests\vimsupport_test.py", line 768, in ReplaceChunksInBuffer_LineOverlappingChunks_test
AssertBuffersAreEqualAsBytes( expected_buffer, result_buffer )
File "C:\Users\micbou\projects\YouCompleteMe\python\ycm\tests\vimsupport_test.py", line 86, in AssertBuffersAreEqualAsBytes
eq_( ToBytes( result_line ), ToBytes( expected_line ) )
AssertionError: b'    third line' != b'    third '
``` …
> [READY] Apply chunks from bottom to top

- appveyor.yml
We should always test for the latest version of Python on AppVeyor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2908)
> [READY] Test for Python 3.6 on AppVeyor

- README.md
- doc/youcompleteme.txt
- python/ycm/client/completion_request.py
- python/ycm/tests/client/completion_request_test.py
- python/ycm/tests/postcomplete_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
Java completer can include FixIts which are applied when a completion
entry is selected. We use the existing mechanism implemented for c-sharp
to perform these edits using the CompleteDone autocommand.
However, the existing mechanism relies on pattern matching the source to
work out which item was completed. Vim patch 8.0.1493 introduces support
for user_data on completion items, so when available we populate it with
the completion array index of the item and use that to get the exact
element that was selected. This is both a lot faster and a lot more
accirate.
Of course when applying these 'FixIts' we don't interrupt the user with
confirmation or the quickfix list as this would just be annoying. If the
server reports that an edit must be made, we just make the edit.
The Java completer …
> [READY] Support for additional FixIts on java completions, e.g. for automatic imports

- autoload/youcompleteme.vim
[`<range>` was introduced in Vim 8.0.1089](https://github.com/vim/vim/commit/c168bd4bd3a9b856fc410fc4515dcca1d10d7461). Use `<count>` instead.  It returns `-1` when no range is given.
Fixes #2913.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2914)
> [READY] Replace <range> with <count> in YcmCompleter command

- python/ycm/diagnostic_interface.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
Currently, we store internally the signs that we place in the buffer so that when we receive a new batch of diagnostics, we can efficiently add and remove signs by looking at the line positions of the stored signs. However, there is a flaw in that approach. When lines are added or removed to the buffer, Vim update the lines of the signs accordingly and thus our stored signs may not correspond anymore to the actual signs. Here's an example of the issue:
*Where did my signs go? I want a refund!*
The solution is to not store the signs but instead get them directly from Vim each time we need to update them. This is done by parsing the output of the `:sign place` command (Vim doesn't provide an API to properly do that). The same example as above with the proposed changes:
*Oh, they were …
> [READY] Improve diagnostic sign placement

- python/ycm/syntax_parse.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/test_utils.py
- python/ycm/vimsupport.py
Since there are now two places where we need to capture the output of a Vim command (for diagnostic signs and for syntax keywords), we should add a function for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2921)
> [READY] Add function to capture Vim command output

- autoload/youcompleteme.vim
- python/ycm/buffer.py
- python/ycm/diagnostic_interface.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
There are two issues with how we display diagnostic matches. The first issue is that if the current buffer contains diagnostic matches and is split in a new window, all the matches are cleared and only matches in the new window are shown. The second issue is that if a new buffer with no diagnostic support is open in the current window and that window already contained matches then the matches are still displayed. Here's an illustration of both issues (signs are disabled):
The solution is to add an autocommand that updates matches on the `BufEnter` and `WinEnter` events. Here's the result:
Note that it's not perfect as multiple windows of the same buffer won't be updated simultaneously. Supporting that scenario is rather tricky because we would need to go through all the windows to update …
> [READY] Improve diagnostic matches display

- README.md
- doc/youcompleteme.txt
Arguments may be ignored when running the `install.py` script in a `cmd.exe` prompt if the command associated to Python files is incorrect. Update the Windows instructions by prefixing the commands with `python`.
Fixes #2929.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2931)
> [READY] Prefix commands with python in Windows instructions

- README.md
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
When FixIt was originally implemented, I decided to present the quick fix list containing the set of changes made to the buffers as it was thought this would be helpful and would reassure the user that the changes we made to their code made sense and were safe. Some large part of this decision was paranoia.
Since then we're using fixit code in a lot more places and the feature is pretty mature. I personally find the opening of the quick fix window to be a bit of a pain, and I quickly end up closing it manually to reclaim the space. I have literally never used it to jump to …
> [READY] Don't open the quickfix window after FixIt/Refactor

- README.md
- doc/youcompleteme.txt
7-Zip is not required anymore on Windows since we now extract libclang from our  `.tar.bz` packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2942)
> [READY] Remove 7-Zip dependency from Windows instructions

- README.md
- doc/youcompleteme.txt
The `<C-R>` key cannot be remapped in YCM's completion mode (`<C-X><C-U>`) due to a Vim limitation. Add an entry in the FAQ about this.
Closes https://github.com/Valloric/YouCompleteMe/issues/2943.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2946)
> [READY] Add an entry in the docs about remapping CTRL-R in completion mode

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
When sending a request to the server, [we add a newline to the buffer contents to match what gets saved to disk](https://github.com/Valloric/YouCompleteMe/blob/d3381411a047a216a1df5d33e2d8551ef611b157/python/ycm/vimsupport.py#L117). If the server generates a chunk containing that newline, this chunk goes past the Vim buffer contents since there is actually no new line, which raises an `IndexError` exception when applying the chunk. We fix the issue by recomputing the end position of where the chunk is applied and by removing all trailing characters in the chunk.
Steps to reproduce the issue:
- create a `Test.java` file with the following contents:
```java
package Test;$
$
```
where `$` represents an end of line;
- issue the `:YcmCompleter Format` command.
--- …
> [READY] Fix index error when applying a chunk at the end of file

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
We need to convert the Vim buffer to bytes in the `LineAndColumnNumbersClamped` function to correctly compute the length of the line as a byte offset (and not a Unicode offset) on Python 3.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2956)
> [READY] Fix column clamping when highlighting diagnostics on Python 3

- python/ycm/client/completion_request.py
- python/ycm/tests/client/completion_request_test.py
- python/ycm/tests/postcomplete_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
Since the `CompleteDone` code only depends on the completion request, it makes sense to move its logic to the `CompletionRequest` class. This is also going to help fixing the issue where a FixIt is applied twice when selecting a completion:
Finally, this reduces the time it takes to run the tests because the ycmd server is not started anymore in the `postcomplete` tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2963)
> [READY] Refactor CompleteDone logic

- README.md
- doc/youcompleteme.txt
The Java completer does not provide a `GoToImplementation` command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2980)
> [READY] Remove Java from the GoToImplementation command in docs

- python/ycm/client/base_request.py
- python/ycm/client/command_request.py
- python/ycm/client/completer_available_request.py
- python/ycm/client/completion_request.py
- python/ycm/client/debug_info_request.py
- python/ycm/client/event_notification.py
- python/ycm/client/messages_request.py
- python/ycm/client/shutdown_request.py
- python/ycm/client/ycmd_keepalive.py
- python/ycm/omni_completer.py
- python/ycm/tests/completion_test.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
Having to wrap all request calls with the `HandleServerException` function is inconvenient. Handle server exceptions directly in `BaseRequest`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2976)
> [READY] Refactor server exception handling

- python/ycm/omni_completer.py
- python/ycm/tests/omni_completer_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
Prior to PR https://github.com/Valloric/YouCompleteMe/pull/2657, it was possible to trigger Vim's omnifunc with `<C-Space>` even if semantic completion was disabled for the current filetype through the `g:ycm_filetype_specific_completion_to_disable` option. It worked because `<C-Space>` was mapped to `<C-X><C-O><C-P>`, which are the keys to trigger the omnifunc. PR https://github.com/Valloric/YouCompleteMe/pull/2657 changed that by making `<C-Space>` directly call the `SendCompletionRequest` function with `force_semantic` sets to `True`. This change was necessary to get fuzzy matching with the omnifunc (see issue https://github.com/Valloric/YouCompleteMe/issues/961) but broke the `<C-Space>` behavior when filetype completion is disabled. This PR restores that behavior.
Fixes …
> [READY] Do not disable omnifunc when filetype completion is disabled

- README.md
- doc/youcompleteme.txt
The `GoToType` command was added a long time ago to the TypeScript completer (see PR https://github.com/Valloric/ycmd/pull/458) but not mentioned in the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2983)
> [READY] Add GoToType command to documentation

- python/ycm/omni_completer.py
We currently return unfiltered and unsorted suggestions from the omnifunc if the `filter_and_sort_candidates` request failed (generally because the server crashed). This behavior is confusing as it may let the user thinks that YCM is working (in a bad way) while in fact it doesn't. No suggestions should be returned in that case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2989)
> [READY] Do not return omnifunc suggestions if server crashed

- autoload/youcompleteme.vim
- python/ycm/buffer.py
- python/ycm/client/base_request.py
- python/ycm/client/ycmd_keepalive.py
- python/ycm/omni_completer.py
- python/ycm/tests/__init__.py
- python/ycm/tests/event_notification_test.py
- python/ycm/youcompleteme.py
When the client sends a request to the server, if an extra conf file is found that is not already white/blacklisted, the server stops processing the request and tells the client that an unknown extra conf file has been found. The client then asks the user if that file should be loaded or not. Depending on the
user's answer, the client sends a request to the server to load or ignore the extra conf file. Finally, the server loads the file or adds it to the blacklist. However, the initial request was not processed by the server and should be sent again.
Here's a demo illustrating the current situation:
As you can see, the file is not parsed after loading the extra conf file. With the proposed changes:
Fixes #2962.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [READY] Resend request when extra conf is loaded or ignored

- README.md
- doc/youcompleteme.txt
- install.py
- plugin/youcompleteme.vim
Issues https://github.com/Valloric/YouCompleteMe/issues/2525 and https://github.com/Valloric/YouCompleteMe/issues/2992 are due to YCM being incompatible with Python 2.7.0 for the reason mentioned in our Travis script:
> Tests are failing on Python 2.7.0 with the exception "TypeError: argument can't be <type 'unicode'>"
Increase the Python 2 requirement to 2.7.1.
Closes https://github.com/Valloric/YouCompleteMe/issues/2525.
Closes https://github.com/Valloric/YouCompleteMe/issues/2992.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2998)
> [READY] Increase Python 2 requirement to 2.7.1

- README.md
- doc/youcompleteme.txt
The tools we are using to convert our `README.md` file into Vim docs ([html2vimdoc](https://github.com/xolox/vim-tools)) and into HTML for the YCM website ([Python-Markdown](https://python-markdown.github.io/#features)) don't support GitHub Markdown tables. We need to write the table in HTML and use @puremourning's changes to [html2vimdoc](https://github.com/xolox/vim-tools) which adds support for simple HTML tables. The result is not perfect but still better than what we currently have.
The html2vimdoc version used to generate the Vim docs can be found in [this branch](https://github.com/micbou/vim-tools/tree/ycm).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/30 …
> [READY] Write table in HTML in docs

- .github/ISSUE_TEMPLATE.md
When reporting an issue, users may include the contents of the logfiles with the default log level `info`, which is not really useful. Ask them to set the log level to `debug`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3012)
> [READY] Ask users to set the log level to debug when including the contents of the logfiles

- doc/youcompleteme.txt
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
The `YcmShowDetailedDiagnostic` command raises a `NoneType` exception on a line with no diagnostic;
```
File "<string>", line 1, in <module>
File "YouCompleteMe/autoload\..\python\ycm\youcompleteme.py", line 663, in ShowDetailedDiagnostic
if 'message' in detailed_diagnostic:
TypeError: argument of type 'NoneType' is not iterable
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3035)
> [READY] Fix YcmShowDetailedDiagnostic command on line without diagnostic

- python/ycm/diagnostic_interface.py
- python/ycm/tests/client/base_request_test.py
- python/ycm/tests/command_test.py
- python/ycm/tests/completion_test.py
- python/ycm/tests/event_notification_test.py
- python/ycm/tests/omni_completer_test.py
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
Since the `getmatches` and `setmatches` Vim functions only allow manipulating matches for the current window, we shouldn't update diagnostic matches if the buffer is not the current window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3024)
> [READY] Update diagnostic matches for all windows

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/client/command_request.py
- python/ycm/tests/client/command_request_test.py
- python/ycm/tests/command_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
This PR allows users to customize how a window is split when running the `GoTo*` commands by prefixing them with the modifiers `:aboveleft`, `:belowright`, `:botright`, etc. (see `:h mods` for the complete list). For instance, to split a window vertically at the right of the screen, one could do:
```viml
:botright vertical YcmCompleter GoTo
```
The `'horizontal-split'` and `'vertical-split'` values of the `g:ycm_goto_buffer_command` option are replaced by `'split'` since a vertical split can be obtained by prefixing the `:vertical` modifier. Those values are still kept for backward compatibility.
A new value is added `'split-or-existing-window'` that is equivalent to `new-or-existing-tab` when the `:tab` modifier is used. Without the `:tab` modifier, the `GoTo*` commands only jump to an …
> [READY] Support modifiers for GoTo commands

- README.md
- doc/youcompleteme.txt
- python/ycm/buffer.py
- python/ycm/client/completion_request.py
- python/ycm/tests/event_notification_test.py
This updates the documentation with the proposed changes in https://github.com/Valloric/ycmd/pull/1036#issuecomment-397234687. The Tern instructions are moved to [this wiki page](https://github.com/Valloric/YouCompleteMe/wiki/JavaScript-Semantic-Completion-through-Tern). JavaScript is added to the list of supported filetypes for diagnostics and completion fixits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3089)
> [READY] Update JavaScript support and documentation

- codecov.yml
I don't know why but codecov includes the `tests` folder in its coverage report since [we migrated to Python 3.7 on AppVeyor](https://github.com/Valloric/YouCompleteMe/commit/2d213e7ed2d0230a6090d11157f33d134a52cc26). Ignoring the folder in codecov configuration file like [we already do in the ycmd repository](https://github.com/Valloric/ycmd/blob/ea58cfcf502dad92258102a5dd1911d43e39bcda/codecov.yml#L16-L25) fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3108)
> [READY] Ignore tests in codecov configuration

- README.md
- doc/youcompleteme.txt
Issue #3054 is fixed in [Vim 8.1.0256 or later](https://github.com/vim/vim/commit/9fa9506853516c82851baec643aa47458cb8b3bc). Mention it in the FAQ.
Closes #3054.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3111)
> [READY] Add entry in FAQ about automatic import insertion breaking undo

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Command modifiers (see `:h mods`) were added in [Vim 7.4.1898](https://github.com/vim/vim/commit/63a60ded3fd584847a05dccf058026e682abad90#diff-28587d36c24b61c33d4d01601f5974ee) while we support 7.4.1578 and later.
Fixes https://github.com/Valloric/YouCompleteMe/issues/3105.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3120)
> [READY] Only use command modifiers if available

- python/ycm/omni_completer.py
- python/ycm/tests/omni_completer_test.py
An omnifunc may move the cursor position even on the first call, e.g. [`completeR` from the `Nvim-R` plugin](https://github.com/jalvesaq/Nvim-R/blob/0db20893d34654aefe2ea1027d815159556330a7/R/common_global.vim#L3383). The cursor position is not restored between the two calls because it's unnecessary with the changes from PR #3112.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3117)
> [READY] Restore cursor position after omnifunc calls

- README.md
- doc/youcompleteme.txt
Add CUDA to the list of C-family languages in the docs and use the "C-family languages" expression when appropriate (instead of enumerating each language).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3123)
> [READY] Add CUDA to C-family languages in documentation

- python/ycm/omni_completer.py
- python/ycm/tests/omni_completer_test.py
Contrarily to [what the docs say](https://github.com/vim/vim/blob/3f6a16f022c437eccaeb683640b25a972cb1b376/runtime/doc/insert.txt#L1057-L1058), [Vim only stops completion if the value returned by the omnifunc is `-3` or `-2`](https://github.com/vim/vim/blob/3f6a16f022c437eccaeb683640b25a972cb1b376/src/edit.c#L5585-L5621). In other cases, if the value is negative or greater than the current column, the start column is set to the current column; otherwise, the value is used as the start column.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3125)
> [READY] Improve omnifunc compliance when start column is invalid

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
When replacing an area of the buffer with `ReplaceChunk`, we are replacing the whole last line of that area because the Python interface doesn't allow changing only some part of a line. If the cursor is positioned on that line just after the ending column of the replaced area, we expect the cursor to be moved depending on the amount of text replaced. However, since the whole line is replaced, Vim cannot figure where the cursor should be positioned and so the cursor is not moved. This leads to the cursor ending in an unexpected position after a FixIt is applied. Here's an illustration of the issue in TypeScript where an import statement is automatically inserted after selecting a completion:
The solution is to manually move the cursor in that case:
--- …
> [READY] Fix cursor position when replacing chunk

- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
The height of the quickfix and location list windows is set to fit all entries by assuming that the lines of the entries are always wrapped if they are longer than the window width. This assumption is wrong if `nowrap` is set. In that case, the height should be set to the number of entries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3134)
> [READY] Set window height according to the wrap option

- README.md
- doc/youcompleteme.txt
As proposed in https://github.com/Valloric/YouCompleteMe/pull/3055#pullrequestreview-149835682, merge the Ubuntu Linux x64 and Fedora Linux x64 instructions into one section for Linux 64-bit. The result can be seen [here](https://github.com/micbou/YouCompleteMe/tree/merge-linux-docs#linux-64-bit).
I confirmed the required packages for Fedora are `gcc-c++`, `cmake`, `python3-devel` (and `ncurses-compat-libs` for C/C++) by installing the distribution in a VM.
Closes #3069.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3140)
> [READY] Merge Linux distributions instructions

- README.md
- doc/youcompleteme.txt
The `pom.xml` link is broken (the `java-language-server` branch doesn't exist). Use a specific commit for the Java links so that they can't be affected by a change in ycmd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3147)
> [READY] Update Java links in documentation

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/client/command_request.py
- python/ycm/tests/command_test.py
- python/ycm/youcompleteme.py
The `ft=` argument of the `YcmCompleter` command is supposed to allow users to specify a completer when running a command. However, this was broken a long time ago in commit https://github.com/Valloric/YouCompleteMe/commit/29bb90a6b434ec6b462398268fbe871924cbe8ed. Only the `ycm:ident` value is still supported but it serves no purpose because the identifier completer doesn't define commands. Ignore completely the `ft=` argument and move the logic to the Python layer. Remove the argument from the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3161)
> [READY] Ignore ft= argument from YcmCompleter command

- README.md
- doc/youcompleteme.txt
The behavior of `get_default_environment` has been changed in the latest version of Jedi. Instead of picking the latest version of Python available on the system, it now uses the one it's running on i.e. the one running ycmd in our case. See https://github.com/davidhalter/jedi/issues/1196. Update the docs accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3176)
> [READY] Update docs about the default version of Python used for completion

- .ycm_extra_conf.py
- autoload/youcompleteme.vim
Ideally, we shouldn't add anything to the Python path because it can break other plugins written in Python but since the alternative is to tell users to manually install our dependencies, we don't really have a choice (the last thing we want are reports about pip failing to install packages). Still, we can at least only add the dependencies we need:
- [requests](https://github.com/requests/requests);
- [pythonfutures](https://github.com/agronholm/pythonfutures) in Python 2;
- [requests-futures](https://github.com/ross/requests-futures);
- [frozendict](https://github.com/slezica/python-frozendict);
- [python-future](https://github.com/PythonCharmers/python-future). 
Fixes #3162.
--- …
> [READY] Add minimal dependencies to Python path

- autoload/youcompleteme.vim
I made a mistake while configuring ycm and used a list instead of a ditionary for the blacklist, like so:
```vim
let g:ycm_filetype_blacklist = ['python']
```
If the `CursorMoved` autocmd is installed while the configuration is not a dictionary, an error message is raised after every keystroke, this makes fixing the configuration error a bit painful. Error message:
```
Error detected while processing function <SNR>78_OnCursorMovedNormalMode[1]..<SNR>78_AllowedToCompleteInCurrentBuffer[1]..<SNR>78_AllowedToCompleteInBuffer:
line   15:
E715: Dictionary required
```
This PR just adds a check for the type of the variable `g:ycm_filetype_blacklist`, if it's  the wrong type a message is printed and the autocmd is not installed. …
> added type check for g:ycm_filetype_blacklist

- python/ycm/base.py
- python/ycm/omni_completer.py
- python/ycm/tests/base_test.py
- python/ycm/tests/omni_completer_test.py
Vim allows each item of the list returned by an omnifunc to be either a string
or a dictionary (see `:h complete-items`) but ycmd only supports lists where items are all strings or all
dictionaries. Convert all strings into dictionaries.
Fixes https://github.com/Valloric/YouCompleteMe/issues/3103.
Fixes https://github.com/Valloric/YouCompleteMe/issues/3179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3104)
> [READY] Convert strings from omnifunc into dictionaries

- python/ycm/client/completion_request.py
- python/ycm/tests/client/completion_request_test.py
- python/ycm/tests/postcomplete_test.py
The `detailed_info` field may contain null characters e.g. `\x00` in Python docstrings (though it doesn't make sense to use such characters in a docstring). Since these characters cannot be evaluated through `pyeval` (and `py3eval`), we replace them with the symbol used by Vim to display them (`^@`).
This PR also rewrites the `_ConvertCompletionDataToVimData` function by relying on two things:
- [the `insertion_text` field is always defined](https://github.com/Valloric/ycmd/blob/600f54de207207a69761e3b585a3bc12194eb49f/ycmd/responses.py#L109);
- [Vim ignores fields with an empty string](https://github.com/vim/vim/blob/833e5dab143034b7e43bc0be49b2eb3687ff9ab7/src/edit.c#L2748-L2755).
I did some measurements and the performance hit is negligible.
Fixes #3207.
--- …
> [READY] Handle null characters in completion response

- python/ycm/tests/test_utils.py
- python/ycm/vimsupport.py
Ensure `<c-w>p` still go to the previous window after updating matches for the current buffer.
Fixes #3228.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3229)
> [READY] Preserve previous window when updating matches

- README.md
- doc/youcompleteme.txt
We need to increase the version requirement to 7.0.0 because of PR https://github.com/Valloric/ycmd/pull/1121.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3237)
> [READY] Increase libclang version requirement in docs

- autoload/youcompleteme.vim
- plugin/youcompleteme.vim
- python/ycm/base.py
- python/ycm/client/command_request.py
- python/ycm/diagnostic_filter.py
- python/ycm/tests/__init__.py
- python/ycm/tests/client/command_request_test.py
- python/ycm/tests/command_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
A small step in decoupling YCM and ycmd. Instead of loading the default settings from ycmd, define them directly in the `plugin/youcompleteme.vim` file along the other options. This removes the `frozendict` and `user_options_store` dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3243)
> [READY] Remove user_options_store dependency

- README.md
- doc/youcompleteme.txt
The FAQ entry about libclang being too old is not relevant anymore. Replace it with the `undefined symbol: clang_getCompletionFixIt` error that occurs when ycmd loads a libclang older than 7.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3269)
> [READY] Update FAQ entry about outdated libclang

- python/ycm/base.py
- python/ycm/tests/base_test.py
The assumption that the `abbr` field always exist does not hold when candidates are from Vim's omnifunc.
Fixes #3264.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3265)
> [READY] Fix insertion adjustment for omnifunc candidates

- run_tests.py
The dependencies are now explicitly added to `PYTHONPATH` in the `run_tests.py` script. Adding the `argparse` module to `sys.path` is not needed anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3266)
> [READY] Fix run_tests.py dependencies

- README.md
- doc/youcompleteme.txt
[vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs) fixed the issue preventing the `VimLeave` event from triggering some time ago. See PR https://github.com/jistr/vim-nerdtree-tabs/pull/92. Remove the plugin from the FAQ.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3277)
> [READY] Remove the vim-nerdtree-tabs plugin from FAQ

- README.md
- doc/youcompleteme.txt
There is now [a 64-bit Vim installer for Windows](https://github.com/vim/vim-win32-installer/releases).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3276)
> [READY] Update Vim installer URL for Windows

- python/ycm/tests/test_utils.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
Among other things, [Vim 8.1.0614](https://github.com/vim/vim/commit/162b71479bd4dcdb3a2ef9198a1444f6f99e6843) changed the output of the `sign place` command by adding the `priority` field:
```
--- Signs ---
Signs for test.cpp:
line=4  id=100000000  name=YcmError priority=10
line=5  id=100000001  name=YcmError priority=10
```
This breaks [the `GetSignsForBuffer` function](https://github.com/Valloric/YouCompleteMe/blob/7997fc5536e8220ed2798c5522a1eb4421577fa2/python/ycm/vimsupport.py#L204-L215) which extract the signs from the output of that command. We need to update the regex pattern used to match the lines of `sign place` for Vim 8.1.0614 or later.
--- …
> [READY] Update sign place regex pattern for newer versions

- autoload/youcompleteme.vim
Dunno how to write a test for such an _intermittent_ issue, sorry
The issue was originally reported at https://github.com/neovim/neovim/issues/6840.
If I exit neovim immediately after it starts, there are error messages like this:
```
Error detected while processing function <SNR>96_PollServerReady[1]..<SNR>96_Pyeval[2]..provider#python3#Call:
line   18:
Invalid channel: 3
Error detected while processing function <SNR>96_PollServerReady[7]..<SNR>96_Pyeval[2]..provider#python3#Call:
line   18:
Invalid channel: 3
```
The issue is not always reproducible. Usually I get once in 5 neovim runs. With this patch I don't get these message in 20 neovim runs.
In …
> [READY] Workaround "Invalid channel" errors when NeoVim exits immediately after started

- plugin/youcompleteme.vim
The current error when Python cannot be loaded
> YouCompleteMe unavailable: requires Vim compiled Python (2.7.1+ or 3.4+) support.
is misleading if Vim has been dynamically compiled against Python but is unable to find the library. See issue https://github.com/Valloric/YouCompleteMe/issues/3300 for instance. We should only return that error if `has( 'python_compiled' )` and `has( 'python3_compiled' )` are both false. Furthermore, we should check if Python 3 is available before Python 2 because on some platforms, only one Python library can be loaded at a time so if Python 2 is loaded first, Python 3 cannot be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/330 …
> [READY] Improve error message when unable to load Python

- plugin/youcompleteme.vim
Turns out neovim doesn't have `has('python_compiled')`, so we need to check if the user is running neovim before checking `has('python_compiled')`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3306)
> [READY] Restore neovim support

- README.md
- doc/youcompleteme.txt
Update the documentation with the complete list of languages affected by the `g:ycm_max_diagnostics_to_display` option and mention that the number of diagnostics is unlimited if the option is set to `0` .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3301)
> [READY] Update g:ycm_max_diagnostics_to_display docs

- README.md
- The original installation guide missed `go build` in `godef`'s directory, relating issue [here](https://github.com/Valloric/YouCompleteMe/issues/3071#issuecomment-403213723).
- The path of `gocode` and `godef` has been changed, update them in the doc.
I have tested this guide on my Manjaro laptop and it works fine, my go version is `1.11.4`.
(Since the path is too long, the vim help doc looks kind of ugly, maybe the formatting or the
path's presenting way should be changed so that it looks better. I used the `gq` command
in vim and it gave me this.)
[cont]: …
> Update Go's part in full installation guide

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
This implements @puremourning's suggestion from https://github.com/Valloric/YouCompleteMe/pull/1415#issuecomment-460197058 and adds an entry in the FAQ on how to override the `TAB` mapping in the command-line window. Since the `CmdwinEnter` event is triggered instead of `BufEnter` in that window, the `s:OnBufferEnter` function is called for that event too. Also, the contents of that window are empty when the filetype is set the first time so we ignore the `FileType` event in that window. Finally, the `qf` filetype is removed from the `g:ycm_filetype_blacklist` option since the quickfix window is always ignored.
This needs testing as these changes may not work well with plugins that create special buffers. We may have to blacklist the filetype of these buffers.
--- …
> [READY] Allow completion in the command-line window

- python/ycm/tests/client/command_request_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Fixes #3334.
Note that `autocmd! * <buffer>` is required for location lists because we don't want to remove the autocommand in other location lists. It doesn't matter for the quickfix window since there is only one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3335)
> [READY] Ensure only loclist or quickfix windows are closed

- README.md
- plugin/youcompleteme.vim
After merge of Valloric/ycmd#1191, `use_clangd` option has changed to binary, this patch updates docs to represent that change.
Needs to be merged after `third_party/ycmd` is updated to contain that PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3325)
> [READY] Update docs to represent new use_clangd flag

- README.md
- doc/youcompleteme.txt
The text `GoTo*` is not rendered in bold because of the asterisk. Instead of escaping the character, we change the text to something more in line with the other bullet points.
In case you are wondering about the other changes in the Vim docs, [I added support for Python 3 to  the `html2vimdoc.py` script](https://github.com/micbou/vim-tools/commit/2f763ac54f345e27c6395ff9d0ab5af9a905c9c6) and this required the change to not break lines on the hyphen character in order to get the same output on both versions of Python (this also has the benefit of not breaking inside a command-line flag like `--java-completer`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3359)
> [READY] Fix bold rendering issue in docs

- python/ycm/client/completion_request.py
- python/ycm/omni_completer.py
- python/ycm/tests/client/completion_request_test.py
- python/ycm/tests/omni_completer_test.py
- python/ycm/tests/test_utils.py
[Patch 8.1.1123](https://github.com/vim/vim/commit/73655cf0ca37a9aa8f56fc51bb853a8b1f7b43d4) added a new field `equal` to completion items that disable Vim filtering. Since we are using our own filtering, we should always set that field to `1`. This should in theory speed up completion and reduce flickering but I couldn't really notice a difference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3364)
> [READY] Disable Vim filtering

- README.md
- doc/youcompleteme.txt
As suggested by @bstaletic in https://github.com/Valloric/YouCompleteMe/issues/3376#issuecomment-485680582, Visual Studio Build Tools is sufficient to build YCM. Users are told to download the 2017 version since 2019 is not yet supported (require a change to the `build.py` script and [waiting for AppVeyor to release the image](https://github.com/appveyor/ci/issues/2907)).
Closes #3376.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3378)
> [READY] Instruct installing Visual Studio Build Tools 2017

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Creating a diagnostic match with a non-positive line or column number raises an exception.
Fixes #3373.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3380)
> [READY] Ensure positive position for diagnostic matches

- README.md
It referred to Valloric/YouCompleteMe instead of ycm-core/YouCompleteMe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3428)
> [READY] Fixing Codecov badge to use the right link

- README.md
- doc/youcompleteme.txt
I was installing ycm on a new machine and looking at docs and found broken links to valloric.github.io. It looks like the repos moved from the valloric github account to ycm-core and github automatically redirects links in the repos but not to github pages sites. I'm also opening a PR in https://github.com/ycm-core/ycmd for the same thing. 
--- …
> valloric.github.io -> ycm-core.github.io

- README.md
- doc/youcompleteme.txt
As far as user facing changes go, there's two:
- `FixIt` for RLS
- Generic LSP completer can specify project root files, like
`Cargo.toml` for rust-analyzer.
Should also solve the go.googlesource.com problem for users from China.
--- …
> [READY] Update ycmd submodule

- autoload/youcompleteme.vim
Since we changed the completion request mechanism to be asyncronous
using a timer, 'invoke' completion is not quite what happens now (the
completion is invoked later with feedkeys()). Instead this sends the
completion request and starts polling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3488)
> [READY] NFC: Rename InvokeCompletion to RequestCompletions

- python/ycm/tests/client/command_request_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
This is an alternative to #3494. Instead of wiping the quickfix buffer,
we're removing the `autocmd`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3495)
> [READY] Automatically delete the WinLeave autocommands

- python/ycm/tests/__init__.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
Currently `g:ycm_show_diagnostics_ui` doesn't prevent async diagnostics
from popping up.
This PR fixes that and also prevents diagnostics from changing in any
mode except normal, as I think it can be very distracting.
Like mentioned on gitter, our async diagnostics doesn't listen to `ycm_show_diagnostic_ui`. Besides that diagnostics changing in …
> [READY] Stop async diagnostics from updating at inopportune times

- python/ycm/buffer.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
Hardcoding supported filetypes prooved to be error prone, as we have
forgot to add `go`, `rust` and in my fork `swift` to the set. Another
problem with hardcoded filetypes is the `GenericLSPCompleter` which can
provide diagnostics for arbitrary filetypes.
This PR does away with `DIAGNOSTIC_UI_ASYNC_FILETYPES`.
--- …
> [READY] Do not hardcode async diagnostic filetype support

- README.md
Using clangd as the C-family completion engine, the following
YcmCompleter subcommands are available:
Supported commands are:
ExecuteCommand
FixIt
Format
GetDoc
GetDocImprecise
GetType
GetTypeImprecise
GoTo
GoToDeclaration
GoToDefinition
GoToImprecise
GoToInclude
GoToReferences
RefactorRename
RestartServer
I've included the C-family languages in the list of supported languages
for each of these subcommands (where they were missing).
This change is needed to accurately reflect the features available for the C-family completion engine.
There are no tests because this PR only …
> Update README to reflect features available for the C-family languages

- azure-pipelines.yml
- azure/linux/install_dependencies.sh
Linuxbrew removed openssl 1.0. We have no choice but to use a newer python to link against openssl 1.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3543)
> [READY] Use openssl 1.1 and newer python 2

- README.md
- plugin/youcompleteme.vim
Fixes #3544 
When leaderf spawns its window as a popup (like YCM's signature help) it calls `execute()`. If a user also has `g:ycm_seed_identifiers_with_syntax == 1` then YCM calls [`:redir`](https://github.com/ycm-core/YouCompleteMe/blob/master/python/ycm/vimsupport.py#L201)  to collect [the keywords](https://github.com/ycm-core/YouCompleteMe/blob/master/python/ycm/syntax_parse.py#L72).
Vim apparently doesn't like executing `redir` within `execute()`.
[cont]: …
> [READY] Blacklist leaderf filetype

- python/ycm/youcompleteme.py
- test/signature_help.test.vim
- test/testdata/vim/mixed_filetype.vim
This PR enables signature help in mixed filetypes, like `vim.python`. The idea is, if `filetypes[i]` doesn't support `/signature_help`, see if the next one does. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3541)
> [READY] Signature help for mixed filetypes

- autoload/youcompleteme.vim
- azure-pipelines.yml
- python/ycm/signature_help.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
- test/signature_help.test.vim
Fixes #3549 
See comment : https://github.com/ycm-core/YouCompleteMe/issues/3549#issuecomment-559936332
Previously, when we called `RequestSignatureHelp` there were a number of reasons why we wouldn't send the request. In these cases, `SignatureHelpRequstReady` would always be false, so we'd poll it every 10ms forever, or until the timer was cancelled. Meanwhile, a separate bug meant that if the timer was already running and you keep typing, we would start more timers, without waiting for (or killing) the existing poll timer.
To solve the former: we return `False` from …
> [READY] Don't poll forever if signature help request isn't sent

- autoload/youcompleteme.vim
- python/ycm/signature_help.py
We *don't* want to enable 'filetype' in the popup - this actually leads
to YCM trying to parse the signature help buffer and various other
autocommands the we don't want. Just enabling the syntax allows for
Syntax autocommnds to even customise the display (I guess), but doesn't
have lots of lag like filetype setting.
In order to differentiate the current signature, we used to use
some text properties to mimic the completion popup. This doesn't work
with syntax highlighting (it overrides it), so we remove that and use
the syntax file's 'CursorLine' highlighting. This works nicely.
Note: There's a "cursorline" option to popup_open, but we don't want to
use that, as it actually uses 'PMenuSel', and is essentially designed
for poup menu-like things. We actually use PMenuSel for the current …
> Signature Help: Enable syntax highlighting in the popup

- python/ycm/client/messages_request.py
- python/ycm/tests/mock_utils.py
- python/ycm/tests/youcompleteme_test.py
- python/ycm/youcompleteme.py
- test/diagnostics.test.vim
This fixes a long standing bug that makes the message poll available only for a single filetype.
RFC because of the two `FIXME:` comments that should be discussed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3551)
> [READY] Poll messages for all visible filetypes

- .vimspector.json
- run_tests.py
Allows running our python tests under vimspector. 
I use this with these:
* [compiler plugin](https://github.com/puremourning/.vim-mac/blob/master/compiler/ycmd_test.vim)
* [ftplugin mappings](https://github.com/puremourning/.vim-mac/blob/5fb39207e3c0369a09509e2ec17d62dcee6ec9d4/ftplugin/python.vim#L122-L128)
Ultimately I just hit `<C-S-T>` to run the test under cursor in vimspector.
But in practice you can just press F5 and enter the full path to the file (or other nosetest arguments) when prompted.
[cont]: https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING …
> [READY] Vimspector: Allow running nose tests under vimspector

- autoload/youcompleteme.vim
It adds [wellle/context.vim](https://github.com/wellle/context.vim) to the filetype blacklist. This is useful because the buffer provided by context.vim isn't meant for editing. It also make the blacklist and whitelist handle buffers with multiple filetypes correctly.
I haven't included tests because I couldn't find existing tests for whitelists or blacklists.
--- …
> Handle multiple filetypes correctly when matching against whitelist/blacklist

- README.md
The proper way to structure the `ls` dictionary for RLS is somewhat obscure, so this PR adds a brief passage in the README explaining it. It also makes mention of needing to restart RLS in order for it to register changes to `Cargo.toml`, since having it register those changes automatically would require didChangeWatchedFiles support (see [ycm-core/ycmd#1296](https://github.com/ycm-core/ycmd/pull/1296)).
This doc change is motivated by a [Gitter …
> Add RLS config and usage information to README

- autoload/youcompleteme.vim
- test/docker/ci/image/Dockerfile
In some colour schemes, it's not appropriate to layer the syntax highlighting on the PMenu colours.
So in order to provide a highlight of the current argument that's guaranteed to have the right contrast, we just use inverse colours instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3589) …
> [READY] Use inverse video for current argument

- autoload/youcompleteme.vim
Fixes #3593
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3594)
> Revert sign_define() as it's in a later version of vim

- python/test_requirements.txt
- python/ycm/client/base_request.py
- python/ycm/youcompleteme.py
- test/diagnostics.test.vim
- test/lib/autoload/youcompleteme/test/setup.vim
- test/signature_help.test.vim
- test/testdata/vim/mixed_filetype.vim
The version of coverage required by covimerage is not compatible with
the current coverage version, so rather than downgrading it for our
python tests, we just use a different requirements file for vimscript
tests.
Fixes this error in CI:
> ERROR: covimerage 0.2.1 has requirement coverage<5.0a6, but you'll have coverage 5.0.3 which is incompatible.
Should also fix coverage data for vimscript
--- …
> [READY] Stabilise CI

- autoload/youcompleteme.vim
When we dumped python 2 and started using `:py3` instead of `call py3eval()` I left vimscript string concatenation operator (`.`) instead of changing it to python's (`+`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3605) …
> [READY] Fix concatenation operator

- python/ycm/buffer.py
For `foo.tsx` file, currently the diagnostics only arrive after `:YcmForceCompileAndDIagnostics`, because `typescriptreact` is missing from the `DIAGNOSTIC_UI_FILETYPES` set.
The vim level test is missing, mostly because I didn't feel like writing one. If you think I should write that test, I will. 
--- …
> [READY] Add typescriptreact to diagnostics enabled filetypes

- .vimspector.json
- autoload/youcompleteme.vim
- python/ycm/tests/youcompleteme_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
- test/commands.test.vim
Add range and mods to YcmToggleLogs
Range allows a custom height to be specified.
Mods allows things like :vertical YcmToggleLogs. This is most useful
when used with a range, like :vertical 90YcmToggleLogs. This simply
allows to open the logs in a vertical split which is useful for large
logs.
You can also :botright etc. See :help <mods>.
This is mostly useful with a user command: `command! YcmLogErr :botright vertical 75YcmToggleLogs ycmd*stderr*`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3647)
> [READY] Add mods and size to :YcmToggleLogs

- README.md
- autoload/youcompleteme.vim
- python/ycm/client/command_request.py
- python/ycm/youcompleteme.py
- test/commands.test.vim
- test/testdata/python/doc.py
This is useful for customistaions, and allows things like the
ExecuteCommand response to be used for things programmatically. An
example is to get the debugger port from `YcmCompleter ExecuteCommand
vscode.java.startDebugSession` as required by Vimspector.
Closes #3467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3654)
> [READY] Add public function to get the response from a subcommand

- autoload/youcompleteme.vim
- test/completion.common.vim
Close the completion menu (get out of ctrl-x mode) when the set of
completions we generate is empty. This gets the user out of ctrl-x mode
and allows insert-mode mappings to work again.
Fixing this caused a regression in the completedone handing, which
highlighted another issue: we were not correctly identifying
non-user-entered insert-mode changes during TextChangedP. We were
relying on CompleteDone, but this is triggered too late or not at all.
The only reliable way when tabbing though elements of the pum is the
CompleteChanged event, which when combined with the
v:event.completed_item key tells us that the change was due to a user
changing the pum selection.
Fixing the above resolved the regression in handling completion fixits
and allows us to close the pum at the right time, but …
> [READY] Close the completion menu when there are no candidates

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- plugin/youcompleteme.vim
- test/commands.test.vim
- test/hover.test.vim
- test/lib/autoload/youcompleteme/test/setup.vim
Add auto-hover behaviour (on by default)
This adds a hover feature, enabled by default on the CursorHold
autocommand (default: 4s), along with a <Plug> mapping to manually
trigger it.
We pick the subcommand to use based on preference order: GetHover,
GetDoc, GetType and remember the choice to avoid too many blocking
calls.
We enable syntax highlighting in the popup like in the signature help
popup, using the syntax of the current buffer. This isn't perfect
because some hover responses are markdown, though we tend to try and
hide that in our GetDoc and GetType. So we use `markdown` for GetHover
and `&syntax` for GetDoc/GetType.
Technically the response fromn the server is either plaintext or
markdown. We could actually use markdown.<current lang> in case that
gives better results with a …
> [READY] Add auto-hover behaviour (on by default)

- README.md
- autoload/youcompleteme.vim
- python/ycm/buffer.py
- python/ycm/tests/youcompleteme_test.py
- test/completion.common.vim
- test/diagnostics.test.vim
- test/docker/manual/image/Dockerfile
- test/docker/manual/run
- test/hover.test.vim
- test/lib/autoload/youcompleteme/test/setup.vim
- test/lib/run_test.vim
- test/signature_help.test.vim
1. improve the syntax detection
We use this heuristic:
* For GetHover - use markdown
* For GetDoc - use nothing
* For GetType - use the current file syntax
You can also (undocumentedly) set b:ycm_hover to a dict with 'command'
and 'syntax' keys to manually override this if you so choose.
This also improves the tests - they now mock the python layer so that we
actually test the vimscript properly and cover the different cases.
Fixes #3667 
--- 
2. improve the popup display/hide mechanics:
* close the popup on 'word' rather than the default 'WORD' cursor movement.
* allow user more control by making the mapping a toggle
Incidentally, I found that the tests were garbage, and were never actually triggering the mapping (fixed by using `nmap` not `nnoremap`) and that there is a simple way to …
> [READY] Slightly improve the syntax heuristic for hover

- README.md
- doc/youcompleteme.txt
- test/hover.test.vim
- test/lib/autoload/youcompleteme/test/popup.vim
- test/signature_help.test.vim
It seems there is some controversy about what the best option is for a given filetype. We had some heuristics by default, but actually i think it's reasonable to allow customisation of this and to document that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3671)
> [READY] Document and test manual popup configuration

- autoload/youcompleteme.vim
rationale for why I haven't. [Didn't include tests, have rationale below]
The behavior used to be `'close': 'button'` which shows an 'X' in the top right of the popup. It's some times not clear that the 'X' is a button. The popup disappears when the cursor moves and the hover command now has toggle behavior so it seems less necessary. This new `'close': 'click'` behavior removes this button, but still closes the popup when clicking anywhere in the popup, so the mouse can still be used.
The change seems trivial so I didn't include any tests. 🤔
[cont]: …
> Use `'close': 'click'` behavior for hover popups

- autoload/youcompleteme.vim
- test/hover.test.vim
- test/testdata/python/doc.py
Previously we relied on popup_atcursor to display the popup in a
sensible place. However, by default 'wrap' is enabled, which prevents
vim from shifting the popup to the left to show it on the screen (even
if you set minwidth). As a result it was possible for the popup to
display a very small vertical section when triggered close to the
right-hand screen edge.
The solution is to enable wrapping, which lets vim shift the popup. The
edge-case is that we _do_ want wrapping if there are lines that are
likely to be wrapped. Therefore in that case (when any line is > some
maximum width), we just force the popup to be placed at column 1 and
enable wrapping.
The maximum width for this wrapping is calculated as the screen width in
columns minus the padding we add in the x-axis. THis is a bit hacky …
> [READY] Maximise displayed text for hover popup

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/client/completion_request.py
- python/ycm/tests/client/completion_request_test.py
- python/ycm/tests/test_utils.py
- python/ycm/vimsupport.py
Fixes #3547
Per discussion in #3547 the popup used when 'popup' is included in completeopt does not get to specify a minimum width, so for languages with verbose signatures like Typescript, the extra information (IE: documentation) that should be viewable there gets very squished and hard to read.
By introducing this simple heuristic, created by @puremourning, of allowing the extra_menu_info to have no more than ~1/3rd of the screen's width in length, we are left with ~1/3rd of the screen for the actual …
> Truncate extra_menu_info when completeopt is in popup mode

- README.md
The ListToggle link assumed that the code was hosted in Valloric's github. The code has moved elsewhere therefor the link has broken.
This change is a documentation change. I've tested the new link works manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3715)
> Readme: Fix ListToggle Link

- README.md
The `ls` key tells YCM that the dictionary should be passed to **thet** LSP server. For each of the LSP server's configuration you should look up the respective server's documentation.
The `ls` key tells YCM that the dictionary should be passed to **the** LSP server. For each of the LSP server's configuration you should look up the respective server's documentation.
--- …
> Typo fix for README.md - LSP Configuration section

- azure/linux/install_dependencies.sh
- azure/run_tests.sh
- azure/send_coverage.sh
Just like it was for ycmd, linux CI is currently borked because of linuxbrew.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3733)
> [READY] Drop linuxbrew

- README.md
- autoload/youcompleteme.vim
- python/ycm/client/command_request.py
- python/ycm/youcompleteme.py
- run_tests.py
- test/hover.test.vim
- test/lib/run_test.vim
The hover request is enabled by default on CursorHold. It's not uncommon
for &updatetime to be set to a small value for other plugings that
update on CursorHold (even YCM used to do this).
However, previously the Hover request was _blocking_. This meant that on
a fairly large codebase, by default YCM could block Vim for many seconds
particularly on startup.
This is YCM anathema, and a big error. Therfore, as it's not easy to
unwind the "enabled by default" decision, a better resolution is to make
the request asynchronous.
This change introduces a `youcompleteme#GetCommandResponseAsync` with
the same behaviour as `youcompleteme#GetCommandResponse` but taking a
callback to handle the result. This is in turn used by the YCMHover
mapping and autocommand.
--- …
> [READY] Make hover request async

- autoload/youcompleteme.vim
- test/filesize.test.vim
Previously, this was providing a false negatives. Now,
if the filetype is not approved, we immediately return
without trying to finish opening it.
Signed-off-by: Kevin Morris <kevr.gtalk@gmail.com>
This PR/Commit chain is made to satisfy https://github.com/ycm-core/YouCompleteMe/issues/3463. Currently, the test works, however I'd like to generate the files from inside of the test and reload YCM when the buffer is filled up. I've tried quite a few different things, but I'm a bit lost as to how to do it. Any advice would be greatly appreciated.
PS: There are some formatting issues in this commit; I'll patch it up shortly, just wanted to get this PR in here to get some eyes on it.
--- …
> don't check file size in unsupported filetypes

- README.md
rationale for why I haven't.: **README update only**
I bumped into this today, pretty hard. My filter was:
```
let g:ycm_filter_diagnostics = {
\ "cpp": {
\      "regex": [ ".*\[-Wunknown-warning-option\].*"],
\      "level": "error",
\    }
\ }
```
And none of the errors would pop up due to the use of "level": "error" which I assumed would do: 
```
for all diagnostics:
if level == "error":
if re.match(regex):
hide
```
Whereas  it actually does:    
```
for all diagnostics:
if re.search(regex):
hide
if level == "error": 
hide
```
My filter ended up:
```
let g:ycm_filter_diagnostics = {
\ "cpp": {
\      "regex": [ "-Wunknown-warning-option"],
\    }
\ }
```
[code]: …
> Clarifications for ycm_filter_diagnostics in README

- .vimspector.json
- README.md
- autoload/youcompleteme.vim
- azure-pipelines.yml
- plugin/youcompleteme.vim
- python/ycm/base.py
- python/ycm/client/completion_request.py
- python/ycm/client/resolve_completion_request.py
- python/ycm/tests/client/completion_request_test.py
- python/ycm/tests/completion_test.py
- python/ycm/youcompleteme.py
- test/completion.common.vim
- test/completion.test.vim
- test/completion_info.test.vim
- test/completion_noresolve.test.vim
- test/docker/ci/image/Dockerfile
- test/fixit.test.vim
- test/lib/plugin/shared.vim
- test/lib/run_test.vim
- test/run_vim_tests
This goes with https://github.com/ycm-core/ycmd/pull/1473
In the client, the implementation is a bit fiddly, but boils down to this section of the vim help:
```
*complete-popuphidden*
If the information for the popup is obtained asynchronously, use "popuphidden"
in 'completeopt'.  The info popup will then be initially hidden and
|popup_show()| must be called once it has been filled with the info.  This can
be done with a |CompleteChanged| autocommand, something like this: >
set completeopt+=popuphidden
au CompleteChanged * call UpdateCompleteInfo()
func UpdateCompleteInfo()
" Cancel any pending info fetch
let item = v:event.completed_item
" Start fetching info for the item then call ShowCompleteInfo(info)
endfunc
func ShowCompleteInfo(info)
let id = popup_findinfo()
if id
call …
```
> [READY] Resolve completion item detailed_info on demand (where possible)

- autoload/youcompleteme.vim
- python/ycm/vimsupport.py
- test/completion.common.vim
- test/completion_info.test.vim
- test/filesize.test.vim
Introduce "fake" filetype `ycm_nofiletype` that is used to handle all
buffers without filetype.
closes #3776
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3777)
> [READY] Allow completion on a buffer without filetype

- test/README.md
* fix "plguin" 
* fix `***NOT**` -- in vim markdown it spans for the rest of the file making it bold_italic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3778)
> Fix typos in test/README

- python/ycm/client/resolve_completion_request.py
- python/ycm/tests/test_utils.py
- python/ycm/vimsupport.py
- Swallow TypeError when omnicompleter puts garbage in item["user_data"]
- Highlight diagnostics with low priority, to allow hlsearch to work
One commit stops an ugly backtrace when OmniCompleter encounters garbage (dict)
in the completion item's `user_data` on completion resolve request.
The other makes diagnostic highlighting play nicer with `hlsearch`.
No tests, because I have no idea how to test either of these.
[code]: …
> [READY] Two tiny fixes

- .vimspector.json
- python/ycm/tests/test_utils.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Upstreaming this because it's useful. I use a lot of commands that run tests and things and the output goes to the QuickFix window. I like this to be vertical for some things. However, YCM's resizing messes up the window layout even if you override it with the autocmd. This is a tiny change to allow YCM to not resise the QuickFix window.
---
This allows the quickfix to be made vertical, with
au FileType qf let b:ycm_no_resize = 1 <bar> wincmd L
Using the YcmQuickFixOpened/YcmLocationOpened can work (with wincmd _),
but this messes up the layout of split windows, e.g.:
:au User YcmQuickFixOpened wincmd _
:split
:YcmCOmpleter GoToSymbol User
This breaks the layout of the 2 splits (as YCM first resizes the
quickfix window with its own command, thust increasing cmdheight to
&lines - <new …
> [READY] Allow suppressing the quickfix height changes

- README.md
- autoload/youcompleteme.vim
- plugin/youcompleteme.vim
- test/.vimspector.json
- test/commands.test.vim
- test/completion.common.vim
- test/completion.test.vim
- test/completion_info.test.vim
- test/completion_noresolve.test.vim
- test/diagnostics.test.vim
- test/filesize.test.vim
- test/fixit.test.vim
- test/hover.test.vim
- test/lib/autoload/youcompleteme/test/setup.vim
- test/lib/plugin/completion.vim
- test/lib/plugin/util.vim
- test/lib/run_test.vim
- test/signature_help.test.vim
- test/testdata/cpp/complete_with_sig_help.cc
When we made YCM parse buffers with no filetype, this ended up including
the buffers within things like popups. Unfortuantely this leads to a
problem that we call "ClearSignatureHelp" from within
"FileReadyToParse". If the "FileReadyToParse" in question was within a
popup, we ge an error "Not valid in popup window" (referring to a call
to popup_close()) and vim gets in a very bad state.
it's not obvious how to solve this in the general case, but for now as
completion in non-filetype buffers is new and rare, we Blacklist enpty
buffers by default to work around the bug.
We allow users to explicitly enable it (and suffer this bug!) by
explicitly whiteliisting it again in ycm_filetype_whitelist.
Added a test which shows that it works when ycm_nofiletyp is
blacklisted, and another test which …
> [READY] Fix signature help traceback when using preview popup

- .mergify.yml
Smart mode sometimes leads to queues of PRs. Our CI time isn't really that much of a problem, particularly on this repo, so switch to simple strict mode, rather than smart strict mode:
the difference:
* Simple: The pull request will be merged only once up-to-date with its base branch. When multiple pull requests are ready to be merged, they will all be updated with their base branch at the same time, and the first ready to be merged will be merged; the remaining pull request will be updated once again.
* smart: enables Strict Merge but only update one pull request against its base branch at a time. This allows you to e.g., save CI time, as Mergify will queue the mergeable pull requests and update them serially, one at a time
--- …
> Disable mergify smart mode; just let it keep trying

- README.md
- doc/youcompleteme.txt
The :help pages and README claimed that rust-analyzer supports the
'ExecuteCommand <args>' subcommand, though this is not the case.
Fixes #3796 .
The previous docs were misleading / incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3797)
> Remove claims of 'ExecuteCommand' support for Rust

- README.md
The reason is that jdt.ls was having issues when using the Groovy
language instead (Windows machine). Autocomplete was not working at all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3812)
> Add message to use Kotlin language for build.gradle

- autoload/youcompleteme.vim
Use `default` for `:highlight`. 
Having it users would be able redefine highlight groups, also colorscheme change would not clear them.
Relates to https://github.com/vim/vim/pull/6970#issuecomment-745837815
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3827)
> fix: make highlighting work for new vim

- python/ycm/buffer.py
- python/ycm/youcompleteme.py
- test/diagnostics.test.vim
Previously it was possible for the following scenario to happen:
1. Async message: `[diags]`
2. Async message: `[]`
3. FileReadyToParse: `[diags]`
In this case, YCM would show stale diagnostics that don't correspond to
the current state of the buffer any more.
No tests because... how do I test a race condition?
--- …
> [READY] Avoid a race condition between async diagnostics and FileReadyToParse

- python/ycm/client/command_request.py
@Aster89 showed that we're not handling `None` in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3847)
> [READY] Handle None response in case of error

- python/ycm/client/resolve_completion_request.py
- test/completion.common.vim
- test/completion_info.test.vim
- test/lib/plugin/completion.vim
- test/signature_help.test.vim
When we resolve completion items on-demand, we re-use the latest
completion request object to do the resolve request. This not only makes
sure that we only have one such request outstanding, but also that the
original request data items and query never change (as required by the
ycmd protocol).
The problem with this is that the complete done handling is implemented
by the CompletionRequest object. If we do a resolve, then we have lost
the completion request object to do the complete done handling. So to
resolve this we just delegate that handling back to the original
completion request when the latest "completion" request is actually a
resolve request.
the brackets) _before_ …
> [READY] Fix auto imports when resolving completions on-demand

- README.md
- doc/youcompleteme.txt
Changed Visual studio Build Tools version from 2017 to 2019, since
this (2017) gave me an (well known) error. Now I know of --msvc,
but this way is more natural and intuitive for unexperienced
YouCompleteMe users like me. But I am not the only one as the issue
https://github.com/ycm-core/YouCompleteMe/issues/3472 shows.
You can see comments in code of this commit (below (If I understand github correctly)).
The main rationale is that if you follow the simple instructions in README.md, you will get an …
> [DOC] Updated Windows installation sect in README.

- .github/workflows/ci.yml
- README.md
- autoload/youcompleteme.vim
- autoload/youcompleteme/finder.vim
- plugin/youcompleteme.vim
- python/ycm/client/command_request.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
- test/.vimspector.json
- test/docker/ci/image/Dockerfile
- test/finder.test.vim
- test/hover.test.vim
- test/lib/autoload/youcompleteme/test/commands.vim
- test/lib/run_test.vim
Demo: 
[![asciicast](https://asciinema.org/a/4JmYLAaz5hOHbZDD0hbsQpY8C.svg)](https://asciinema.org/a/4JmYLAaz5hOHbZDD0hbsQpY8C)
Basic idea is to provide "GoToSymbol" and "GoToDocumentOutline" using a "narrow-down-while-typing" approach similar to the insert completion popup.
To enable:
* `nmap <something> <Plug>(YCMFindSymbolInWorkspace)`
* `nmap <something> <Plug>(YCMFindSymbolInDocument)`
e.g.
* `nmap <leader>yfw <Plug>(YCMFindSymbolInWorkspace)`
* `nmap <leader>yfd <Plug>(YCMFindSymbolInDocument)`
Currently:
- "Workspace" search (GoToSymbol) relies on the _server_ (i.e. the LSP server) doing the filtering of the query. This is because none of the LSP servers I tested would return anything with query = ''. Therefore we can't easily use YCM's "filter and sort candidates" which would be …
> [READY] Interactive symbol search

- autoload/youcompleteme/finder.vim
- test/finder.test.vim
Disable completion in the finder popup fixes #3879 
Also, catch errors sending the request and just silently fail (rather than traceback)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3880)
> Symbol popup: Disable completion in the prompt buffer.

- .github/workflows/lock_old_issues.yaml
- CONTRIBUTING.md
This locks issues which are:
- issues, not PRs
- closed
- not updated in last 60 days.
Runs once a day at around midnight (in some timezone, shrug). Can be run manually.
Code for the action:
https://github.com/dessant/lock-threads/blob/master/src/index.js
Settings for the action:
https://github.com/dessant/lock-threads#inputs
Things we might want to do:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3884)
> Lock closed issues older than 60 days

- autoload/youcompleteme/finder.vim
We don't catch all keys, so this is largely the correct thing to do
Fixes #3881
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3885)
> Enable mappings with popup visible.

- python/ycm/signature_help.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Python, since 3.2, provides [`@lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache), which is more flexible than our `@memoize`. We don't really need the extra features.
https://github.com/python/cpython/blob/main/Lib/functools.py#L479-L644
Considering the complexity, I'm not sure we want `@lru_cache` instead of our own version. For a trivial function, the retrieval from the cache was done in ~100us. …
> Use the standard library for memoizing return values

- python/ycm/diagnostic_interface.py
- python/ycm/tests/diagnostic_interface_test.py
- python/ycm/vimsupport.py
Before the big diagnostics refactor, we only served diagnostics for the
current buffer. That allowed `vimsupport.LineAndColumnNumbersClamped()`
to assume `vim.current.buffer` was always correct.
That is no longer the case - we were clamping offsets to, potentially,
the contents of a wrong buffer. More specifically, if
1. Current buffer is not the same buffer we are updating diagnostics
for.
2. Current buffer does not have line number of the target buffer
diagnostics.
Then we end up wrongfully "moving" the line of the diagnostic. On top of
that, if the target buffer's …
> [READY] Do not assume current buffer in vimsupport.LineAndColumnNumbersClamped()

- python/ycm/tests/test_utils.py
- python/ycm/vimsupport.py
- test/diagnostics.test.vim
`vimsupport.GetTextProperties()` goes over all the properties in a
buffer. Then it filters for those whose type starts with `Ycm`.
However, if a plugin ever deletes its property type but leaves around a
property of that type, `prop_list()` will not contain the property type
for that property. This is where we previously encounter a rather nasty
`KeyError`.
I really wish vim had a nicer API for listing properties.
This bug was reported by @roachsinai on gitter.
[cont]: …
> [READY] Avoid KeyError when a different plugin's property type gets deleted

- autoload/youcompleteme.vim
This change does away with s:UpdateMatches(), for the sake of
performance in large files.
Previously, we would still try to update diagnostics in large files,
which would result in YCM calling a vim API for every line in that large
file.
The obvious solution - just call `s:AllowedToCompleteInCurrentBuffer()`
in `s:UpdateMatches()` - doesn't work, because it make
`s:OnBufferEnter()` return early as well, because
`s:VisitedBufferRequiresReparse() == false`. That makes
`s:OnBufferEnter()` skip the rest of the setup of completion.
Yes, this means that vimscript API for getting …
> [READY] Move ycm_state.UpdateMatches() to s:OnBufferEnter()

- autoload/youcompleteme.vim
This can happen if there's another async plugin that can change cursor
position, like matchup. In that case, it's a race condition between YCM
completing correctly and the plugin movin the cursor some place else.
The workaround here is to make sure the cursor position at request is
the same as cursor position at `complete()` time. As a result:
1. Erratic cursor movement won't mess up the buffer content and get in
the way of typing.
2. Occasionally, YCM won't call `complete()` in a situation where a user
might expect it to, but that's a direct consequence of `1`.
3. YCM …
> [RFC] Do not call complete() if the cursor changed position since the completion request

- README.md
- vimrc_ycm_minimal
YCM works find on arm64 Macs, but the bundled clangd/libclang don't work.
At present, there is no Homebrew bottle for mono either, so we recommend using mono-project + rosetta (confirmed this works)
closes #3947 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3971)
> Document setup on arm macs

- python/ycm/tests/test_utils.py
- python/ycm/vimsupport.py
This greatly improves the performance of `vimsupport.GetTextProperties()`, assuming vim is at least 8.2.3652.
Should I update vim in our docker, so that we run tests on this branch as well?
--- …
> [READY] When available use the faster prop_list API

- README.md
Option `signcolumn` has no `off` argument
Proper way to not draw `signcolumn` is `set signcolumn=no`
Reproduced with vim 8.2.3700
Testing is not required, this PR changes only README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3981)
> docs: clarify vim option

- autoload/youcompleteme.vim
- test/completion.common.vim
Pull request #3953 introduced cursor tracking via
s:current_cursor_position, which used to be set on `TextChangedI` and
`CursorMovedI`.
If neither of those events happen and YCM attempts completion, a user
would see a vim stack trace.
This is possible if forcing semantic completion immediately after
entering insert mode. To fix this, we also set
`s:current_cursor_position` on `InsertEnter`.
[code]: …
> [READY] Do not error when trying to complete without typing any characters

- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
no new test, but updated vimsupport_test.py to match updated vimsupport.py
I work with large code files with folding enabled (I suppose this is quite common settings for vim users), when using YCM GoTo to jump around the code, I need to press zv every time when jumping in middle of a closed folding. Similar behavior in Vim Termdebug has been reported and patched.
--- …
> Auto open possible folding when jumping to a location

- README.md
Installation instructions for macOS recommend to install and link Java via Homebrew with the following commands:
```
$ brew install java
$ sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
```
However, on my new computer, Homebrew installs `java` into `/opt/homebrew/opt/openjdk` instead of `/usr/local/opt/openjdk`.
I don't know the reason for the path change. Probably it is due to the OS changes, as I have Homebrew 3.3.9 on macOS Catalina and Monterey with different paths.
Anyway, the PR changes `/usr/local/opt/openjdk` …
> Generalize path to Homebrew-installed java on macOS

- .vimspector.json
- python/ycm/diagnostic_interface.py
- python/ycm/tests/diagnostic_interface_test.py
SOmetimes, for some reason, the legacy libclang completer returns ranges
where the end of the diagnostic range is 0,0 (or otherwise invalid).
It's not clear why that is, but it's coming from libclang and there's
not much we can do about it.
ANyway in the past we would have just crated a diagnostic "match" that
would have never matched anything. Now, we're trying to create a text
property spanning that range, which causes a vim error and ugly
traceback.
Solution is to simply validate ranges and drop invalid ones.
Fixes #4013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4014)
> Fix traceback with invalid diagnostic ranges

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/signature_help.py
- python/ycm/youcompleteme.py
- test/lib/autoload/youcompleteme/test/popup.vim
- test/signature_help.test.vim
The signature help is awesome when you need it, but can get in the way,
when one needs to see the line above cursor.
With this commit, and an additional binding, it is possible to
temporarily hide the popup.
One caveat is that, if there were no popup to begin with and user starts
to edit arguments somewhere between triggers, the user won't be able to
spawn a popup with this binding.
As for the tests... I don't think there's an API for "is this popup visible", akin to `pumvisible()`.
[cont]: …
> Implement manual toggling of signature help popup visibility

- python/ycm/youcompleteme.py
- [] I have included tests for the changes in my PR. If not, I have included a
The tagfiles specified (loaded) in vim may already be abspath, join them directly will lead to tagfiles not loaded.
(In my own settings, I used abspath for tag files and ID from tagfiles were not shown by YCM) 
--- …
> tagfiles may already be abspath

- README.md
- autoload/youcompleteme.vim
- python/ycm/buffer.py
- python/ycm/client/semantic_tokens_request.py
- python/ycm/diagnostic_interface.py
- python/ycm/semantic_highlighting.py
- python/ycm/vimsupport.py
There's a `g:ycm_enable_semantic_highlighting` and `b:ycm_enable_semantic_highlighting` that can be set to 1.
Vim only, no neovim.
experimental, unsupported and undocumented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4033)
> Support for semantic highlighting (experimental)

- README.md
- autoload/youcompleteme.vim
- autoload/youcompleteme/filetypes.vim
- autoload/youcompleteme/finder.vim
- python/ycm/client/command_request.py
- python/ycm/tests/command_test.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
- test/finder.test.vim
- test/lib/autoload/youcompleteme/test/commands.vim
Sorry this is a pretty big PR. May help to review by commits, as the earlier commits make the underlying changes, and the later commits implement the functional changes.
I frequently found myself wanting to query any part of my current "workspace" irrespective of current context.
In particular, my mental model was of using a "C++ project" but if my cursor was in a config file or script, then the symbol search just wouldn't work.  As I said on GItter:
> This is the kind of thing where we want it to feel intuitive. In my case about 8/10 times I was working in a c++ project but had say a config file or script open in the current buffer. My “mental model” was that I was working in c++ but I actually was working in, say, TCL at that moment.
So instead we query for each open filetype for which …
> Context Free Symbol search: query all open filetypes and merge results

- autoload/youcompleteme.vim
For some reason, the (wierd) way we were initialising
s:enable_inlay_hints via vim.command was causing wierdness on older vims
and neovim (i.e. where it was returning 0). Unclear why this was
happening, but using less wierd syntax seems to fix it.
Fixes #4051
Fixes #4052
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4053)
> Fix passing '+10' etc on command line in older vims.

- autoload/youcompleteme/finder.vim
If a candidate shown in the symbol finder is too long to display the
path and line number, we would incorrectly calculate the length of the
path text property. Calculate it correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4054)
> Fix traceback when a long identifier is displayed in finder

- README.md
- autoload/youcompleteme.vim
- python/ycm/tests/test_utils.py
- python/ycm/vimsupport.py
- test/completion.common.vim
- vimrc_ycm_minimal
Fixes #3919
```
Provide a way to manually trigger YCM's completions
When automatic triggering is disabled, we now set the completefunc, so
the user can use C-x C-u. We also provide a plug mapping that does the
completion as users may not be comfortable with c-x c-u.
As this is a very unusual use-case for YCM we sweep under the rug that
most users probably want to use <Tab> for both completion and "next". Or
perhaps want to use C-p in the same way. For now a unique mapping works.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4097)
>     Provide a way to manually trigger YCM's completions

- autoload/youcompleteme.vim
- python/ycm/buffer.py
- python/ycm/diagnostic_interface.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
When g:ycm_update_diagnostics_in_insert_mode is disabled (i.e. `0`) clear the diagnostics when _entering_ insert mode.
This makes editing much smoother when there are a lot of diags and is much less annoying particularly when using things like virtual text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4117)
> Hide diags in insert mode

- python/ycm/client/command_request.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
This fixes the behavour of GoToAlternate file to keep the buffer's cursor position.
cc @klew
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4118)
> Don't change the cursor position if GoTo doesnt have one

- .github/workflows/ci.yml
Our records indicate that some of your organization’s workflow files are still referencing the macos-10.15 runner image. This image has been fully unsupported since 2022-12-01 and will be completely removed by 2023-03-31.
What you need to do
Workflows using the macos-10.15 YAML workflow label should be updated to macos-latest, macos-12, or macos-11. You can always get up-to-date information on our tools by reading about the [software](https://app.github.media/e/er?s=88570519&lid=3455&elqTrackId=20a1f0dfddfb4f279a143758449644bb&elq=80ef062d847e4addbbafffe8e5e487cb&elqaid=3113&elqat=1) in GitHub Actions runner images. Please contact [GitHub Support](https://app.github.media/e/er?s=88570519&lid=3338&elqTrackId=109f1ab4edb9447baf91e5e0d5dcb9c1&elq=80ef062d847e4addbbafffe8e5e487cb&elqaid=3113&e …
> Use macOS 12 in CI

- autoload/youcompleteme.vim
- python/ycm/buffer.py
- python/ycm/inlay_hints.py
- python/ycm/scrolling_range.py
- python/ycm/semantic_highlighting.py
- test/completion.test.vim
- test/completion_info.test.vim
- test/completion_noresolve.test.vim
- test/diagnostics.test.vim
- test/finder.test.vim
- test/hover.test.vim
- test/testdata/cpp/finder_test.cc
Minimise overdraw and over-request for semantic tokens.
Share the scrolling window implementation with inlay hints which was already a bit better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4150)
> Semantic highlighting optimisation

- README.md
- python/ycm/client/command_request.py
- python/ycm/tests/client/command_request_test.py
- python/ycm/tests/vimsupport_test.py
- python/ycm/vimsupport.py
Apply mods to the pedit command.
Fixes #4152
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4155)
> Accept command modifiers (mods) for GetDoc subcommand

- python/ycm/semantic_highlighting.py
We were supposed to allow users to set highlight groups for any token types that we don't understand, as servers can basically return anything they like. This didn't work and we just always complained about it.
Now we trap the "text property type doesn't exist" error and warn then. This allows users to specify the missing ones to stfu the error. Also improved the message to point to the help.
closes #4161
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4164)
> Fix custom text properties for semantic highlighting

- README.md
- python/ycm/signature_help.py
Fixes #4153
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4157)
> Add option to disable signature help syntax highlights

- doc/youcompleteme.txt
Update the vim docs after recent changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4173)
> [Auto] Update vim docs

- README.md
- autoload/youcompleteme.vim
- doc/youcompleteme.txt
- python/ycm/youcompleteme.py
This seems to work, but I have a few questions
- What tests should I look at to understand how to write one for this change?
- Are you happy with the name `YcmErrorPopup`?
- What should I set as `'priority'`, `'combine'`, `'override'`?
See #4165 and [conversation on gitter](https://matrix.to/#/!wwhJRinEmBFNyyXmut:gitter.im/$g19MXPpDc-cOYFxt_27sZ-nigpQRuBYUa_DbJ0RlqBA?via=gitter.im&via=matrix.org&via=matrix.freyachat.eu).
[code]: https://github.com/ycm-core/YouCompleteMe/blob/master/CODE_OF_CONDUCT …
> Address #4165: provide a highlight group for the detailed diagnostic popup

- .github/workflows/ci.yml
This silences thet GHA warning, similar to the changes in ycmd.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4186)
> Update setup-java action

- README.md
- doc/youcompleteme.txt
- test/docker/ci/image/Dockerfile
- test/fixit.test.vim
- test/hover.test.vim
- test/signature_help.test.vim
Mostly completer upgrades, and we are now python 3.12 ready.
Now we are python 3.12 ready. For a more detailed look into the diff:
```
e755af6fd Merge pull request #1712 from bstaletic/py312-bugs
ed6a49abf Merge pull request #1710 from bstaletic/llvm-17
3a88cf39d Merge pull request #1706 from bstaletic/go_cleanup
cff0e09f8 Merge pull request #1707 from bstaletic/empty_truthy_thingy
18b4d4946 Merge pull request #1709 from bstaletic/cicici
611920821 Merge pull request #1708 from bstaletic/more-ci-fixes
95fec7784 Merge pull request #1705 from bstaletic/no-bidi-chars
7d5ef4c7e …
```
> Update to new ycmd

- python/ycm/scrolling_range.py
- python/ycm/vimsupport.py
First and more common error is that by the time we execute
buffer = vim.buffers[ bufnr ]
the buffer might not be there any more. This is because `RangeVisibleInBuffer()` is called asynchronously and the user may bwipeout a buffer in between polls.
This regularly happens in our vim tests. In such a case, we get a nasty traceback from `vimsupport` module.
The solution is to catch the KeyError and return None.
However, `ScrollingBufferRange()` also was not ready to handle None values from `RangeVisibleInBuffer()`, even though `RangeVisibleInBuffer()` could return None even …
> Handle possible errors from RangeVisibleInBuffer()

- python/ycm/diagnostic_interface.py
- python/ycm/youcompleteme.py
- test/diagnostics.test.vim
This PR fixes two diagnostic bugs, makes one harder to solve and leaves one for later:
1. Diagnostic echo on enter if echoing virtual-text when asked not to. - Fixed
2. No diagnostic refresh if leaving insert mode after a semantic trigger. - Fixed
3. Echo flicker on insert leave. - Harder to fix. Previously caused only by `CursorMoved`, now by `InsertLeave` too.
4. Sign column bounce - still thinking about the best way to fix it.
I have tried fixing number 3, but all I could come up with were some heuristics which were always wrong in some case...
Are these changes still …
> Diagnostics fixes - hopefully only the non-controversial parts

- README.md
- python/ycm/semantic_highlighting.py
- test/diagnostics.test.vim
- test/lib/autoload/youcompleteme/test/popup.vim
Adds instructions for using YCM with .NET 6.0 and newer, as it is currently not supported out of the box and configuring it has difficult to diagnose gotchas. Switching defaults to .NET 6.0 version of OmniSharp-Roslyn for out-of-the-box support [breaks a bunch of tests in `ycmd`](https://github.com/ycm-core/ycmd/pull/1659), lacking resources to fix.
Removal of necessisity for solution files is possible, but requires …
> Add instructions for use with .NET 6.0

- autoload/youcompleteme.vim
- test/completion_info.test.vim
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4208)
> Make switching to semantic completer work after select ID completer candidate

- autoload/youcompleteme/finder.vim
Previously len( desc ) and len( path ) counted bytes, which was wrong for non-ascii characters. A string like `čđš` should have the length of 3 when calculating the number of spaces between the identifier and the file path.
That brings us to choosing the right string length function. The choices are:
- strcharlen - counts characters. `čđš` is 3, `čđ\tš` is 4. Not sure what happens in the face of zero width joiners.
- strdisplaywidth - counts character width on screen. `čđš` is 3 and `čđ\tš` is 9 (assuming `tabstop` is 8).
Tabs do not appear in identifier names, but double …
> Fix display of special characters in finder popups

- python/ycm/vimsupport.py
- test/diagnostics.test.vim
Previously, we have always used the diagnostics start column of the *starting* line of a multiline diagnostic. This is wrong, as the starting column for a line in the middle of a multiline diagnostic is always 1.
Previous patch just happens to work if the start column of the first line of the diagnostic is also 1.
Fixes #4196
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [READY] Take care of start column in multiline diags for detailed diag popups

- python/ycm/youcompleteme.py
- test/diagnostics.test.vim
If a line for which detailed diagnostics are requested contains more than a single diagnostic with the same message, YCM will try `options.pop( 'col' )` more than once.
We do not need to really iterate through the diagnostics once we have found the first one that is a match. If there's only one diag with the matching message, looping beyond that diagnostic is just a waste of time. If there's multiple diagnostics with the same message, it does not matter which one we display in the popup.
Hence, the added break at the end of the loop.
[cont]: …
> [READY] Handle multiple identical diagnostics in YcmShowDetailedDiagnostic popup

- autoload/youcompleteme.vim
While this is quite a minor change, I feel that it helps with the readability and flow of the source code for people first familiarizing themselves with it (and/or people coming back to it after a while).
I did not include tests since only comments were modified.
- - - …
> Correct a few typos in comments

- autoload/youcompleteme.vim
There are two kinds of scrolling that need to be handled:
1. Scrolling the buffer in a window shifts the buffer, but popups stay in place. Instead, we close the popup whenever we receive a WinScrolled event.
2. Scrolling the popup contents themselves resets the `updatetime` timer and can trigger a second `CursorHold` event, which leads to YCM resetting the hover popup. Instead, only re-display the hover popup if it is not already visible.
Open questions:
- Should we close other popups after `WinScrolled`?
- Tests... How do we even test "do X if mouse pointer at (x, y) …
> [READY] Handle scrolling when hover popup is open

- test/fixit.test.vim
The ycmd update that was pushed a moment ago has broken a single vim level test - JDT once again reordered some fixits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4222)
> [READY] Fix tests after ycmd update

- README.md
Fixes extra backtick in README.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4225)
> Remove extra backtick

- README.md
- autoload/youcompleteme.vim
- autoload/youcompleteme/finder.vim
- autoload/youcompleteme/hierarchy.vim
- autoload/youcompleteme/symbol.vim
- python/ycm/client/base_request.py
- python/ycm/client/command_request.py
- python/ycm/hierarchy_tree.py
- python/ycm/tests/command_test.py
- python/ycm/tests/test_utils.py
- python/ycm/vimsupport.py
- python/ycm/youcompleteme.py
- test/hierarchies.test.vim
- test/hover.test.vim
- test/testdata/cpp/hierarchies.cc
This is the client side pull request related to ycm-core/ycmd#1733
Again, tests and documentations are missing.  Documentation is the easy part, but tests would be dreadful...
I have not paid much attention to the look of the popup.
The look is slightly off - for deep hierarchies  the location of references in the file (`foo.cpp:8` for example) becomes misaligned.
The context is is not right aligned either.
Basically, it's functional but ugly. If someone would be up for it, please send patches my way.
The only publicly available function here is …
> [READY] Implement type/call hierarchy handling

- python/ycm/hierarchy_tree.py
The usage of walrus operator makes ycm unavailable for Python version under 3.8, which is inconsistent with the requirements in install.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4244)
> remove usage of walrus operator

- .github/workflows/ci.yml
- .mergify.yml
This is similar to ycm-core/ycmd#1746
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4240)
> [READY] Update CI config

- python/ycm/semantic_highlighting.py
The `decorator` type was introduced in LSP 1.17.
The `concept` type is used by clangd.
Reported by @amosnier on gitter.
The mapped value is just the first thing that came to my mind. Feel free to suggest bette alternatives.
- - - …
> Add new semantic token types

- README.md
The given repository is no longer needed to install the specified packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4229)
> Removed unnecessary repository.

- autoload/youcompleteme.vim
Since vim 9.1.0469, completeopt is a global-local option. 
When adding `noselect`, we need to treat `completeopt` as local and use `setlocal`.
This works for 9.1.0016 as well and allows users to freely mess with buffer-local `completeopt`
without messing up YCM completions.
Fixes #4261 
- - - …
> [READY] Use setlocal for temporary completeopt adjustment
