ycm-core/YouCompleteMe

README.md
I have signed the Google contributor license agreement
=> clarify how to check your version of vim is recent

README.md, doc/youcompleteme.txt
This goes with this change: https://github.com/Valloric/ycmd/pull/82
=> document g:ycm_csharp_server_port option

README.md
requeired is replaced with required
=> Spelling Mistake Corrected

README.md, python/ycm/vimsupport.py
I tried to give it a go at #1398. It definitely need a review, since python is not really my language (I just start to learning it), so I'm not sure this is the best algorithm. Plus, do the docs need more explaining for this new method?
I sign the CLA.
=> Add new-or-existing-tab as ycm_goto_buffer_command method

README.md
Hello,
As we discussed before, I move this documentation to the FAQ part,
old PR: https://github.com/Valloric/YouCompleteMe/pull/1447
Original Idea come from this issue: https://github.com/Valloric/YouCompleteMe/issues/1082
I've signed the CLA.
Guillaume.
=> Add installation with NeoBundle in the FAQ.

autoload/youcompleteme.vim, python/ycm/client/completer_available_request.py, python/ycm/youcompleteme.py
Sorry, I deleted the branch on github by mistake. Here is the same changes from #1530 plus a buffer local variable, so we don't try to set the `omnifunc` everytime we enter insert mode. I signed the CLA.
=> Fix completer available

README.md, doc/youcompleteme.txt
The documentation was updated to be in sync with ycmd @bfcfa21,
regarding default semantic hooks defined in ycmd's completer_utils.py.
=> Updating default semantic hooks.

autoload/youcompleteme.vim
Fix issues #1597 and #1598. These issues should contain enough information to understand the changes.
Thanks to @wladston.
=> Fix trigger issues

doc/youcompleteme.txt
Includes recent changes including FixIt and some other minor tweaks
=> Update vim help

CONTRIBUTING.md, README.md, doc/youcompleteme.txt, install.py, install.sh
Allow Windows users to run the script. 
Documentation updated.
=> [Windows support] Convert the install script to python

python/ycm/youcompleteme.py
Required for https://github.com/Valloric/ycmd/pull/210. Please see that PR for functional and testing details.
=> Pass cwd to completer for filename completions

README.md, doc/youcompleteme.txt
Remove Project Management entry.
=> Update table of contents in README

README.md, appveyor.yml, doc/youcompleteme.txt
@Valloric you need to add the YouCompleteMe project in your AppVeyor account. I'll update the badge.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1698)
=> [Windows support] Add AppVeyor configuration

autoload/youcompleteme.vim, python/ycm/paths.py, python/ycm/youcompleteme.py
This function contains mostly Vim-specific code and is only used in YouCompleteMe so we move it in vimsupport.py file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1719)
=> Move PathToPythonInterpreter function from ycmd to YouCompleteMe

README.md, doc/youcompleteme.txt
This is the first draft of the official Windows documentation.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1720)
=> Add Windows documentation

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1724)
=> Add notice to FAQ about ctags and C projects

README.md, doc/youcompleteme.txt
This PR closes #334.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1738)
=> Add GoToInclude documentation and update to latest ycmd

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1740)
=> Fedora documentation with required dependencies. Works on F22.

README.md, doc/youcompleteme.txt
Following PR #1740. Update the Vim documentation.
Maybe we should remove the `super-quick` in the titles to make them shorter and be consistent with the others. I'll update the PR if you agree.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1742)
=> Add an entry for Fedora installation in README.md

.gitmodules
See PR Valloric/ycmd#259.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1782)
=> Remove requests submodule

CONTRIBUTING.md, README.md, requirements.txt
In learning how to update this branch in #570, I added some docs on how to update it, and the requirements to do so.
Not going to be offended if you don't want/need this. I will forget, so I will squirrel it away somewhere :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1853)
=> Add developer documentation for the website

CONTRIBUTING.md
Not a huge deal but without those identations, the output will be 3 ordered lists instead of one.
Since this concerns the `gh-pages` branch, it should be directly merged.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1857)
=> [READY] Fix ordered list in CONTRIBUTING.md

index.html
Update the website to the latest readme.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1858)
=> Update to readme at 414f482b1c8c21460f933e89e2475295413c4543

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1861)
=> fixed readme path third-party with third_party

index.html
Fixing some paths.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1877)
=> Update to README.md at 07f4402f49a6cb987ebb17a4c17790816e06c3e7

python/ycm/client/completion_request.py, python/ycm/client/tests/completion_request_test.py
This is useful for hints for example, whose purpose is information
display solely.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1899)
=> Allows empty insertion text.

README.md, doc/youcompleteme.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1922)
=> Add notes to readme according to #1891.

README.md, doc/youcompleteme.txt
I've just wrote down the first things that came to mind. So any feedback on which part to expand or fix is appreciated. Specifically I don't know if would be useful to the user to know that JediHTTP exists and what it does. I fear that explaining would do more harm than good :confused:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1928)
=> [READY] Update documentation of latest python completer

python/ycm/base.py, python/ycm/client/base_request.py, python/ycm/client/command_request.py, python/ycm/client/completer_available_request.py, python/ycm/client/completion_request.py, python/ycm/client/event_notification.py, python/ycm/client/omni_completion_request.py, python/ycm/client/tests/command_request_test.py, python/ycm/client/tests/completion_request_test.py, python/ycm/client/ycmd_keepalive.py, python/ycm/diagnostic_interface.py, python/ycm/omni_completer.py, python/ycm/paths.py, python/ycm/syntax_parse.py, python/ycm/test_utils.py, python/ycm/tests/base_test.py, python/ycm/tests/event_notification_test.py, python/ycm/tests/omni_completion_request_tests.py, python/ycm/tests/paths_test.py, python/ycm/tests/postcomplete_tests.py, python/ycm/tests/syntax_parse_test.py, python/ycm/tests/vimsupport_test.py, python/ycm/vimsupport.py, python/ycm/youcompleteme.py
See PR Valloric/ycmd#346.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1962)
=> [READY] Remove interpreter line from Python sources

README.md, doc/youcompleteme.txt
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1964)
=> Update readme with typescript GoToReferences subcommand

autoload/youcompleteme.vim, python/ycm/diagnostic_interface.py, python/ycm/tests/base_test.py, python/ycm/tests/event_notification_test.py, python/ycm/youcompleteme.py
Moved file parse request handling into python, trying to simplify the overall flow, and allow easier additions of additional post handlers such as semantic token extraction.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1905)
=> [READY] Simplify parse request handling

autoload/youcompleteme.vim, install.py, python/test_requirements.txt, python/ycm/client/base_request.py, python/ycm/client/command_request.py, python/ycm/client/completion_request.py, python/ycm/client/omni_completion_request.py, python/ycm/vimsupport.py, python/ycm/youcompleteme.py, run_tests.py
Still using ycmd only in py2, but at least we can use YCM with ycmd master again.
@micbou @puremourning @vheon Try to give this one a whirl on your machines since ycmd had a ton of recent changes.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/1995)
=> [READY] Updating to latest ycmd

python/ycm/tests/youcompleteme_test.py
See PR #2004.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2005)
=> [READY] Add test to check if ycm_core is not imported

README.md, doc/youcompleteme.txt
Apparently, it is not possible to write a header on multiple lines using the `#` syntax in markdown, so we write it on one line.
Update the vim docs too.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2035)
=> [READY] Fix multiline title entry in FAQ

README.md, doc/youcompleteme.txt
Fixes #2042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2043)
=> Fix confusing phrasing in README

README.md
Was following the guides and saw this referencing a wrong path so I decided to fix it with the proper one.
Should be useful sine this will keep the docs up-to-date!
https://reviewable.io/reviews/valloric/youcompleteme/2047
=> Update tern_runtime directory in README

index.html
Update the website to the latest README at 385dae5ad977dc4cb18a5e143acf3eea7a6b8b60
Fixes https://github.com/Valloric/YouCompleteMe/issues/2046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2048)
=> Update from README

README.md, doc/youcompleteme.txt
Follow up of PR #2043.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2065)
=> [READY] Fix more confusing phrasing in README

README.md, doc/youcompleteme.txt
I spent a while trying to find where I had written the instructions for building python with pyenv to work with YCM, then I thought the README was a good place for it.
ycmd must use pythons with `--enable-shared` or `--enable-framework` else boom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme …
=> Add how to build python to avoid startup problems (in particular, pyenv)

README.md, doc/youcompleteme.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2095)
=> [READY] Add TypeScript RefactorRename subcommand to documentation

ci/travis/travis_install.sh
See PR Valloric/ycmd#459.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2118)
=> [READY] Fix and improve pyenv setup in Travis script

ci/travis/travis_install.sh
See PR Valloric/ycmd#460.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2120)
=> [READY] Fix pyenv setup on Travis

python/ycm/paths.py, python/ycm/tests/paths_test.py
Note: depends on Valloric/ycmd#466 being merged and the ycmd submodule
ref then being updated.
Fixes #2136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2140)
=> [READY] Starting ycmd with Python used to build it

.travis.yml, ci/appveyor/appveyor_install.bat, ci/travis/travis_install.linux.sh
Update ycmd to include PR Valloric/ycmd#481 and update Travis configuration according to this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2157)
=> [READY] Update Travis configuration

README.md
The golang details in the README are different than details for other additional languages. Adding a link to the golang download page and updating the wording makes the languages look the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
=> Update go installation details to match others

doc/youcompleteme.txt
Regenerated vim documentation with html2vimdoc.py to match README.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2196)
=> Update vim documentation with html2vimdoc

README.md
There is a bug in vim with Python 2.7.11 on Windows. Adding information in the FAQ.
This is a modification of this pull request: https://github.com/Valloric/YouCompleteMe/pull/2122.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcomple …
=> Add warning about Python 2.7.11 bug to FAQ

README.md, doc/youcompleteme.txt
Closes #2188.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2204)
=> [READY] Add instructions to install Mono in README

README.md, doc/youcompleteme.txt
This will document the enhancement that https://github.com/Valloric/ycmd/pull/429 brought to YCM. When this will be ready I will update the vim documentation too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2205)
=> [RFC] Document find first executable for ycm_python_binary_path

install.py
Closes #2206.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2207)
=> [READY] Check Python version in install script

README.md, doc/youcompleteme.txt
NeoBundle has been abandoned.
Also deleting the super-obsolete Bitdeli badge.
Fixes #2208.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2210)
=> [READY] Removing NeoBundle mentions from README

index.html
Fixes #2237.
This needs to be merged directly. We cannot use @homu here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2239)
=> [READY] Update website documentation

python/ycm/syntax_parse.py, python/ycm/tests/syntax_parse_test.py
Fixes #2269.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2282)
=> [READY] Extract keywords from the whole PreProc syntax group

README.md, doc/youcompleteme.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2281)
=> [READY] Recommend a more recent version for Python bug on Windows

.travis.yml, ci/travis/travis_script.sh
See https://github.com/Valloric/ycmd/pull/570.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2279)
=> [READY] Disable flake8 for Python 2.6 on Travis

README.md, doc/youcompleteme.txt
Add the `/property:Configuration=Release` option when building the OmniSharp server in the full installation guide.
Fixes #2188.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2284)
=> [READY] Update C# instructions in full installation guide

autoload/youcompleteme.vim
See discussion in PR #2265 and the commit message.
Since only the `BufEnter` autocommand event is concerned, we are splitting `s:OnBufferVisit` in two functions:
- `s:OnBufferRead`, identical to current `s:OnBufferVisit`, for the `BufRead` and `FileType` autocommand events;
- `s:OnBufferEnter` for the `BufEnter` event.
We only send the `BufferVisit` and `FileReadyToParse` event notifications to `ycmd` in `s:OnBufferEnter` when the entered buffer, in which we are allowed to complete, is different from the last one.
Closes #2265.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2312)
=> [READY] Do not send BufferVisit and FileReadyToParse notification events when current allowed buffer has not changed

README.md, doc/youcompleteme.txt
Wrong section level for this FAQ entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2324)
=> [READY] Fix FAQ entry in README

README.md, doc/youcompleteme.txt
Ubuntu 14.10 has Vim 7.4.273.
Closes #2361.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2362)
=> [READY] Bump Ubuntu version to 14.10 in documentation

python/ycm/tests/postcomplete_test.py
I couldn't resist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2382)
=> [READY] Rename postcomplete tests file to be consistent with other tests name

python/ycm/tests/__init__.py, python/ycm/tests/completion_test.py, python/ycm/tests/event_notification_test.py, python/ycm/tests/test_utils.py, python/ycm/tests/vimsupport_test.py, python/ycm/vimsupport.py, python/ycm/youcompleteme.py
This PR replaces each occurrence of `os.getcwd` by [the function helper `GetCurrentDirectory`](https://github.com/Valloric/ycmd/blob/master/ycmd/utils.py#L450) added in PR https://github.com/Valloric/ycmd/pull/622. This fixes three different issues covered by the new tests.
As in PR https://github.com/Valloric/ycmd/pull/622, I am only pushing the tests for now so that you can see the errors yourself. Note that these tests are only failing on Python 2 and the `CreateCompletionRequest_UnicodeWorkingDirectory` test only fails on Windows.
Fixes #2375.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2391)
=> [READY] Fix unicode issues when working with current directory on Python 2

python/ycm/youcompleteme.py
Fixes #2395.
Depends on PR https://github.com/Valloric/ycmd/pull/629.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2398)
=> [READY] Create temporary files in a secure manner

python/ycm/client/shutdown_request.py
This is what happens when you copy paste code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2406)
=> [READY] Remove unused code in shutdown request

python/ycm/youcompleteme.py
See PR https://github.com/Valloric/ycmd/pull/542.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2407)
=> [READY] Remove unloaded_buffer parameter

.gitignore, appveyor.yml
I forgot to do that when adding coverage.
Also, the `cover` folder is created at the project root, not in the `python` folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2412)
=> [READY] Enable coverage on AppVeyor

CONTRIBUTING.md, README.md, doc/youcompleteme.txt
This may help reduce the number of issues opened for questions or misconfigurations. This is also an alternative to the Google group for users that can't access it because of country regulations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2423)
=> [READY] Add Gitter badge and encourage users to ask questions on Gitter

.travis.yml, ci/travis/travis_script.sh, python/test_requirements.txt
See PR https://github.com/Valloric/ycmd/pull/665.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2476)
=> [READY] Do not disable Flake8 on Python 2.6 Travis but restrict its version

python/ycm/client/debug_info_request.py, python/ycm/tests/client/debug_info_request_test.py, python/ycm/tests/youcompleteme_test.py, python/ycm/youcompleteme.py
Depends on PR https://github.com/Valloric/ycmd/pull/601.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2342)
=> [READY] Implement new debugging information API

autoload/youcompleteme.vim
Small refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2513)
=> [READY] Remove s:GetCompletions function

python/ycm/tests/vimsupport_test.py, python/ycm/vimsupport.py
Fixes #2519
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2520)
=> Use bang version of `normal`

autoload/youcompleteme.vim, python/ycm/youcompleteme.py
Since PR #2517, the `BufferVisit` and `FileReadyToParse` requests are ignored until the server is ready. We need to send them again when it becomes ready so that identifiers and snippets for the current buffer are properly parsed. This is done in the `s:OnFileReadyToParse` function since this function is regularly called. We also try to set the omnifunc since it depends on a response from the server and is only set when entering a buffer or changing its filetype. This replaces the code that consisted of setting the omnifunc when entering insert mode for the first time.
A cleaner solution would be to do that asynchronously but we can't with our Vim version requirement.
Fixes #2541.
--- …
=> [RFC] Send requests again when server becomes ready

autoload/youcompleteme.vim, python/ycm/client/base_request.py
The requests module is slow to import. See https://github.com/kennethreitz/requests/issues/3213. We should lazy load it to improve startup time. We do that by adding two methods to the `BaseRequest` class: one that returns the requests module and another the session object since it depends on the `request-futures` module and `requests-futures` imports `requests`. In addition, we make sure that no requests are sent at startup otherwise there would be no point to lazy load these. These requests would fail anyway since the server can't be ready yet.
Here are the improvements on startup time:
<table>
<tr>
<th rowspan="2">Platform</th>
<th colspan="2">First run (ms)</th>
<th colspan="2">Subsequent runs (ms)</th>
</tr>
<tr>
<td>Before</td>
<td>After</td>
<td>Before</td>
<td>After</td>
</tr> …
=> [READY] Import the requests module lazily

README.md
Indents added in Ubuntu section (for easier copy&pasting).
PS. Tests are not included - minor documentation change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2565)
=> Indents added in Ubuntu and Fedora sections

README.md, appveyor.yml, doc/youcompleteme.txt
Release notes:
- PR https://github.com/Valloric/ycmd/pull/707: update racerd;
- PR https://github.com/Valloric/ycmd/pull/709: update Tern to 0.21.0;
- PR https://github.com/Valloric/ycmd/pull/711: fix https://github.com/Valloric/YouCompleteMe/issues/2532;
- PR https://github.com/Valloric/ycmd/pull/717: add Visual Studio 2017 and drop Visual Studio 2012 support.
Closes #2571.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2572)
=> [READY] Update ycmd

autoload/youcompleteme.vim
PR #2312 introduced an issue where the `completeopt`, `completefunc`, and `omnifunc` options are not set for buffers opened before the plugin is loaded. The `OnBufferVisit` function was split into `OnBufferRead` and `OnBufferEnter` but `SetUpCompleteopt`, `SetCompleteFunc`, and `SetOmnicompleteFunc` were not copied to `OnBufferEnter`.
Since the result of `VisitedBufferRequiresReparse` is identical to `AllowedToCompleteInCurrentBuffer` for a new buffer (its buffer number is necessarily new), we merge back the two functions into `OnBufferVisit` to fix the issue. Also, we change the `DisableOnLargeFile` function to include it in `AllowedToCompleteInCurrentBuffer`. This reduces duplication of code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> [READY] Merge back OnBufferRead and OnBufferEnter into OnBufferVisit

autoload/youcompleteme.vim
We can't use `VisitedBufferRequiresReparse` for the `FileType` autocommand event because ycmd may parse a buffer differently depending on its filetype. We have to use `AllowedToCompleteInCurrentBuffer` for this event (we can also use it for the `BufRead` one).
Fixes https://github.com/Valloric/ycmd/issues/731.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2595)
=> [READY] Split the OnBufferVisit function again

README.md, doc/youcompleteme.txt
Let's update before the end of year.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2603)
=> [READY] Update copyright years

README.md, doc/youcompleteme.txt
Items are not properly indented in the additional languages step of the Full Installation Guide section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2613)
=> [READY] Fix indentation in documentation

autoload/youcompleteme.vim
Since we only use the `b:ycm_changedtick` variable to track the last time we parsed the buffer, we can change it to store a number instead of a dictionary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2614)
=> [READY] Refactor b:ycm_changedtick variable

autoload/youcompleteme.vim
When visiting a buffer that was previously parsed, its last parse may be outdated because of changes from other buffers. We need to force a new parse.
This partially fixes issue https://github.com/Valloric/YouCompleteMe/issues/2165 in the sense that you don't have to edit the buffer (or call `:YcmForceCompileAndDiagnostics`) anymore to refresh diagnostics but you still have to wait for the `CursorHold` event. This can be further improved by displaying diagnostics asynchronously using timers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2629)
=> [READY] Force parsing on buffer visit

autoload/youcompleteme.vim
Since [we don't parse the buffer if no filetype is set](https://github.com/Valloric/YouCompleteMe/blob/ad00f4c3f4f6b41752950151d4ffba727c119dbd/autoload/youcompleteme.vim#L334), calling `s:OnBufferRead` on the `BufRead` event is only useful if the buffer filetype is set. But if that's the case, this means that the `FileType` event was fired before the `BufRead` one and thus the `s:OnBufferRead` function is already called. So, there is no point in calling `s:OnBufferRead` on the `BufRead` event. In fact, this costs us a `BufferVisit` and a `FileReadyToParse` request for nothing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2645)
=> [READY] Drop BufRead event

python/ycm/tests/vimsupport_test.py
This provides the most basic test for `EscapedFilepath()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2662)
=> Filepath space escaping

autoload/youcompleteme.vim, python/ycm/buffer.py, python/ycm/diagnostic_interface.py, python/ycm/tests/event_notification_test.py, python/ycm/tests/test_utils.py, python/ycm/tests/youcompleteme_test.py, python/ycm/vimsupport.py, python/ycm/youcompleteme.py
Removed dummy sign logic, now​ it places news signs, then removes obsolete ones. I did this in my fork long ago and never experienced any flicker.
Some source code refactoring, which I believe simplifies logic a little.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2677)
=> [Ready] Refactored diag interface, removed dummy sign.

python/ycm/tests/__init__.py, python/ycm/tests/event_notification_test.py, python/ycm/tests/youcompleteme_test.py
We don't need to mock the `IsServerReady` function if we check that the server is ready before running each test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2700)
=> [READY] Check if server is ready before running tests

autoload/youcompleteme.vim
Completing outside insert mode is not going to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2703)
=> [READY] Stop completion polling when leaving insert mode

README.md, doc/youcompleteme.txt
This ~~trigged~~ triggered me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2736)
=> [READY] Fix typo in documentation

ci/travis/travis_install.linux.sh, ci/travis/travis_install.sh
Travis complains that the `/home/travis/bin` folder already exist when creating it. Use `mkdir` with the `-p` option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2764)
=> [READY] Fix Linux builds on Travis

run_tests.py
See PR https://github.com/Valloric/ycmd/pull/829.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2769)
=> [READY] Run flake8 and nose as modules

python/ycm/youcompleteme.py
See PR https://github.com/Valloric/ycmd/pull/841.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2788)
=> [READY] Close options file before starting server

README.md
A typo in the ReadMe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2812)
=> Simple typo fix.

python/ycm/tests/client/completion_request_test.py
See PR https://github.com/Valloric/ycmd/pull/863.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2813)
=> [READY] Fix bare except statement

README.md
No tests needed since it's just a README change. Resolves #2824. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2825)
=> Mention in the docs that you need the exact version of Python that Vim is looking for

.circleci/config.yml, .circleci/install_dependencies.sh, .travis.yml, README.md, ci/travis/travis_install.sh, doc/youcompleteme.txt, plugin/youcompleteme.vim, python/test_requirements.txt, python/ycm/paths.py, python/ycm/tests/paths_test.py, python/ycm/tests/youcompleteme_test.py, run_tests.py
Since we are dropping support for Python 2.6 and 3.3 in Valloric/ycmd#904 we should drop support for them in YCM as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2887)
=> [READY] Drop Python 2.6 and Python 3.3

doc/youcompleteme.txt
Updates the Vim help to include recent changes, in particular Java help
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2906)
=> Update help doc

README.md, autoload/youcompleteme.vim, doc/youcompleteme.txt, python/ycm/client/command_request.py, python/ycm/tests/client/command_request_test.py, python/ycm/tests/command_test.py, python/ycm/tests/test_utils.py, python/ycm/vimsupport.py, python/ycm/youcompleteme.py
Implement the API introduced by PR https://github.com/Valloric/ycmd/pull/920.
PR https://github.com/Valloric/YouCompleteMe/pull/2898 is required for a bug-free formatting experience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2900)
=> [READY] Add range support to completer command

python/ycm/tests/youcompleteme_test.py
`:%s/YouCompelteMe/YouCompleteMe`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2910)
=> [READY] Fix typo in tests name

python/ycm/vimsupport.py
Forgot to do that in PR https://github.com/Valloric/YouCompleteMe/pull/2921.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2924)
=> [READY] Convert Vim command output to Unicode

.circleci/install_dependencies.sh, ci/travis/travis_install.sh
See PR https://github.com/Valloric/ycmd/pull/940.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2930)
=> [READY] Lower minimum Python version requirements on Travis and CircleCI

README.md, doc/youcompleteme.txt
I broke it in PR https://github.com/Valloric/YouCompleteMe/pull/2900.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2957)
=> [READY] Fix Refactoring Commands link in table of contents

README.md, doc/youcompleteme.txt
Closes https://github.com/Valloric/YouCompleteMe/issues/2971.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2972)
=> [READY] Mention Universal Ctags in docs

python/ycm/client/completion_request.py, python/ycm/tests/postcomplete_test.py
Fixes the issue mentioned in PR https://github.com/Valloric/YouCompleteMe/pull/2963 for Vim 8.0.1493 and later. I don't think it's worth the trouble to fix the issue for older versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2970)
=> [READY] Fix applying fixit twice after completion

autoload/youcompleteme.vim
We should check if completion is allowed when a character is inserted or deleted like we do with the other events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2979)
=> [READY] Check if completion is allowed on character events

.circleci/config.yml, .circleci/install_dependencies.sh, ci/travis/travis_install.sh
Attempt to fix the builds on Travis and CircleCI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2986)
=> [READY] Do not update pip on Travis and CircleCI

python/ycm/client/shutdown_request.py
Error found by [LGTM](https://lgtm.com/projects/g/Valloric/YouCompleteMe/alerts/?mode=list).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/2997)
=> [READY] Fix shutdown request init

index.html
This should be manually merged. Do not trigger @zzbot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3003)
=> [READY] Update website

python/test_requirements.txt, python/ycm/buffer.py, python/ycm/client/completion_request.py, python/ycm/syntax_parse.py, python/ycm/vimsupport.py, python/ycm/youcompleteme.py
See PR https://github.com/Valloric/ycmd/pull/1021.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3011)
=> [READY] Fix issues reported by the flake8-comprehensions plugin

README.md
- [ X] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [X ] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [ X] I have included tests for the changes in my PR. If not, I have included a
- [ X] **I understand my PR may be closed if it becomes obvious I didn't
The instructions for FreeBSD were not up-to-date. This works for FreeBSD 11.x (the latest). As I've only changed the readme, no tests were run.
[code]: …
=> Updating documentation for FreeBSd 11.x

README.md, autoload/youcompleteme.vim, doc/youcompleteme.txt, python/ycm/buffer.py
This PR follows Valloric/ycmd#1031. The specific changes are listed below:
- enable linting for cuda files
- disable syntastic for cuda files
- update docs
I have not included tests because there are no tests for the C++ counterparts.
--- …
=> Add CUDA support

README.md
Since the latest anaconda works with YCM, let's just state that it is not supported in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3013)
=> [READY] Anaconda python FAQ

README.md, doc/youcompleteme.txt
Forgot to remove this CMake generator in commit https://github.com/Valloric/YouCompleteMe/commit/9392f7fd6143344b4c2e1d3bbc2dc0257e3b4e87.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3032)
=> [READY] Remove Visual Studio 12 generator from the docs

README.md, doc/youcompleteme.txt
Some of them found with `:set spell`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3051)
=> [READY] Fix typos in documentation

appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3086)
=> [READY] Test Python 3.7 on AppVeyor

README.md, doc/youcompleteme.txt
See PR https://github.com/Valloric/ycmd/pull/1061.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3087)
=> [READY] Add g:ycm_filepath_blacklist option to documentation

README.md, doc/youcompleteme.txt
Update documentation to reflect the changes introduced by PRs https://github.com/Valloric/ycmd/pull/1035 and https://github.com/Valloric/ycmd/pull/1057.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3088)
=> [READY] Update C-family documentation

python/ycm/omni_completer.py, python/ycm/tests/omni_completer_test.py
Vim internally moves the cursor to the start column before calling the omnifunc a second time. This can be confirmed by starting Vim with the following vimrc:
```vim
set nocompatible
function! Omnifunc(findstart, base)
echom col('.')
if a:findstart		
if getline('.') == 'foo.ba'
return 4
endif
endif
return [ 'bar', 'baz']
endfunction
set omnifunc=Omnifunc
```
typing `foo.ba`, and hitting `<C-X><C-O>`. This outputs `7` and `5` on the command line which means that the cursor at column 7 on the first call of the omnifunc is moved to column 5 on the second call.
Since some omnifuncs depend on this to compute the list of candidates (e.g. the one defined by [the LanguageClient-neovim plugin](https://github.com/autozimu/LanguageClient-neovim)), we should reproduce that behavior in YCM.
Fixes …
=> [READY] Move cursor to start column before calling again omnifunc

.ycm_extra_conf.py, README.md, doc/youcompleteme.txt
This PR updates the Python docs and adds a `.ycm_extra_conf.py` file to be able to complete third-party packages in YCM code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3113)
=> [READY] Update Python documentation and add extra conf file

README.md
Info to not post at #vim is already stated in upper portion of README.md
rationale for why I haven't. (Doesn't need tests)
Removes repetitive information off the README.md file.
The message on the bottom of file might be a mistake:
> Please do NOT go to #vim on freenode for support. Please contact the YouCompleteMe maintainers directly using the contact details below.
..because we are already at the bottom of the README.
--- …
=> removes repetitive line

ci/appveyor/appveyor_install.bat, install.py, run_tests.py
See https://github.com/Valloric/ycmd/pull/1135 for reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3241)
=> [READY] Run flake8 on scripts in root

.gitmodules, .ycm_extra_conf.py, autoload/youcompleteme.vim
See Valloric/ycmd#1143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3263)
=> [READY] Do not use ycmd/third_party

python/ycm/client/completion_request.py, python/ycm/client/omni_completion_request.py, python/ycm/tests/client/omni_completion_request_tests.py, python/ycm/tests/postcomplete_test.py
Fixes #3274.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3275)
=> [READY] Do not apply fixits for omnifunc completion

autoload/youcompleteme.vim, python/ycm/youcompleteme.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3273)
=> [READY] Remove server_utils dependency

autoload/youcompleteme.vim
We need to reproduce [the complete python-future insertion logic of `server_utils.py`](https://github.com/Valloric/ycmd/blob/07757d4250886794652d87d04fa5eb53aee5f163/ycmd/server_utils.py#L35-L50) if we want to support virtualenv and embedded Python. See PRs https://github.com/Valloric/ycmd/pull/625 and https://github.com/Valloric/ycmd/pull/786.
I was a little worried on the performance impact of importing the `re` module and compiling the regex so I measured the time spent importing the modules and inserting python-future in `sys.path` and got less than 1ms (~0.5ms) so negligible compared to the whole startup time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/328 …
=> [READY] Support virtualenv and embedded Python

.gitmodules
See PR https://github.com/Valloric/ycmd/pull/1169.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3284)
=> [READY] Update requests URL

README.md, doc/youcompleteme.txt
Closes https://github.com/Valloric/YouCompleteMe/issues/765.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3302)
=> [READY] Add instruction on how to highlight lines without Vim gutter

README.md, plugin/youcompleteme.vim
clangd-based completer has been introduced into ycmd for a while now. I believe it is time to let users know about it as well. We are also updating clangd's docs and it would be nice to point people using vim into YCM docs for integration. You can see the patch for that one in https://reviews.llvm.org/D56718.
Also you can have a look at the end product of the changes at https://kadircet.github.io/YouCompleteMe
--- …
=> [READY] Add instructions for clangd into README

README.md, doc/youcompleteme.txt
Fixes a Clangd markdown link and other minor things in the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3345)
=> [READY] Fix Clangd link in docs

.circleci/config.yml, .circleci/install_dependencies.sh, .travis.yml, ci/travis/travis_install.sh, install.py, plugin/youcompleteme.vim, python/ycm/paths.py, python/ycm/tests/paths_test.py, python/ycm/tests/youcompleteme_test.py
see Valloric/ycmd#1207 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3344)
=> [READY] Drop python 3.4

python/ycm/tests/test_utils.py, python/ycm/tests/vimsupport_test.py, python/ycm/vimsupport.py
There is an issue on Windows where jumping to a file that is already open in a window doesn't go to that window if the case differs between the path of the file and the path of the buffer in the window (with `g:ycm_goto_command_buffer` sets to `'split-or-existing-window'`). This shouldn't happen since paths are case-insensitive on this platform. We need to ignore the case when comparing paths on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3390)
=> [READY] Ignore case when comparing paths on Windows and macOS

README.md, doc/youcompleteme.txt
Update the link to the MacVim installer and clarify the instructions on how to start Vim or MacVim from a terminal on macOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3391)
=> [READY] Instruct users to install MacVim with Homebrew

README.md
If the user has both python 2 and 3, and 2 is the configured alternative, the instructions will fail with missing headers. This change makes it clear that python3 is needed for this step (because a previous step installed python3-dev.)
If the user has both python 2 and 3, and 2 is the configured alternative, the instructions will fail with missing headers. This change makes it clear that python3 is needed for this step (because a previous step installed python3-dev.)
README.md change only--no tests needed. 
I successfully followed the instructions with the new command. …
=> Specify python3 in the README

.mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3394)
=> [READY] Set up Mergify configuration

python/test_requirements.txt
See Valloric/ycmd#1236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3370)
=> [READY] Update coverage.py

README.md, doc/youcompleteme.txt
This part was inadvertently removed in PR https://github.com/Valloric/YouCompleteMe/pull/3391.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3403)
=> [READY] Add back Vundle instruction in macOS section

.mergify.yml
Equivalent change to https://github.com/Valloric/ycmd/pull/1256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3413)
=> Allow maintainer to override reviewable, per ycmd

.mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3427)
=> Use ycm-core for mergify/azure

README.md, azure-pipelines.yml, doc/youcompleteme.txt, plugin/youcompleteme.vim
ycm-core/ycmd#1275 Remap python GoTo* commands
ycm-core/ycmd#1274 Migrate to Omnisharp-Roslyn
ycm-core/ycmd#1239 Error ID in diagnostic messages
ycm-core/ycmd#1267 Clangd extra conf support
ycm-core/ycmd#1266 JDT update to 0.40.0
ycm-core/ycmd#1245 Generic (pluggable) LSP completer support
ycm-core/ycmd#1263 Support JDT extensions
ycm-core/ycmd#1261 Typescript update
ycm-core/ycmd#1264 [vimspector](/puremourning/vimspector) configuration
ycm-core/ycmd#1262 Multi-user installation
ycm-core/ycmd#1243 Migrate to GOPLS
ycm-core/ycmd#1249 Support MSVC 16 (VS2019)
ycm-core/ycmd#1224 Migrate to RLS
actually perform …
=> [READY] Update ycmd submodule

azure/linux/install_dependencies.sh
same as https://github.com/ycm-core/ycmd/pull/1314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3486)
=> [READY] Fix azure openssl

autoload/youcompleteme.vim
Fixes https://github.com/Valloric/YouCompleteMe/issues/3420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/youcompleteme/3421)
=> [READY] Do not poll for messages in blacklisted filetypes

README.md, doc/youcompleteme.txt
Users have been allowed to manually specify the path to the C# solution
files for 5.5 years. This PR just documents how.
YCM has never documented the solution to #574 even though the relevant PR first appeared before the YCM/ycmd split and was merged shortly after the split.
Fixes #574
--- …
=> [READY] Document CSharSolutionFile

README.md, azure-pipelines.yml, python/ycm/client/command_request.py, python/ycm/tests/client/command_request_test.py, python/ycm/youcompleteme.py, test/README.md, test/docker/ci/image/Dockerfile, test/fixit.test.vim, test/lib/autoload/youcompleteme/test/setup.vim, test/testdata/cpp/fixit.c
Since ycm-core/ycmd#1338 introduces new API, this is the client side to take advantage of that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3502)
=> [READY] Handle unresolved fixits

azure-pipelines.yml
- Use python that compiles with openssl1.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3553)
=> [READY] Fix CI

README.md
Closes #3557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3558)
=> Fix simple typo: criticial -> critical

index.html
Depends on https://github.com/ycm-core/YouCompleteMe/pull/3571
Don't use the bot, just merge manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3572)
=> [NO BOT] update website

python/test_requirements.txt, python/ycm/tests/command_test.py, python/ycm/tests/completion_test.py, python/ycm/tests/event_notification_test.py, python/ycm/tests/omni_completer_test.py, python/ycm/tests/vimsupport_test.py, python/ycm/tests/youcompleteme_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3579)
=> [READY] Hamcrest deprecation warning

README.md
YCM moved repos and one of the links in the README was stale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3581)
=> Update link in README installation section

python/ycm/client/completion_request.py, python/ycm/tests/client/completion_request_test.py, python/ycm/tests/postcomplete_test.py
Fixes #3440 
The tests are missing, because they will be annoying to write.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3573)
=> [READY] Avoid calling _RawResponse when retrieving extra_data

azure-pipelines.yml, azure/linux/install_dependencies.sh, pytest.ini, python/test_requirements.txt, python/ycm/tests/__init__.py, python/ycm/tests/base_test.py, python/ycm/tests/client/base_request_test.py, python/ycm/tests/client/command_request_test.py, python/ycm/tests/client/completion_request_test.py, python/ycm/tests/client/messages_request_test.py, python/ycm/tests/client/omni_completion_request_test.py, python/ycm/tests/client/omni_completion_request_tests.py, python/ycm/tests/command_test.py, python/ycm/tests/completion_test.py, python/ycm/tests/conftest.py, python/ycm/tests/event_notification_test.py, python/ycm/tests/mock_utils.py, python/ycm/tests/omni_completer_test.py, python/ycm/tests/paths_test.py, python/ycm/tests/postcomplete_test.py, python/ycm/tests/test_utils.py, python/ycm/tests/vimsupport_test.py, python/ycm/tests/youcompleteme_test.py, run_tests.py
We're finally here. We need to replace nose, which is unmaintained, with something and "yours truly" believes that pytest is the best option we got.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3590)
=> [READY] Switch to pytest

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, vimrc_ycm_minimal
We frequently ask for this, so might as well make it the requirement.
As part of our documentation refresh, add a way to simply do minimal repro cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3618)
=> Add minimal vimrc repro instruction to CONTRIBUTING.md

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
Well, it's not quite "ready". The section about the generic LSP is missing and the gif demo has not been updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3606)
=> [READY] Update README.md

README.md, doc/youcompleteme.txt
Closes #3597 
This PR adds some new demo gifs to show off unicode support (I believe we're the only one who can do that), signature help and subcommands.
The website will be updated after this pull request is merged.
--- …
=> [READY] New demo gifs and generic LSP

azure-pipelines.yml
See ycm-core/ycmd#1406 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3621)
=> [READY] Update CI images

azure/linux/install_dependencies.sh
Same as ycmd - need to ensure we `apt update` before `apt-get install`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3623)
=> [READY] Ensure we have latest apt info

README.md, doc/youcompleteme.txt
Since the last README update, I've noticed a few problems:
- A dead link - removed
- Not-a-link that should have been a link - fixed
- Duplicated signature help gif - gifs reordered
- At the top now is the old completion gif.
- Then there's the brief unicode brag.
- Then the subcommands gif.
- Finally @puremourning's signature help gif with a somewhat detailed description.
[code]: …
=> [READY] Cleanup since the last README update

README.md, doc/youcompleteme.txt, test/docker/manual/foo.py, test/fixit.test.vim
- Implement didChangeWatchedFiles support
- Upgrade to LLVM10
- Update to unicode 13
- Use non-reentrant locks everywhere
- Update rust to nightly-2020-03-12 (Fixes #3587)
- Improve hover rendering for the GenericLSPCompleter
- Update jdtls to 0.52.0
- Re-Add gopls FixIt test
- Add GoToImplementation test for gopls
- Update gopls to 0.3.3
- Allow users to specify paths to external executables
[code]: …
=> [READY] Update the ycmd submodule to the latest commit

autoload/youcompleteme.vim, python/ycm/youcompleteme.py
Made for purposes of testing ycm-core/ycmd#1428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3660)
=> [READY] Implement FileSave event

README.md
C# semantic completion wasn't linked in the ToC of the README.md. Link added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3695)
=> Added link to C# Semantic Completion section

README.md, doc/youcompleteme.txt, python/ycm/client/command_request.py, python/ycm/vimsupport.py
This is the client side to ycmd's `is_preferred`. Not ready, because it depends on server side changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3700)
=> [READY] Rely on `kind` for auto-applying fixits

README.md, doc/youcompleteme.txt, install.py, plugin/youcompleteme.vim, python/ycm/client/base_request.py, python/ycm/client/completion_request.py, python/ycm/client/debug_info_request.py, python/ycm/paths.py, python/ycm/signature_help.py, python/ycm/tests/client/command_request_test.py, python/ycm/tests/client/completion_request_test.py, python/ycm/tests/conftest.py, python/ycm/tests/paths_test.py, python/ycm/tests/test_utils.py, python/ycm/tests/vimsupport_test.py, python/ycm/tests/youcompleteme_test.py, python/ycm/vimsupport.py, python/ycm/youcompleteme.py
As discussed previously, this drops support for python 3.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3722)
=> Drop python 3.5 support

python/ycm/tests/base_test.py, python/ycm/tests/completion_test.py, python/ycm/tests/event_notification_test.py, python/ycm/tests/vimsupport_test.py
This is the minimal change required to avoid problems with NFS4 not being able to handle [the hwair character](https://en.wikipedia.org/wiki/Hwair) in file names.
Fixes: #3365 
Closes: #3600 
--- …
=> [READY] Avoid "Hwair" character in file names

autoload/youcompleteme.vim
Fixes #3748 
I have not added a test, because the change is really small and I was lazy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3749)
=> [READY] Make the popup preview check stricter

python/ycm/diagnostic_filter.py
Like I mentioned in gitter, the deleted portion was never used.
The diagnostics filter is used by:
1. Creating a `_MasterDiagnosticFilter` instace by calling the `DiagnosticFilter.CreateFromOptions()` static method.
1.1 The name `_MasterDiagnosticFilter` is misleading, as it is basically just a cache.
2. Then the user of the filter (the diagnostic_interface) asks for a subset of the "master filter", corresponding to the current filetype, by calling `_MasterDiagnosticFilter.SubsetForTypes()`.
2.1 *That* …
=> [READY] Simplify diagnostic filter

plugin/youcompleteme.vim
- [ x ] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [ x ] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [ x ] I have included tests for the changes in my PR. If not, I have included a
- [ x ] **I understand my PR may be closed if it becomes obvious I didn't
vim considers the spaces in the let command added by a recent commit an error, so I removed them.
---
This change …
=> Remove spaces in let command to please vim.

README.md
Updates the README.md for macOs installation. This PR provides the user the option to use Homebrew installed vim rather than just the sole option of macvim. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3803)
=> Update README.md macOS installation for vim and macvim

README.md
This update should also close some open YCM issues, but I haven't checked them all. At least the one complaining about watchdog.
Feel free to suggest a different/better README update.
Changelog:
- Added docs in the `/signature_help` response
- Dropped Requests and Waitress from dependencies
- Upgraded gopls to 0.6.4
- Upgraded TSserver to 4.1.5
- Upgraded watchdog, avoiding warnings at compile time.
- CMake 3.14 is now required, again, avoiding warnings about deprecation.
- Added `GoToDocumentOutline` …
=> [READY] At long last, update the ycmd submodule

.github/workflows/ci.yml, .mergify.yml, test/vimrc
Just as I said "works"...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3872)
=> Fix CI config errors

.gitmodules, python/ycm/client/base_request.py, python/ycm/client/signature_help_request.py, python/ycm/tests/conftest.py, python/ycm/tests/mock_utils.py
This is the best we can do, without #3792. It seems to work fine, but there's just one thing that's bothering me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3809)
=> [READY] Drop the dependency on requests

autoload/youcompleteme.vim
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3917)
=> [READY] Remove stale python paths from sys.path

README.md, plugin/youcompleteme.vim, python/ycm/buffer.py, python/ycm/diagnostic_interface.py, python/ycm/tests/conftest.py, python/ycm/youcompleteme.py, test/completion.common.vim, test/diagnostics.test.vim
This has come up a few times with different users, me included. Some prefer not to see diagnostic updates while typing.
Fixes #3888
Hopefully, the vim tests won't give me too much trouble.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/yo …
=> [READY] Allow users to opt-out of diagnostics update in insert mode

README.md
This pull request fixes typo in README.md - 'brea' instead of 'brew' to install a MacOS package via Homebrew.
I didn't create any test case as I didn't modify the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3988)
=> Fix typo in README.md - 'brea' instead of 'brew'

README.md
Reading ease. No tests are applicable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3998)
=> Fix a few spelling typos

.mergify.yml
https://blog.mergify.com/strict-mode-deprecation/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4002)
=> Switch to mergify queues (YCM)

README.md, autoload/youcompleteme.vim, python/ycm/buffer.py, python/ycm/diagnostic_interface.py, python/ycm/tests/youcompleteme_test.py, python/ycm/vimsupport.py, python/ycm/youcompleteme.py, test/diagnostics.test.vim
Fixes #3910 
No tests, because I'm not sure what kind of API there is to test this.
RFC because the popup is using default options and I'm open for debates on that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/3913)
=> [READY] Allow display of diagnostics in a popup

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4037)
=> fix: typos with ycm_enable_semantic_highlighting

README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4039)
=> fix: typo in highlight groups section

python/ycm/diagnostic_interface.py, python/ycm/inlay_hints.py, python/ycm/semantic_highlighting.py, python/ycm/text_properties.py
When available use the "types" list in prop_remove
https://github.com/vim/vim/pull/10945
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4047)
=> Reduce calls to prop_remove

.github/workflows/ci.yml, README.md
Fixes #4063
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4066)
=> Update ycmd : update jdtls

autoload/youcompleteme/finder.vim
Fixes #4059
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4067)
=> Fix cursorlineopt

.github/workflows/update_vim_docs.yaml, .mergify.yml, doc/youcompleteme.txt, update-vim-docs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4079)
=> Auto update vim docs

README.md
Fix two minor typos in README.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4082)
=> Fix 2 minor typos in README

doc/youcompleteme.txt
Update the vim docs after recent changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4080)
=> [Auto] Update vim docs

python/ycm/diagnostic_interface.py, python/ycm/tests/diagnostic_interface_test.py
it might happen in invalid libclang result
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/youcompleteme/4091)
=> Accept invalid end_lnum field in diagnose parse

.github/workflows/ci.yml, python/ycm/youcompleteme.py, test/diagnostics.test.vim, test/docker/ci/image/Dockerfile, test/docker/ci/push, test/docker/ci/rebuild, test/docker/manual/image/Dockerfile, test/docker/manual/push, test/docker/manual/rebuild, test/docker/manual/run, test/finder.test.vim, test/lib/autoload/youcompleteme/test/setup.vim, test/lib/plugin/shared.vim, test/lib/run_test.vim
Fixes #4125
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4126)
=> Fix traceback when diagnostics contain quotes

python/ycm/vimsupport.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4139)
=> Yet more attempts to catch 'changedtick' returning ''

test/README.md
Fixing typos is good.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4174)
=> Fix typos in readme

.github/workflows/ci.yml
Because github is complaining about the age of actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4175)
=> [READY] Update all actions

python/ycm/vimsupport.py
Fixes #4182
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4183)
=> Replace tabs with spaces when echoing a message

CODE_OF_CONDUCT.md
The trivial changes improve readability and correctness.
Tests are not included because no code has been changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/YouCompleteMe/4270)
=> Fix typos in the code of conduct document
